# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3e13df4ace506f13b79976108cf9d8175b1d723dfd5526d6dae8f693b23136bd65c23313499124b672e17820ee5e75a129536a7ddc7412717507e6b018b51047

test:
  secret_key_base: 77692eb6f9e2a3890c557d2fa780f5bb240e9500ffb48e5938132832dc5999aeaeec9805ee0223b0abbeaf9b24f75ad1f5888f68a678c2706c5dd1d6a1d02e89

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
