# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

 development:
  adapter: postgresql
  encoding: unicode
  database: pagoprueba-api
  pool: 5
  username: postgres
  password: 123456

test:
  adapter: postgresql
  encoding: unicode
  database: pagoprueba-api-test
  pool: 5
  username: postgres
  password: 123456