<?php

return array (
  0 => 
  array (
    'id' => 1,
    'odoo_code_id' => 'base.ad',
    'name' => 'Andorra',
    'nationality' => 'Andorrana',
    'code' => 'ad',
    'phone_code' => '+376',
    'currency_code' => 'EUR',
    'latitude' => 42.5,
    'longitude' => 1.5,
    'is_active' => true,
  ),
  1 => 
  array (
    'id' => 2,
    'odoo_code_id' => 'base.ae',
    'name' => 'Emiratos Árabes Unidos',
    'nationality' => 'Emirati',
    'code' => 'ae',
    'phone_code' => '+971',
    'currency_code' => 'AED',
    'latitude' => 24.0,
    'longitude' => 54.0,
    'is_active' => true,
  ),
  2 => 
  array (
    'id' => 3,
    'odoo_code_id' => 'base.af',
    'name' => 'Afganistán',
    'nationality' => 'Afgana',
    'code' => 'af',
    'phone_code' => '+93',
    'currency_code' => 'AFN',
    'latitude' => 33.0,
    'longitude' => 65.0,
    'is_active' => true,
  ),
  3 => 
  array (
    'id' => 4,
    'odoo_code_id' => 'base.ag',
    'name' => 'Antigua y Barbuda',
    'nationality' => 'Antiguana',
    'code' => 'ag',
    'phone_code' => '+1268',
    'currency_code' => 'XCD',
    'latitude' => 17.05,
    'longitude' => -61.8,
    'is_active' => true,
  ),
  4 => 
  array (
    'id' => 5,
    'odoo_code_id' => 'base.ai',
    'name' => 'Anguila',
    'nationality' => 'Anguilana',
    'code' => 'ai',
    'phone_code' => '+1264',
    'currency_code' => 'XCD',
    'latitude' => 18.25,
    'longitude' => -63.16666666,
    'is_active' => true,
  ),
  5 => 
  array (
    'id' => 6,
    'odoo_code_id' => 'base.al',
    'name' => 'Albania',
    'nationality' => 'Albanesa',
    'code' => 'al',
    'phone_code' => '+355',
    'currency_code' => 'ALL',
    'latitude' => 41.0,
    'longitude' => 20.0,
    'is_active' => true,
  ),
  6 => 
  array (
    'id' => 7,
    'odoo_code_id' => 'base.am',
    'name' => 'Armenia',
    'nationality' => 'Armenia',
    'code' => 'am',
    'phone_code' => '+374',
    'currency_code' => 'AMD',
    'latitude' => 40.0,
    'longitude' => 45.0,
    'is_active' => true,
  ),
  7 => 
  array (
    'id' => 8,
    'odoo_code_id' => 'base.ar',
    'name' => 'Argentina',
    'nationality' => 'Argentina',
    'code' => 'ar',
    'phone_code' => '+54',
    'currency_code' => 'ARS',
    'latitude' => -34.0,
    'longitude' => -64.0,
    'is_active' => true,
  ),
  8 => 
  array (
    'id' => 9,
    'odoo_code_id' => 'base.at',
    'name' => 'Austria',
    'nationality' => 'Austriaca',
    'code' => 'at',
    'phone_code' => '+43',
    'currency_code' => 'EUR',
    'latitude' => 47.33333333,
    'longitude' => 13.33333333,
    'is_active' => true,
  ),
  9 => 
  array (
    'id' => 10,
    'odoo_code_id' => 'base.au',
    'name' => 'Australia',
    'nationality' => 'Australiana',
    'code' => 'au',
    'phone_code' => '+61',
    'currency_code' => 'AUD',
    'latitude' => -27.0,
    'longitude' => 133.0,
    'is_active' => true,
  ),
  10 => 
  array (
    'id' => 11,
    'odoo_code_id' => 'base.aw',
    'name' => 'Aruba',
    'nationality' => 'Arubeña',
    'code' => 'aw',
    'phone_code' => '+297',
    'currency_code' => 'AWG',
    'latitude' => 12.5,
    'longitude' => -69.96666666,
    'is_active' => true,
  ),
  11 => 
  array (
    'id' => 12,
    'odoo_code_id' => 'base.az',
    'name' => 'Azerbaiyán',
    'nationality' => 'Azerbaiyana',
    'code' => 'az',
    'phone_code' => '+994',
    'currency_code' => 'AZN',
    'latitude' => 40.5,
    'longitude' => 47.5,
    'is_active' => true,
  ),
  12 => 
  array (
    'id' => 13,
    'odoo_code_id' => 'base.ba',
    'name' => 'Bosnia y Herzegovina',
    'nationality' => 'Bosnia',
    'code' => 'ba',
    'phone_code' => '+387',
    'currency_code' => 'BAM',
    'latitude' => 44.0,
    'longitude' => 18.0,
    'is_active' => true,
  ),
  13 => 
  array (
    'id' => 14,
    'odoo_code_id' => 'base.bb',
    'name' => 'Barbados',
    'nationality' => 'Barbadense',
    'code' => 'bb',
    'phone_code' => '+1246',
    'currency_code' => 'BBD',
    'latitude' => 13.16666666,
    'longitude' => -59.53333333,
    'is_active' => true,
  ),
  14 => 
  array (
    'id' => 15,
    'odoo_code_id' => 'base.bd',
    'name' => 'Bangladés',
    'nationality' => 'Bangladesi',
    'code' => 'bd',
    'phone_code' => '+880',
    'currency_code' => 'BDT',
    'latitude' => 24.0,
    'longitude' => 90.0,
    'is_active' => true,
  ),
  15 => 
  array (
    'id' => 16,
    'odoo_code_id' => 'base.be',
    'name' => 'Bélgica',
    'nationality' => 'Belga',
    'code' => 'be',
    'phone_code' => '+32',
    'currency_code' => 'EUR',
    'latitude' => 50.83333333,
    'longitude' => 4.0,
    'is_active' => true,
  ),
  16 => 
  array (
    'id' => 17,
    'odoo_code_id' => 'base.bg',
    'name' => 'Bulgaria',
    'nationality' => 'Bulgara',
    'code' => 'bg',
    'phone_code' => '+359',
    'currency_code' => 'BGN',
    'latitude' => 43.0,
    'longitude' => 25.0,
    'is_active' => true,
  ),
  17 => 
  array (
    'id' => 18,
    'odoo_code_id' => 'base.bh',
    'name' => 'Baréin',
    'nationality' => 'Bahreiní',
    'code' => 'bh',
    'phone_code' => '+973',
    'currency_code' => 'BHD',
    'latitude' => 26.0,
    'longitude' => 50.55,
    'is_active' => true,
  ),
  18 => 
  array (
    'id' => 19,
    'odoo_code_id' => 'base.bl',
    'name' => 'San Bartolomé',
    'nationality' => 'Bartolomense',
    'code' => 'bl',
    'phone_code' => '+590',
    'currency_code' => 'EUR',
    'latitude' => 18.5,
    'longitude' => -63.41666666,
    'is_active' => true,
  ),
  19 => 
  array (
    'id' => 20,
    'odoo_code_id' => 'base.bm',
    'name' => 'Bermudas',
    'nationality' => 'Bermudeña',
    'code' => 'bm',
    'phone_code' => '+1441',
    'currency_code' => 'BMD',
    'latitude' => 32.33333333,
    'longitude' => -64.75,
    'is_active' => true,
  ),
  20 => 
  array (
    'id' => 21,
    'odoo_code_id' => 'base.bn',
    'name' => 'Brunéi',
    'nationality' => 'Bruneana',
    'code' => 'bn',
    'phone_code' => '+673',
    'currency_code' => 'BND',
    'latitude' => 4.5,
    'longitude' => 114.66666666,
    'is_active' => true,
  ),
  21 => 
  array (
    'id' => 22,
    'odoo_code_id' => 'base.bo',
    'name' => 'Bolivia',
    'nationality' => 'Boliviana',
    'code' => 'bo',
    'phone_code' => '+591',
    'currency_code' => 'BOB',
    'latitude' => -17.0,
    'longitude' => -65.0,
    'is_active' => true,
  ),
  22 => 
  array (
    'id' => 23,
    'odoo_code_id' => 'base.br',
    'name' => 'Brasil',
    'nationality' => 'Brasileña',
    'code' => 'br',
    'phone_code' => '+55',
    'currency_code' => 'BRL',
    'latitude' => -10.0,
    'longitude' => -55.0,
    'is_active' => true,
  ),
  23 => 
  array (
    'id' => 24,
    'odoo_code_id' => 'base.bs',
    'name' => 'Bahamas',
    'nationality' => 'Bahameña',
    'code' => 'bs',
    'phone_code' => '+1242',
    'currency_code' => 'BSD',
    'latitude' => 25.0343,
    'longitude' => -77.3963,
    'is_active' => true,
  ),
  24 => 
  array (
    'id' => 25,
    'odoo_code_id' => 'base.bt',
    'name' => 'Bután',
    'nationality' => 'Butanesa',
    'code' => 'bt',
    'phone_code' => '+975',
    'currency_code' => 'BTN',
    'latitude' => 27.5,
    'longitude' => 90.5,
    'is_active' => true,
  ),
  25 => 
  array (
    'id' => 26,
    'odoo_code_id' => 'base.by',
    'name' => 'Bielorrusia',
    'nationality' => 'Bielorrusa',
    'code' => 'by',
    'phone_code' => '+375',
    'currency_code' => 'BYN',
    'latitude' => 53.0,
    'longitude' => 28.0,
    'is_active' => true,
  ),
  26 => 
  array (
    'id' => 27,
    'odoo_code_id' => 'base.bz',
    'name' => 'Belice',
    'nationality' => 'Beliceña',
    'code' => 'bz',
    'phone_code' => '+501',
    'currency_code' => 'BZD',
    'latitude' => 17.25,
    'longitude' => -88.75,
    'is_active' => true,
  ),
  27 => 
  array (
    'id' => 28,
    'odoo_code_id' => 'base.ca',
    'name' => 'Canadá',
    'nationality' => 'Canadiense',
    'code' => 'ca',
    'phone_code' => '+1',
    'currency_code' => 'CAD',
    'latitude' => 60.0,
    'longitude' => -95.0,
    'is_active' => true,
  ),
  28 => 
  array (
    'id' => 29,
    'odoo_code_id' => 'base.ch',
    'name' => 'Suiza',
    'nationality' => 'Suiza',
    'code' => 'ch',
    'phone_code' => '+41',
    'currency_code' => 'CHF',
    'latitude' => 47.0,
    'longitude' => 8.0,
    'is_active' => true,
  ),
  29 => 
  array (
    'id' => 30,
    'odoo_code_id' => 'base.cl',
    'name' => 'Chile',
    'nationality' => 'Chilena',
    'code' => 'cl',
    'phone_code' => '+56',
    'currency_code' => 'CLP',
    'latitude' => -30.0,
    'longitude' => -71.0,
    'is_active' => true,
  ),
  30 => 
  array (
    'id' => 31,
    'odoo_code_id' => 'base.cn',
    'name' => 'China',
    'nationality' => 'China',
    'code' => 'cn',
    'phone_code' => '+86',
    'currency_code' => 'CNY',
    'latitude' => 35.0,
    'longitude' => 105.0,
    'is_active' => true,
  ),
  31 => 
  array (
    'id' => 32,
    'odoo_code_id' => 'base.co',
    'name' => 'Colombia',
    'nationality' => 'Colombiana',
    'code' => 'co',
    'phone_code' => '+57',
    'currency_code' => 'COP',
    'latitude' => 4.0,
    'longitude' => -72.0,
    'is_active' => true,
  ),
  32 => 
  array (
    'id' => 33,
    'odoo_code_id' => 'base.cr',
    'name' => 'Costa Rica',
    'nationality' => 'Costarricense',
    'code' => 'cr',
    'phone_code' => '+506',
    'currency_code' => 'CRC',
    'latitude' => 10.0,
    'longitude' => -84.0,
    'is_active' => true,
  ),
  33 => 
  array (
    'id' => 34,
    'odoo_code_id' => 'base.cu',
    'name' => 'Cuba',
    'nationality' => 'Cubana',
    'code' => 'cu',
    'phone_code' => '+53',
    'currency_code' => 'CUC',
    'latitude' => 21.5,
    'longitude' => -80.0,
    'is_active' => true,
  ),
  34 => 
  array (
    'id' => 35,
    'odoo_code_id' => 'base.cw',
    'name' => 'Curazao',
    'nationality' => 'Curazaleña',
    'code' => 'cw',
    'phone_code' => '+599',
    'currency_code' => 'ANG',
    'latitude' => 12.116667,
    'longitude' => -68.933333,
    'is_active' => true,
  ),
  35 => 
  array (
    'id' => 36,
    'odoo_code_id' => 'base.cy',
    'name' => 'Chipre',
    'nationality' => 'Chipriota',
    'code' => 'cy',
    'phone_code' => '+357',
    'currency_code' => 'EUR',
    'latitude' => 35.0,
    'longitude' => 33.0,
    'is_active' => true,
  ),
  36 => 
  array (
    'id' => 37,
    'odoo_code_id' => 'base.cz',
    'name' => 'República Checa',
    'nationality' => 'Checa',
    'code' => 'cz',
    'phone_code' => '+420',
    'currency_code' => 'CZK',
    'latitude' => 49.75,
    'longitude' => 15.5,
    'is_active' => true,
  ),
  37 => 
  array (
    'id' => 38,
    'odoo_code_id' => 'base.de',
    'name' => 'Alemania',
    'nationality' => 'Alemana',
    'code' => 'de',
    'phone_code' => '+49',
    'currency_code' => 'EUR',
    'latitude' => 51.0,
    'longitude' => 9.0,
    'is_active' => true,
  ),
  38 => 
  array (
    'id' => 39,
    'odoo_code_id' => 'base.dk',
    'name' => 'Dinamarca',
    'nationality' => 'Danesa',
    'code' => 'dk',
    'phone_code' => '+45',
    'currency_code' => 'DKK',
    'latitude' => 56.0,
    'longitude' => 10.0,
    'is_active' => true,
  ),
  39 => 
  array (
    'id' => 40,
    'odoo_code_id' => 'base.dm',
    'name' => 'Dominica',
    'nationality' => 'Dominiquesa',
    'code' => 'dm',
    'phone_code' => '+1767',
    'currency_code' => 'XCD',
    'latitude' => 15.41666666,
    'longitude' => -61.33333333,
    'is_active' => true,
  ),
  40 => 
  array (
    'id' => 41,
    'odoo_code_id' => 'base.do',
    'name' => 'República Dominicana',
    'nationality' => 'Dominicana',
    'code' => 'do',
    'phone_code' => '+1809',
    'currency_code' => 'DOP',
    'latitude' => 19.0,
    'longitude' => -70.66666666,
    'is_active' => true,
  ),
  41 => 
  array (
    'id' => 42,
    'odoo_code_id' => 'base.ec',
    'name' => 'Ecuador',
    'nationality' => 'Ecuatoriana',
    'code' => 'ec',
    'phone_code' => '+593',
    'currency_code' => 'USD',
    'latitude' => -2.0,
    'longitude' => -77.5,
    'is_active' => true,
  ),
  42 => 
  array (
    'id' => 43,
    'odoo_code_id' => 'base.ee',
    'name' => 'Estonia',
    'nationality' => 'Estonia',
    'code' => 'ee',
    'phone_code' => '+372',
    'currency_code' => 'EUR',
    'latitude' => 59.0,
    'longitude' => 26.0,
    'is_active' => true,
  ),
  43 => 
  array (
    'id' => 44,
    'odoo_code_id' => 'base.es',
    'name' => 'España',
    'nationality' => 'Española',
    'code' => 'es',
    'phone_code' => '+34',
    'currency_code' => 'EUR',
    'latitude' => 40.0,
    'longitude' => -4.0,
    'is_active' => true,
  ),
  44 => 
  array (
    'id' => 45,
    'odoo_code_id' => 'base.fi',
    'name' => 'Finlandia',
    'nationality' => 'Finlandesa',
    'code' => 'fi',
    'phone_code' => '+358',
    'currency_code' => 'EUR',
    'latitude' => 64.0,
    'longitude' => 26.0,
    'is_active' => true,
  ),
  45 => 
  array (
    'id' => 46,
    'odoo_code_id' => 'base.fr',
    'name' => 'Francia',
    'nationality' => 'Francesa',
    'code' => 'fr',
    'phone_code' => '+33',
    'currency_code' => 'EUR',
    'latitude' => 46.0,
    'longitude' => 2.0,
    'is_active' => true,
  ),
  46 => 
  array (
    'id' => 47,
    'odoo_code_id' => 'base.ge',
    'name' => 'Georgia',
    'nationality' => 'Georgiana',
    'code' => 'ge',
    'phone_code' => '+995',
    'currency_code' => 'GEL',
    'latitude' => 42.0,
    'longitude' => 43.5,
    'is_active' => true,
  ),
  47 => 
  array (
    'id' => 48,
    'odoo_code_id' => 'base.gi',
    'name' => 'Gibraltar',
    'nationality' => 'Gibraltareña',
    'code' => 'gi',
    'phone_code' => '+350',
    'currency_code' => 'GIP',
    'latitude' => 36.13333333,
    'longitude' => -5.35,
    'is_active' => true,
  ),
  48 => 
  array (
    'id' => 49,
    'odoo_code_id' => 'base.gl',
    'name' => 'Groenlandia',
    'nationality' => 'Groenlandesa',
    'code' => 'gl',
    'phone_code' => '+299',
    'currency_code' => 'DKK',
    'latitude' => 72.0,
    'longitude' => -40.0,
    'is_active' => true,
  ),
  49 => 
  array (
    'id' => 50,
    'odoo_code_id' => 'base.gr',
    'name' => 'Grecia',
    'nationality' => 'Griega',
    'code' => 'gr',
    'phone_code' => '+30',
    'currency_code' => 'EUR',
    'latitude' => 39.0,
    'longitude' => 22.0,
    'is_active' => true,
  ),
  50 => 
  array (
    'id' => 51,
    'odoo_code_id' => 'base.gt',
    'name' => 'Guatemala',
    'nationality' => 'Guatemalteca',
    'code' => 'gt',
    'phone_code' => '+502',
    'currency_code' => 'GTQ',
    'latitude' => 15.5,
    'longitude' => -90.25,
    'is_active' => true,
  ),
  51 => 
  array (
    'id' => 52,
    'odoo_code_id' => 'base.gy',
    'name' => 'Guyana',
    'nationality' => 'Guyanesa',
    'code' => 'gy',
    'phone_code' => '+592',
    'currency_code' => 'GYD',
    'latitude' => 5.0,
    'longitude' => -59.0,
    'is_active' => true,
  ),
  52 => 
  array (
    'id' => 53,
    'odoo_code_id' => 'base.hk',
    'name' => 'Hong Kong',
    'nationality' => 'Hongkonesa',
    'code' => 'hk',
    'phone_code' => '+852',
    'currency_code' => 'HKD',
    'latitude' => 22.267,
    'longitude' => 114.188,
    'is_active' => true,
  ),
  53 => 
  array (
    'id' => 54,
    'odoo_code_id' => 'base.hn',
    'name' => 'Honduras',
    'nationality' => 'Hondureña',
    'code' => 'hn',
    'phone_code' => '+504',
    'currency_code' => 'HNL',
    'latitude' => 15.0,
    'longitude' => -86.5,
    'is_active' => true,
  ),
  54 => 
  array (
    'id' => 55,
    'odoo_code_id' => 'base.hr',
    'name' => 'Croacia',
    'nationality' => 'Croata',
    'code' => 'hr',
    'phone_code' => '+385',
    'currency_code' => 'EUR',
    'latitude' => 45.16666666,
    'longitude' => 15.5,
    'is_active' => true,
  ),
  55 => 
  array (
    'id' => 56,
    'odoo_code_id' => 'base.ht',
    'name' => 'Haití',
    'nationality' => 'Haitiana',
    'code' => 'ht',
    'phone_code' => '+509',
    'currency_code' => 'HTG',
    'latitude' => 19.0,
    'longitude' => -72.41666666,
    'is_active' => true,
  ),
  56 => 
  array (
    'id' => 57,
    'odoo_code_id' => 'base.hu',
    'name' => 'Hungría',
    'nationality' => 'Hungara',
    'code' => 'hu',
    'phone_code' => '+36',
    'currency_code' => 'HUF',
    'latitude' => 47.0,
    'longitude' => 20.0,
    'is_active' => true,
  ),
  57 => 
  array (
    'id' => 58,
    'odoo_code_id' => 'base.id',
    'name' => 'Indonesia',
    'nationality' => 'Indonesia',
    'code' => 'id',
    'phone_code' => '+62',
    'currency_code' => 'IDR',
    'latitude' => -5.0,
    'longitude' => 120.0,
    'is_active' => true,
  ),
  58 => 
  array (
    'id' => 59,
    'odoo_code_id' => 'base.ie',
    'name' => 'Irlanda',
    'nationality' => 'Irlandesa',
    'code' => 'ie',
    'phone_code' => '+353',
    'currency_code' => 'EUR',
    'latitude' => 53.0,
    'longitude' => -8.0,
    'is_active' => true,
  ),
  59 => 
  array (
    'id' => 60,
    'odoo_code_id' => 'base.il',
    'name' => 'Israel',
    'nationality' => 'Israelí',
    'code' => 'il',
    'phone_code' => '+972',
    'currency_code' => 'ILS',
    'latitude' => 31.47,
    'longitude' => 35.13,
    'is_active' => true,
  ),
  60 => 
  array (
    'id' => 61,
    'odoo_code_id' => 'base.in',
    'name' => 'India',
    'nationality' => 'Indu',
    'code' => 'in',
    'phone_code' => '+91',
    'currency_code' => 'INR',
    'latitude' => 20.0,
    'longitude' => 77.0,
    'is_active' => true,
  ),
  61 => 
  array (
    'id' => 62,
    'odoo_code_id' => 'base.iq',
    'name' => 'Irak',
    'nationality' => 'Iraquí',
    'code' => 'iq',
    'phone_code' => '+964',
    'currency_code' => 'IQD',
    'latitude' => 33.0,
    'longitude' => 44.0,
    'is_active' => true,
  ),
  62 => 
  array (
    'id' => 63,
    'odoo_code_id' => 'base.ir',
    'name' => 'Irán',
    'nationality' => 'Irani',
    'code' => 'ir',
    'phone_code' => '+98',
    'currency_code' => 'IRR',
    'latitude' => 32.0,
    'longitude' => 53.0,
    'is_active' => true,
  ),
  63 => 
  array (
    'id' => 64,
    'odoo_code_id' => 'base.is',
    'name' => 'Islandia',
    'nationality' => 'Islandesa',
    'code' => 'is',
    'phone_code' => '+354',
    'currency_code' => 'ISK',
    'latitude' => 65.0,
    'longitude' => -18.0,
    'is_active' => true,
  ),
  64 => 
  array (
    'id' => 65,
    'odoo_code_id' => 'base.it',
    'name' => 'Italia',
    'nationality' => 'Italiana',
    'code' => 'it',
    'phone_code' => '+39',
    'currency_code' => 'EUR',
    'latitude' => 42.83333333,
    'longitude' => 12.83333333,
    'is_active' => true,
  ),
  65 => 
  array (
    'id' => 66,
    'odoo_code_id' => 'base.jm',
    'name' => 'Jamaica',
    'nationality' => 'Jamaiquina',
    'code' => 'jm',
    'phone_code' => '+1876',
    'currency_code' => 'JMD',
    'latitude' => 18.25,
    'longitude' => -77.5,
    'is_active' => true,
  ),
  66 => 
  array (
    'id' => 67,
    'odoo_code_id' => 'base.jo',
    'name' => 'Jordania',
    'nationality' => 'Jordana',
    'code' => 'jo',
    'phone_code' => '+962',
    'currency_code' => 'JOD',
    'latitude' => 31.0,
    'longitude' => 36.0,
    'is_active' => true,
  ),
  67 => 
  array (
    'id' => 68,
    'odoo_code_id' => 'base.jp',
    'name' => 'Japón',
    'nationality' => 'Japonesa',
    'code' => 'jp',
    'phone_code' => '+81',
    'currency_code' => 'JPY',
    'latitude' => 36.0,
    'longitude' => 138.0,
    'is_active' => true,
  ),
  68 => 
  array (
    'id' => 69,
    'odoo_code_id' => 'base.kg',
    'name' => 'Kirguistán',
    'nationality' => 'Kirguis',
    'code' => 'kg',
    'phone_code' => '+996',
    'currency_code' => 'KGS',
    'latitude' => 41.0,
    'longitude' => 75.0,
    'is_active' => true,
  ),
  69 => 
  array (
    'id' => 70,
    'odoo_code_id' => 'base.kh',
    'name' => 'Camboya',
    'nationality' => 'Camboyana',
    'code' => 'kh',
    'phone_code' => '+855',
    'currency_code' => 'KHR',
    'latitude' => 13.0,
    'longitude' => 105.0,
    'is_active' => true,
  ),
  70 => 
  array (
    'id' => 71,
    'odoo_code_id' => 'base.kn',
    'name' => 'San Cristóbal y Nieves',
    'nationality' => 'San Cristobaleña',
    'code' => 'kn',
    'phone_code' => '+1869',
    'currency_code' => 'XCD',
    'latitude' => 17.33333333,
    'longitude' => -62.75,
    'is_active' => true,
  ),
  71 => 
  array (
    'id' => 72,
    'odoo_code_id' => 'base.kp',
    'name' => 'Corea del Norte',
    'nationality' => 'Norcoreana',
    'code' => 'kp',
    'phone_code' => '+850',
    'currency_code' => 'KPW',
    'latitude' => 40.0,
    'longitude' => 127.0,
    'is_active' => true,
  ),
  72 => 
  array (
    'id' => 73,
    'odoo_code_id' => 'base.kr',
    'name' => 'Corea del Sur',
    'nationality' => 'Surcoreana',
    'code' => 'kr',
    'phone_code' => '+82',
    'currency_code' => 'KRW',
    'latitude' => 37.0,
    'longitude' => 127.5,
    'is_active' => true,
  ),
  73 => 
  array (
    'id' => 74,
    'odoo_code_id' => 'base.kw',
    'name' => 'Kuwait',
    'nationality' => 'Kuwaiti',
    'code' => 'kw',
    'phone_code' => '+965',
    'currency_code' => 'KWD',
    'latitude' => 29.5,
    'longitude' => 45.75,
    'is_active' => true,
  ),
  74 => 
  array (
    'id' => 75,
    'odoo_code_id' => 'base.ky',
    'name' => 'Islas Caimán',
    'nationality' => 'Caimanensa',
    'code' => 'ky',
    'phone_code' => '+1345',
    'currency_code' => 'KYD',
    'latitude' => 19.3133,
    'longitude' => -81.2546,
    'is_active' => true,
  ),
  75 => 
  array (
    'id' => 76,
    'odoo_code_id' => 'base.kz',
    'name' => 'Kazajistán',
    'nationality' => 'Kazaja',
    'code' => 'kz',
    'phone_code' => '+76',
    'currency_code' => 'KZT',
    'latitude' => 48.0196,
    'longitude' => 66.9237,
    'is_active' => true,
  ),
  76 => 
  array (
    'id' => 77,
    'odoo_code_id' => 'base.la',
    'name' => 'Laos',
    'nationality' => 'Laosiana',
    'code' => 'la',
    'phone_code' => '+856',
    'currency_code' => 'LAK',
    'latitude' => 18.0,
    'longitude' => 105.0,
    'is_active' => true,
  ),
  77 => 
  array (
    'id' => 78,
    'odoo_code_id' => 'base.lb',
    'name' => 'Líbano',
    'nationality' => 'Libanesa',
    'code' => 'lb',
    'phone_code' => '+961',
    'currency_code' => 'LBP',
    'latitude' => 33.83333333,
    'longitude' => 35.83333333,
    'is_active' => true,
  ),
  78 => 
  array (
    'id' => 79,
    'odoo_code_id' => 'base.lc',
    'name' => 'Santa Lucía',
    'nationality' => 'Santalucense',
    'code' => 'lc',
    'phone_code' => '+1758',
    'currency_code' => 'XCD',
    'latitude' => 13.88333333,
    'longitude' => -60.96666666,
    'is_active' => true,
  ),
  79 => 
  array (
    'id' => 80,
    'odoo_code_id' => 'base.lk',
    'name' => 'Sri Lanka',
    'nationality' => 'Ceilandesa',
    'code' => 'lk',
    'phone_code' => '+94',
    'currency_code' => 'LKR',
    'latitude' => 7.0,
    'longitude' => 81.0,
    'is_active' => true,
  ),
  80 => 
  array (
    'id' => 81,
    'odoo_code_id' => 'base.mm',
    'name' => 'Birmania (Myanmar)',
    'nationality' => 'Birmana',
    'code' => 'mm',
    'phone_code' => '+95',
    'currency_code' => 'MMK',
    'latitude' => 22.0,
    'longitude' => 98.0,
    'is_active' => true,
  ),
  81 => 
  array (
    'id' => 82,
    'odoo_code_id' => 'base.mn',
    'name' => 'Mongolia',
    'nationality' => 'Mongola',
    'code' => 'mn',
    'phone_code' => '+976',
    'currency_code' => 'MNT',
    'latitude' => 46.0,
    'longitude' => 105.0,
    'is_active' => true,
  ),
  82 => 
  array (
    'id' => 83,
    'odoo_code_id' => 'base.mo',
    'name' => 'Macao',
    'nationality' => 'Macaense',
    'code' => 'mo',
    'phone_code' => '+853',
    'currency_code' => 'MOP',
    'latitude' => 22.16666666,
    'longitude' => 113.55,
    'is_active' => true,
  ),
  83 => 
  array (
    'id' => 84,
    'odoo_code_id' => 'base.ms',
    'name' => 'Montserrat',
    'nationality' => 'Montserratense',
    'code' => 'ms',
    'phone_code' => '+1664',
    'currency_code' => 'XCD',
    'latitude' => 16.75,
    'longitude' => -62.2,
    'is_active' => true,
  ),
  84 => 
  array (
    'id' => 85,
    'odoo_code_id' => 'base.mv',
    'name' => 'Maldivas',
    'nationality' => 'Maldiva',
    'code' => 'mv',
    'phone_code' => '+960',
    'currency_code' => 'MVR',
    'latitude' => 3.25,
    'longitude' => 73.0,
    'is_active' => true,
  ),
  85 => 
  array (
    'id' => 86,
    'odoo_code_id' => 'base.mx',
    'name' => 'México',
    'nationality' => 'Mexicana',
    'code' => 'mx',
    'phone_code' => '+52',
    'currency_code' => 'MXN',
    'latitude' => 23.0,
    'longitude' => -102.0,
    'is_active' => true,
  ),
  86 => 
  array (
    'id' => 87,
    'odoo_code_id' => 'base.my',
    'name' => 'Malasia',
    'nationality' => 'Malasia',
    'code' => 'my',
    'phone_code' => '+60',
    'currency_code' => 'MYR',
    'latitude' => 2.5,
    'longitude' => 112.5,
    'is_active' => true,
  ),
  87 => 
  array (
    'id' => 88,
    'odoo_code_id' => 'base.ni',
    'name' => 'Nicaragua',
    'nationality' => 'Nicaraguense',
    'code' => 'ni',
    'phone_code' => '+505',
    'currency_code' => 'NIO',
    'latitude' => 13.0,
    'longitude' => -85.0,
    'is_active' => true,
  ),
  88 => 
  array (
    'id' => 89,
    'odoo_code_id' => 'base.nl',
    'name' => 'Países Bajos',
    'nationality' => 'Neerlandesa',
    'code' => 'nl',
    'phone_code' => '+31',
    'currency_code' => 'EUR',
    'latitude' => 52.5,
    'longitude' => 5.75,
    'is_active' => true,
  ),
  89 => 
  array (
    'id' => 90,
    'odoo_code_id' => 'base.np',
    'name' => 'Nepal',
    'nationality' => 'Nepalí',
    'code' => 'np',
    'phone_code' => '+977',
    'currency_code' => 'NPR',
    'latitude' => 28.0,
    'longitude' => 84.0,
    'is_active' => true,
  ),
  90 => 
  array (
    'id' => 91,
    'odoo_code_id' => 'base.om',
    'name' => 'Omán',
    'nationality' => 'Omani',
    'code' => 'om',
    'phone_code' => '+968',
    'currency_code' => 'OMR',
    'latitude' => 21.0,
    'longitude' => 57.0,
    'is_active' => true,
  ),
  91 => 
  array (
    'id' => 92,
    'odoo_code_id' => 'base.pa',
    'name' => 'Panamá',
    'nationality' => 'Panameña',
    'code' => 'pa',
    'phone_code' => '+507',
    'currency_code' => 'PAB',
    'latitude' => 9.0,
    'longitude' => -80.0,
    'is_active' => true,
  ),
  92 => 
  array (
    'id' => 93,
    'odoo_code_id' => 'base.pe',
    'name' => 'Perú',
    'nationality' => 'Peruana',
    'code' => 'pe',
    'phone_code' => '+51',
    'currency_code' => 'PEN',
    'latitude' => -10.0,
    'longitude' => -76.0,
    'is_active' => true,
  ),
  93 => 
  array (
    'id' => 94,
    'odoo_code_id' => 'base.ph',
    'name' => 'Filipinas',
    'nationality' => 'Filipina',
    'code' => 'ph',
    'phone_code' => '+63',
    'currency_code' => 'PHP',
    'latitude' => 13.0,
    'longitude' => 122.0,
    'is_active' => true,
  ),
  94 => 
  array (
    'id' => 95,
    'odoo_code_id' => 'base.pk',
    'name' => 'Pakistán',
    'nationality' => 'Pakistani',
    'code' => 'pk',
    'phone_code' => '+92',
    'currency_code' => 'PKR',
    'latitude' => 30.0,
    'longitude' => 70.0,
    'is_active' => true,
  ),
  95 => 
  array (
    'id' => 96,
    'odoo_code_id' => 'base.pl',
    'name' => 'Polonia',
    'nationality' => 'Polaca',
    'code' => 'pl',
    'phone_code' => '+48',
    'currency_code' => 'PLN',
    'latitude' => 52.0,
    'longitude' => 20.0,
    'is_active' => true,
  ),
  96 => 
  array (
    'id' => 97,
    'odoo_code_id' => 'base.pm',
    'name' => 'San Pedro y Miquelón',
    'nationality' => 'Sanpedrina',
    'code' => 'pm',
    'phone_code' => '+508',
    'currency_code' => 'EUR',
    'latitude' => 46.83333333,
    'longitude' => -56.33333333,
    'is_active' => true,
  ),
  97 => 
  array (
    'id' => 98,
    'odoo_code_id' => 'base.pr',
    'name' => 'Puerto Rico',
    'nationality' => 'Puertorriqueña',
    'code' => 'pr',
    'phone_code' => '+1787',
    'currency_code' => 'USD',
    'latitude' => 18.25,
    'longitude' => -66.5,
    'is_active' => true,
  ),
  98 => 
  array (
    'id' => 99,
    'odoo_code_id' => 'base.ps',
    'name' => 'Palestina',
    'nationality' => 'Palestina',
    'code' => 'ps',
    'phone_code' => '+970',
    'currency_code' => 'EGP',
    'latitude' => 31.9,
    'longitude' => 35.2,
    'is_active' => true,
  ),
  99 => 
  array (
    'id' => 100,
    'odoo_code_id' => 'base.pt',
    'name' => 'Portugal',
    'nationality' => 'Portuguesa',
    'code' => 'pt',
    'phone_code' => '+351',
    'currency_code' => 'EUR',
    'latitude' => 39.5,
    'longitude' => -8.0,
    'is_active' => true,
  ),
  100 => 
  array (
    'id' => 101,
    'odoo_code_id' => 'base.py',
    'name' => 'Paraguay',
    'nationality' => 'Paraguaya',
    'code' => 'py',
    'phone_code' => '+595',
    'currency_code' => 'PYG',
    'latitude' => -23.0,
    'longitude' => -58.0,
    'is_active' => true,
  ),
  101 => 
  array (
    'id' => 102,
    'odoo_code_id' => 'base.qa',
    'name' => 'Catar',
    'nationality' => 'Qatarí',
    'code' => 'qa',
    'phone_code' => '+974',
    'currency_code' => 'QAR',
    'latitude' => 25.5,
    'longitude' => 51.25,
    'is_active' => true,
  ),
  102 => 
  array (
    'id' => 103,
    'odoo_code_id' => 'base.ru',
    'name' => 'Rusia',
    'nationality' => 'Rusa',
    'code' => 'ru',
    'phone_code' => '+73',
    'currency_code' => 'RUB',
    'latitude' => 60.0,
    'longitude' => 100.0,
    'is_active' => true,
  ),
  103 => 
  array (
    'id' => 104,
    'odoo_code_id' => 'base.sa',
    'name' => 'Arabia Saudita',
    'nationality' => 'Saudí',
    'code' => 'sa',
    'phone_code' => '+966',
    'currency_code' => 'SAR',
    'latitude' => 25.0,
    'longitude' => 45.0,
    'is_active' => true,
  ),
  104 => 
  array (
    'id' => 105,
    'odoo_code_id' => 'base.se',
    'name' => 'Suecia',
    'nationality' => 'Sueca',
    'code' => 'se',
    'phone_code' => '+46',
    'currency_code' => 'SEK',
    'latitude' => 62.0,
    'longitude' => 15.0,
    'is_active' => true,
  ),
  105 => 
  array (
    'id' => 106,
    'odoo_code_id' => 'base.sg',
    'name' => 'Singapur',
    'nationality' => 'Singapurense',
    'code' => 'sg',
    'phone_code' => '+65',
    'currency_code' => 'SGD',
    'latitude' => 1.36666666,
    'longitude' => 103.8,
    'is_active' => true,
  ),
  106 => 
  array (
    'id' => 107,
    'odoo_code_id' => 'base.sh',
    'name' => 'Santa Elena',
    'nationality' => 'Santaelenense',
    'code' => 'sh',
    'phone_code' => '+290',
    'currency_code' => 'GBP',
    'latitude' => -15.95,
    'longitude' => -5.72,
    'is_active' => true,
  ),
  107 => 
  array (
    'id' => 108,
    'odoo_code_id' => 'base.si',
    'name' => 'Eslovenia',
    'nationality' => 'Eslovena',
    'code' => 'si',
    'phone_code' => '+386',
    'currency_code' => 'EUR',
    'latitude' => 46.11666666,
    'longitude' => 14.81666666,
    'is_active' => true,
  ),
  108 => 
  array (
    'id' => 109,
    'odoo_code_id' => 'base.sk',
    'name' => 'Eslovaquia',
    'nationality' => 'Eslovaca',
    'code' => 'sk',
    'phone_code' => '+421',
    'currency_code' => 'EUR',
    'latitude' => 48.66666666,
    'longitude' => 19.5,
    'is_active' => true,
  ),
  109 => 
  array (
    'id' => 110,
    'odoo_code_id' => 'base.sr',
    'name' => 'Surinam',
    'nationality' => 'Surinamesa',
    'code' => 'sr',
    'phone_code' => '+597',
    'currency_code' => 'SRD',
    'latitude' => 4.0,
    'longitude' => -56.0,
    'is_active' => true,
  ),
  110 => 
  array (
    'id' => 111,
    'odoo_code_id' => 'base.sv',
    'name' => 'El Salvador',
    'nationality' => 'Salvadoreña',
    'code' => 'sv',
    'phone_code' => '+503',
    'currency_code' => 'USD',
    'latitude' => 13.83333333,
    'longitude' => -88.91666666,
    'is_active' => true,
  ),
  111 => 
  array (
    'id' => 112,
    'odoo_code_id' => 'base.sx',
    'name' => 'Sint Maarten',
    'nationality' => 'Sanmantinense',
    'code' => 'sx',
    'phone_code' => '+1721',
    'currency_code' => 'ANG',
    'latitude' => 18.033333,
    'longitude' => -63.05,
    'is_active' => true,
  ),
  112 => 
  array (
    'id' => 113,
    'odoo_code_id' => 'base.sy',
    'name' => 'Siria',
    'nationality' => 'Siria',
    'code' => 'sy',
    'phone_code' => '+963',
    'currency_code' => 'SYP',
    'latitude' => 35.0,
    'longitude' => 38.0,
    'is_active' => true,
  ),
  113 => 
  array (
    'id' => 114,
    'odoo_code_id' => 'base.tc',
    'name' => 'Islas Turcas y Caicos',
    'nationality' => 'Turcocaiqueña',
    'code' => 'tc',
    'phone_code' => '+1649',
    'currency_code' => 'USD',
    'latitude' => 21.75,
    'longitude' => -71.58333333,
    'is_active' => true,
  ),
  114 => 
  array (
    'id' => 115,
    'odoo_code_id' => 'base.th',
    'name' => 'Tailandia',
    'nationality' => 'Tailandesa',
    'code' => 'th',
    'phone_code' => '+66',
    'currency_code' => 'THB',
    'latitude' => 15.0,
    'longitude' => 100.0,
    'is_active' => true,
  ),
  115 => 
  array (
    'id' => 116,
    'odoo_code_id' => 'base.tj',
    'name' => 'Tayikistán',
    'nationality' => 'Tayica',
    'code' => 'tj',
    'phone_code' => '+992',
    'currency_code' => 'TJS',
    'latitude' => 39.0,
    'longitude' => 71.0,
    'is_active' => true,
  ),
  116 => 
  array (
    'id' => 117,
    'odoo_code_id' => 'base.tm',
    'name' => 'Turkmenistán',
    'nationality' => 'Turcomana',
    'code' => 'tm',
    'phone_code' => '+993',
    'currency_code' => 'TMT',
    'latitude' => 40.0,
    'longitude' => 60.0,
    'is_active' => true,
  ),
  117 => 
  array (
    'id' => 118,
    'odoo_code_id' => 'base.tr',
    'name' => 'Turquía',
    'nationality' => 'Turca',
    'code' => 'tr',
    'phone_code' => '+90',
    'currency_code' => 'TRY',
    'latitude' => 39.0,
    'longitude' => 35.0,
    'is_active' => true,
  ),
  118 => 
  array (
    'id' => 119,
    'odoo_code_id' => 'base.tt',
    'name' => 'Trinidad y Tobago',
    'nationality' => 'Trinitense',
    'code' => 'tt',
    'phone_code' => '+1868',
    'currency_code' => 'TTD',
    'latitude' => 10.6918,
    'longitude' => -61.2225,
    'is_active' => true,
  ),
  119 => 
  array (
    'id' => 120,
    'odoo_code_id' => 'base.tw',
    'name' => 'Taiwán',
    'nationality' => 'Taiwanesa',
    'code' => 'tw',
    'phone_code' => '+886',
    'currency_code' => 'TWD',
    'latitude' => 23.5,
    'longitude' => 121.0,
    'is_active' => true,
  ),
  120 => 
  array (
    'id' => 121,
    'odoo_code_id' => 'base.ua',
    'name' => 'Ucrania',
    'nationality' => 'Ucraniana',
    'code' => 'ua',
    'phone_code' => '+380',
    'currency_code' => 'UAH',
    'latitude' => 49.0,
    'longitude' => 32.0,
    'is_active' => true,
  ),
  121 => 
  array (
    'id' => 122,
    'odoo_code_id' => 'base.uk',
    'name' => 'Reino Unido',
    'nationality' => 'Britanica',
    'code' => 'uk',
    'phone_code' => '+44',
    'currency_code' => 'GBP',
    'latitude' => 54.0,
    'longitude' => -2.0,
    'is_active' => true,
  ),
  122 => 
  array (
    'id' => 123,
    'odoo_code_id' => 'base.us',
    'name' => 'Estados Unidos',
    'nationality' => 'Estadounidense',
    'code' => 'us',
    'phone_code' => '+1201',
    'currency_code' => 'USD',
    'latitude' => 38.0,
    'longitude' => -97.0,
    'is_active' => true,
  ),
  123 => 
  array (
    'id' => 124,
    'odoo_code_id' => 'base.uy',
    'name' => 'Uruguay',
    'nationality' => 'Uruguaya',
    'code' => 'uy',
    'phone_code' => '+598',
    'currency_code' => 'UYU',
    'latitude' => -33.0,
    'longitude' => -56.0,
    'is_active' => true,
  ),
  124 => 
  array (
    'id' => 125,
    'odoo_code_id' => 'base.uz',
    'name' => 'Uzbekistán',
    'nationality' => 'Uzbeka',
    'code' => 'uz',
    'phone_code' => '+998',
    'currency_code' => 'UZS',
    'latitude' => 41.0,
    'longitude' => 64.0,
    'is_active' => true,
  ),
  125 => 
  array (
    'id' => 126,
    'odoo_code_id' => 'base.va',
    'name' => 'Ciudad del Vaticano',
    'nationality' => 'Vaticana',
    'code' => 'va',
    'phone_code' => '+3906698',
    'currency_code' => 'EUR',
    'latitude' => 41.9,
    'longitude' => 12.45,
    'is_active' => true,
  ),
  126 => 
  array (
    'id' => 127,
    'odoo_code_id' => 'base.vc',
    'name' => 'San Vicente y las Granadinas',
    'nationality' => 'Sanvicentina',
    'code' => 'vc',
    'phone_code' => '+1784',
    'currency_code' => 'XCD',
    'latitude' => 13.25,
    'longitude' => -61.2,
    'is_active' => true,
  ),
  127 => 
  array (
    'id' => 128,
    'odoo_code_id' => 'base.ve',
    'name' => 'Venezuela',
    'nationality' => 'Venezolana',
    'code' => 've',
    'phone_code' => '+58',
    'currency_code' => 'VES',
    'latitude' => 8.0,
    'longitude' => -66.0,
    'is_active' => true,
  ),
  128 => 
  array (
    'id' => 129,
    'odoo_code_id' => 'base.vg',
    'name' => 'Islas Vírgenes Británicas',
    'nationality' => 'Virgenesa',
    'code' => 'vg',
    'phone_code' => '+1284',
    'currency_code' => 'USD',
    'latitude' => 18.431383,
    'longitude' => -64.62305,
    'is_active' => true,
  ),
  129 => 
  array (
    'id' => 130,
    'odoo_code_id' => 'base.vi',
    'name' => 'Islas Vírgenes de los EE. UU.',
    'nationality' => 'Virgenesa',
    'code' => 'vi',
    'phone_code' => '+1340',
    'currency_code' => 'USD',
    'latitude' => 18.35,
    'longitude' => -64.933333,
    'is_active' => true,
  ),
  130 => 
  array (
    'id' => 131,
    'odoo_code_id' => 'base.vn',
    'name' => 'Vietnam',
    'nationality' => 'Vietnamita',
    'code' => 'vn',
    'phone_code' => '+84',
    'currency_code' => 'VND',
    'latitude' => 16.16666666,
    'longitude' => 107.83333333,
    'is_active' => true,
  ),
  131 => 
  array (
    'id' => 132,
    'odoo_code_id' => 'base.ye',
    'name' => 'Yemen',
    'nationality' => 'Yemeni',
    'code' => 'ye',
    'phone_code' => '+967',
    'currency_code' => 'YER',
    'latitude' => 15.0,
    'longitude' => 48.0,
    'is_active' => true,
  ),
);
