<?php

use Illuminate\Database\Seeder;

class OdooCountySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->insert(['odoo_state_id' => 1670,'odoo_municipality_id' => 29, 'odoo_mun_code' => '307','name' => 'Autónomo Alto Orinoco' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1670,'odoo_municipality_id' => 24, 'odoo_mun_code' => '302','name' => 'Autónomo Atabapo' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1670,'odoo_municipality_id' => 23, 'odoo_mun_code' => '301','name' => 'Autónomo Atures' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1670,'odoo_municipality_id' => 27, 'odoo_mun_code' => '305','name' => 'Autónomo Autana' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1670,'odoo_municipality_id' => 25, 'odoo_mun_code' => '303','name' => 'Autónomo Guainía' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1670,'odoo_municipality_id' => 28, 'odoo_mun_code' => '306','name' => 'Autónomo Manapiare' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1670,'odoo_municipality_id' => 26, 'odoo_mun_code' => '304','name' => 'Autónomo Río Negro' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1671,'odoo_municipality_id' => 30, 'odoo_mun_code' => '401','name' => 'Achaguas' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1671,'odoo_municipality_id' => 36, 'odoo_mun_code' => '407','name' => 'Biruaca' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1671,'odoo_municipality_id' => 31, 'odoo_mun_code' => '402','name' => 'Muñoz' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1671,'odoo_municipality_id' => 33, 'odoo_mun_code' => '404','name' => 'Pedro Camejo' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1671,'odoo_municipality_id' => 32, 'odoo_mun_code' => '403','name' => 'Páez' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1671,'odoo_municipality_id' => 34, 'odoo_mun_code' => '405','name' => 'Rómulo Gallegos' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1671,'odoo_municipality_id' => 35, 'odoo_mun_code' => '406','name' => 'San Fernando' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1672,'odoo_municipality_id' => 37, 'odoo_mun_code' => '501','name' => 'Atanasio Girardot' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1672,'odoo_municipality_id' => 47, 'odoo_mun_code' => '511','name' => 'Bolívar' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1672,'odoo_municipality_id' => 51, 'odoo_mun_code' => '515','name' => 'Camatagua' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1672,'odoo_municipality_id' => 53, 'odoo_mun_code' => '517','name' => 'Francisco Linares Alcántara' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1672,'odoo_municipality_id' => 46, 'odoo_mun_code' => '510','name' => 'José Angel Lamas' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1672,'odoo_municipality_id' => 39, 'odoo_mun_code' => '503','name' => 'José Félix Ribas' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1672,'odoo_municipality_id' => 52, 'odoo_mun_code' => '516','name' => 'José Rafael Revenga' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1672,'odoo_municipality_id' => 45, 'odoo_mun_code' => '509','name' => 'Libertador' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1672,'odoo_municipality_id' => 49, 'odoo_mun_code' => '513','name' => 'Mario Briceño Iragorry' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1672,'odoo_municipality_id' => 54, 'odoo_mun_code' => '518','name' => 'Ocumare De La Costa De Oro' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1672,'odoo_municipality_id' => 40, 'odoo_mun_code' => '504','name' => 'San Casimiro' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1672,'odoo_municipality_id' => 41, 'odoo_mun_code' => '505','name' => 'San Sebastián' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1672,'odoo_municipality_id' => 38, 'odoo_mun_code' => '502','name' => 'Santiago Mariño' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1672,'odoo_municipality_id' => 48, 'odoo_mun_code' => '512','name' => 'Santos Michelena' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1672,'odoo_municipality_id' => 42, 'odoo_mun_code' => '506','name' => 'Sucre' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1672,'odoo_municipality_id' => 50, 'odoo_mun_code' => '514','name' => 'Tovar' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1672,'odoo_municipality_id' => 43, 'odoo_mun_code' => '507','name' => 'Urdaneta' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1672,'odoo_municipality_id' => 44, 'odoo_mun_code' => '508','name' => 'Zamora' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1669,'odoo_municipality_id' => 2, 'odoo_mun_code' => '201','name' => 'Anaco' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1669,'odoo_municipality_id' => 3, 'odoo_mun_code' => '202','name' => 'Aragua' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1669,'odoo_municipality_id' => 18, 'odoo_mun_code' => '217','name' => 'Diego Bautista Urbaneja' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1669,'odoo_municipality_id' => 12, 'odoo_mun_code' => '211','name' => 'Fernando De Peñalver' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1669,'odoo_municipality_id' => 10, 'odoo_mun_code' => '209','name' => 'Francisco De Miranda' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1669,'odoo_municipality_id' => 19, 'odoo_mun_code' => '218','name' => 'Francisco Del Carmen Carvajal' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1669,'odoo_municipality_id' => 16, 'odoo_mun_code' => '215','name' => 'Guanta' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1669,'odoo_municipality_id' => 8, 'odoo_mun_code' => '207','name' => 'Independencia' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1669,'odoo_municipality_id' => 11, 'odoo_mun_code' => '210','name' => 'José Gregorio Monagas' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1669,'odoo_municipality_id' => 14, 'odoo_mun_code' => '213','name' => 'Juan Antonio Sotillo' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1669,'odoo_municipality_id' => 6, 'odoo_mun_code' => '205','name' => 'Juan Manuel Cajigal' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1669,'odoo_municipality_id' => 9, 'odoo_mun_code' => '208','name' => 'Libertad' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1669,'odoo_municipality_id' => 5, 'odoo_mun_code' => '204','name' => 'Manuel Ezequiel Bruzual' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1669,'odoo_municipality_id' => 7, 'odoo_mun_code' => '206','name' => 'Pedro María Freites' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1669,'odoo_municipality_id' => 17, 'odoo_mun_code' => '216','name' => 'Píritu' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1669,'odoo_municipality_id' => 15, 'odoo_mun_code' => '214','name' => 'San José De Guanipa' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1669,'odoo_municipality_id' => 22, 'odoo_mun_code' => '221','name' => 'San Juan De Capistrano' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1669,'odoo_municipality_id' => 20, 'odoo_mun_code' => '219','name' => 'Santa  Ana' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1669,'odoo_municipality_id' => 4, 'odoo_mun_code' => '203','name' => 'Simón Bolívar' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1669,'odoo_municipality_id' => 13, 'odoo_mun_code' => '212','name' => 'Simón Rodríguez' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1669,'odoo_municipality_id' => 21, 'odoo_mun_code' => '220','name' => 'Sir Arthur Mc Gregor' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1673,'odoo_municipality_id' => 63, 'odoo_mun_code' => '609','name' => 'Alberto Arvelo Torrealba' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1673,'odoo_municipality_id' => 66, 'odoo_mun_code' => '612','name' => 'Andrés Eloy Blanco' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1673,'odoo_municipality_id' => 64, 'odoo_mun_code' => '610','name' => 'Antonio José De Sucre' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1673,'odoo_municipality_id' => 55, 'odoo_mun_code' => '601','name' => 'Arismendi' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1673,'odoo_municipality_id' => 56, 'odoo_mun_code' => '602','name' => 'Barinas' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1673,'odoo_municipality_id' => 57, 'odoo_mun_code' => '603','name' => 'Bolívar' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1673,'odoo_municipality_id' => 65, 'odoo_mun_code' => '611','name' => 'Cruz Paredes' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1673,'odoo_municipality_id' => 58, 'odoo_mun_code' => '604','name' => 'Ezequiel Zamora' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1673,'odoo_municipality_id' => 59, 'odoo_mun_code' => '605','name' => 'Obispos' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1673,'odoo_municipality_id' => 60, 'odoo_mun_code' => '606','name' => 'Pedraza' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1673,'odoo_municipality_id' => 61, 'odoo_mun_code' => '607','name' => 'Rojas' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1673,'odoo_municipality_id' => 62, 'odoo_mun_code' => '608','name' => 'Sosa' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1674,'odoo_municipality_id' => 74, 'odoo_mun_code' => '708','name' => 'Angostura' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1674,'odoo_municipality_id' => 67, 'odoo_mun_code' => '701','name' => 'Caroní' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1674,'odoo_municipality_id' => 68, 'odoo_mun_code' => '702','name' => 'Cedeño' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1674,'odoo_municipality_id' => 76, 'odoo_mun_code' => '710','name' => 'El Callao' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1674,'odoo_municipality_id' => 75, 'odoo_mun_code' => '709','name' => 'Gran Sabana' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1674,'odoo_municipality_id' => 69, 'odoo_mun_code' => '703','name' => 'Heres' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1674,'odoo_municipality_id' => 77, 'odoo_mun_code' => '711','name' => 'Padre Pedro Chien' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1674,'odoo_municipality_id' => 70, 'odoo_mun_code' => '704','name' => 'Piar' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1674,'odoo_municipality_id' => 71, 'odoo_mun_code' => '705','name' => 'Roscio' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1674,'odoo_municipality_id' => 73, 'odoo_mun_code' => '707','name' => 'Sifontes' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1674,'odoo_municipality_id' => 72, 'odoo_mun_code' => '706','name' => 'Sucre' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1675,'odoo_municipality_id' => 78, 'odoo_mun_code' => '801','name' => 'Bejuma' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1675,'odoo_municipality_id' => 79, 'odoo_mun_code' => '802','name' => 'Carlos Arvelo' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1675,'odoo_municipality_id' => 80, 'odoo_mun_code' => '803','name' => 'Diego Ibarra' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1675,'odoo_municipality_id' => 81, 'odoo_mun_code' => '804','name' => 'Guacara' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1675,'odoo_municipality_id' => 83, 'odoo_mun_code' => '806','name' => 'Juan José Mora' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1675,'odoo_municipality_id' => 91, 'odoo_mun_code' => '814','name' => 'Libertador' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1675,'odoo_municipality_id' => 88, 'odoo_mun_code' => '811','name' => 'Los Guayos' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1675,'odoo_municipality_id' => 87, 'odoo_mun_code' => '810','name' => 'Miranda' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1675,'odoo_municipality_id' => 82, 'odoo_mun_code' => '805','name' => 'Montalbán' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1675,'odoo_municipality_id' => 89, 'odoo_mun_code' => '812','name' => 'Naguanagua' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1675,'odoo_municipality_id' => 84, 'odoo_mun_code' => '807','name' => 'Puerto Cabello' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1675,'odoo_municipality_id' => 90, 'odoo_mun_code' => '813','name' => 'San Diego' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1675,'odoo_municipality_id' => 85, 'odoo_mun_code' => '808','name' => 'San Joaquín' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1675,'odoo_municipality_id' => 86, 'odoo_mun_code' => '809','name' => 'Valencia' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1676,'odoo_municipality_id' => 92, 'odoo_mun_code' => '901','name' => 'Anzoátegui' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1676,'odoo_municipality_id' => 93, 'odoo_mun_code' => '902','name' => 'Falcón' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1676,'odoo_municipality_id' => 94, 'odoo_mun_code' => '903','name' => 'Girardot' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1676,'odoo_municipality_id' => 99, 'odoo_mun_code' => '908','name' => 'Lima Blanco' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1676,'odoo_municipality_id' => 95, 'odoo_mun_code' => '904','name' => 'Pao De San Juan Bautista' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1676,'odoo_municipality_id' => 96, 'odoo_mun_code' => '905','name' => 'Ricaurte' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1676,'odoo_municipality_id' => 100, 'odoo_mun_code' => '909','name' => 'Rómulo Gallegos' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1676,'odoo_municipality_id' => 97, 'odoo_mun_code' => '906','name' => 'San Carlos' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1676,'odoo_municipality_id' => 98, 'odoo_mun_code' => '907','name' => 'Tinaco' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1690,'odoo_municipality_id' => 333, 'odoo_mun_code' => '2303','name' => 'Antonio Díaz' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1690,'odoo_municipality_id' => 334, 'odoo_mun_code' => '2304','name' => 'Casacoima' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1690,'odoo_municipality_id' => 332, 'odoo_mun_code' => '2302','name' => 'Pedernales' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1690,'odoo_municipality_id' => 331, 'odoo_mun_code' => '2301','name' => 'Tucupita' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1668,'odoo_municipality_id' => 1, 'odoo_mun_code' => '101','name' => 'Libertador' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 101, 'odoo_mun_code' => '1001','name' => 'Acosta' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 102, 'odoo_mun_code' => '1002','name' => 'Bolívar' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 103, 'odoo_mun_code' => '1003','name' => 'Buchivacoa' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 121, 'odoo_mun_code' => '1021','name' => 'Cacique Manaure' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 104, 'odoo_mun_code' => '1004','name' => 'Carirubana' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 105, 'odoo_mun_code' => '1005','name' => 'Colina' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 114, 'odoo_mun_code' => '1014','name' => 'Dabajuro' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 106, 'odoo_mun_code' => '1006','name' => 'Democracia' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 107, 'odoo_mun_code' => '1007','name' => 'Falcón' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 108, 'odoo_mun_code' => '1008','name' => 'Federación' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 120, 'odoo_mun_code' => '1020','name' => 'Jacura' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 116, 'odoo_mun_code' => '1016','name' => 'Los Taques' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 109, 'odoo_mun_code' => '1009','name' => 'Mauroa' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 110, 'odoo_mun_code' => '1010','name' => 'Miranda' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 115, 'odoo_mun_code' => '1015','name' => 'Monseñor Iturriza' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 122, 'odoo_mun_code' => '1022','name' => 'Palmasola' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 111, 'odoo_mun_code' => '1011','name' => 'Petit' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 117, 'odoo_mun_code' => '1017','name' => 'Píritu' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 119, 'odoo_mun_code' => '1019','name' => 'San Francisco' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 112, 'odoo_mun_code' => '1012','name' => 'Silva' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 123, 'odoo_mun_code' => '1023','name' => 'Sucre' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 125, 'odoo_mun_code' => '1025','name' => 'Tocópero' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 118, 'odoo_mun_code' => '1018','name' => 'Unión' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 124, 'odoo_mun_code' => '1024','name' => 'Urumaco' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1677,'odoo_municipality_id' => 113, 'odoo_mun_code' => '1013','name' => 'Zamora' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1678,'odoo_municipality_id' => 133, 'odoo_mun_code' => '1108','name' => 'Camaguán' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1678,'odoo_municipality_id' => 139, 'odoo_mun_code' => '1114','name' => 'Chaguaramas' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1678,'odoo_municipality_id' => 136, 'odoo_mun_code' => '1111','name' => 'El Socorro' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1678,'odoo_municipality_id' => 128, 'odoo_mun_code' => '1103','name' => 'Francisco De Miranda' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1678,'odoo_municipality_id' => 130, 'odoo_mun_code' => '1105','name' => 'José Félix Ribas' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1678,'odoo_municipality_id' => 129, 'odoo_mun_code' => '1104','name' => 'José Tadeo Monagas' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1678,'odoo_municipality_id' => 131, 'odoo_mun_code' => '1106','name' => 'Juan Germán Roscio' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1678,'odoo_municipality_id' => 127, 'odoo_mun_code' => '1102','name' => 'Julián Mellado' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1678,'odoo_municipality_id' => 135, 'odoo_mun_code' => '1110','name' => 'Las Mercedes' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1678,'odoo_municipality_id' => 126, 'odoo_mun_code' => '1101','name' => 'Leonardo Infante' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1678,'odoo_municipality_id' => 137, 'odoo_mun_code' => '1112','name' => 'Ortíz' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1678,'odoo_municipality_id' => 132, 'odoo_mun_code' => '1107','name' => 'Pedro Zaraza' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1678,'odoo_municipality_id' => 140, 'odoo_mun_code' => '1115','name' => 'San Gerónimo De Guayabal' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1678,'odoo_municipality_id' => 134, 'odoo_mun_code' => '1109','name' => 'San José De Guaribe' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1678,'odoo_municipality_id' => 138, 'odoo_mun_code' => '1113','name' => 'Santa María De Ipire' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1679,'odoo_municipality_id' => 148, 'odoo_mun_code' => '1208','name' => 'Andrés Eloy Blanco' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1679,'odoo_municipality_id' => 141, 'odoo_mun_code' => '1201','name' => 'Crespo' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1679,'odoo_municipality_id' => 142, 'odoo_mun_code' => '1202','name' => 'Iribarren' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1679,'odoo_municipality_id' => 143, 'odoo_mun_code' => '1203','name' => 'Jiménez' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1679,'odoo_municipality_id' => 144, 'odoo_mun_code' => '1204','name' => 'Morán' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1679,'odoo_municipality_id' => 145, 'odoo_mun_code' => '1205','name' => 'Palavecino' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1679,'odoo_municipality_id' => 149, 'odoo_mun_code' => '1209','name' => 'Simón Planas' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1679,'odoo_municipality_id' => 146, 'odoo_mun_code' => '1206','name' => 'Torres' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1679,'odoo_municipality_id' => 147, 'odoo_mun_code' => '1207','name' => 'Urdaneta' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1691,'odoo_municipality_id' => 335, 'odoo_mun_code' => '2401','name' => 'Vargas' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1680,'odoo_municipality_id' => 150, 'odoo_mun_code' => '1301','name' => 'Alberto Adriani' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1680,'odoo_municipality_id' => 151, 'odoo_mun_code' => '1302','name' => 'Andrés Bello' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1680,'odoo_municipality_id' => 160, 'odoo_mun_code' => '1311','name' => 'Antonio Pinto Salinas' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1680,'odoo_municipality_id' => 171, 'odoo_mun_code' => '1322','name' => 'Aricagua' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1680,'odoo_municipality_id' => 152, 'odoo_mun_code' => '1303','name' => 'Arzobispo Chacón' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1680,'odoo_municipality_id' => 153, 'odoo_mun_code' => '1304','name' => 'Campo Elías' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1680,'odoo_municipality_id' => 162, 'odoo_mun_code' => '1313','name' => 'Caracciolo Parra Olmedo' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1680,'odoo_municipality_id' => 163, 'odoo_mun_code' => '1314','name' => 'Cardenal Quintero' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1680,'odoo_municipality_id' => 154, 'odoo_mun_code' => '1305','name' => 'Guaraque' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1680,'odoo_municipality_id' => 155, 'odoo_mun_code' => '1306','name' => 'Julio César Salas' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1680,'odoo_municipality_id' => 156, 'odoo_mun_code' => '1307','name' => 'Justo Briceño' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1680,'odoo_municipality_id' => 157, 'odoo_mun_code' => '1308','name' => 'Libertador' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1680,'odoo_municipality_id' => 159, 'odoo_mun_code' => '1310','name' => 'Miranda' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1680,'odoo_municipality_id' => 161, 'odoo_mun_code' => '1312','name' => 'Obispo Ramos De Lora' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1680,'odoo_municipality_id' => 170, 'odoo_mun_code' => '1321','name' => 'Padre Noguera' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1680,'odoo_municipality_id' => 164, 'odoo_mun_code' => '1315','name' => 'Pueblo Llano' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1680,'odoo_municipality_id' => 165, 'odoo_mun_code' => '1316','name' => 'Rangel' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1680,'odoo_municipality_id' => 166, 'odoo_mun_code' => '1317','name' => 'Rivas Dávila' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1680,'odoo_municipality_id' => 158, 'odoo_mun_code' => '1309','name' => 'Santos Marquina' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1680,'odoo_municipality_id' => 167, 'odoo_mun_code' => '1318','name' => 'Sucre' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1680,'odoo_municipality_id' => 168, 'odoo_mun_code' => '1319','name' => 'Tovar' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1680,'odoo_municipality_id' => 169, 'odoo_mun_code' => '1320','name' => 'Tulio Febres Cordero' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1680,'odoo_municipality_id' => 172, 'odoo_mun_code' => '1323','name' => 'Zea' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1681,'odoo_municipality_id' => 173, 'odoo_mun_code' => '1401','name' => 'Acevedo' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1681,'odoo_municipality_id' => 186, 'odoo_mun_code' => '1414','name' => 'Andrés Bello' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1681,'odoo_municipality_id' => 188, 'odoo_mun_code' => '1416','name' => 'Baruta' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1681,'odoo_municipality_id' => 174, 'odoo_mun_code' => '1402','name' => 'Brión' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1681,'odoo_municipality_id' => 192, 'odoo_mun_code' => '1420','name' => 'Buroz' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1681,'odoo_municipality_id' => 189, 'odoo_mun_code' => '1417','name' => 'Carrizal' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1681,'odoo_municipality_id' => 190, 'odoo_mun_code' => '1418','name' => 'Chacao' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1681,'odoo_municipality_id' => 184, 'odoo_mun_code' => '1412','name' => 'Cristóbal Rojas' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1681,'odoo_municipality_id' => 191, 'odoo_mun_code' => '1419','name' => 'El Hatillo' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1681,'odoo_municipality_id' => 175, 'odoo_mun_code' => '1403','name' => 'Guaicaipuro' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1681,'odoo_municipality_id' => 176, 'odoo_mun_code' => '1404','name' => 'Independencia' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1681,'odoo_municipality_id' => 177, 'odoo_mun_code' => '1405','name' => 'Lander' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1681,'odoo_municipality_id' => 185, 'odoo_mun_code' => '1413','name' => 'Los Salias' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1681,'odoo_municipality_id' => 179, 'odoo_mun_code' => '1407','name' => 'Paz Castillo' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1681,'odoo_municipality_id' => 193, 'odoo_mun_code' => '1421','name' => 'Pedro Gual' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1681,'odoo_municipality_id' => 180, 'odoo_mun_code' => '1408','name' => 'Plaza' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1681,'odoo_municipality_id' => 178, 'odoo_mun_code' => '1406','name' => 'Páez' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1681,'odoo_municipality_id' => 187, 'odoo_mun_code' => '1415','name' => 'Simón Bolívar' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1681,'odoo_municipality_id' => 181, 'odoo_mun_code' => '1409','name' => 'Sucre' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1681,'odoo_municipality_id' => 182, 'odoo_mun_code' => '1410','name' => 'Urdaneta' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1681,'odoo_municipality_id' => 183, 'odoo_mun_code' => '1411','name' => 'Zamora' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1682,'odoo_municipality_id' => 194, 'odoo_mun_code' => '1501','name' => 'Acosta' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1682,'odoo_municipality_id' => 204, 'odoo_mun_code' => '1511','name' => 'Aguasay' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1682,'odoo_municipality_id' => 195, 'odoo_mun_code' => '1502','name' => 'Bolívar' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1682,'odoo_municipality_id' => 196, 'odoo_mun_code' => '1503','name' => 'Caripe' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1682,'odoo_municipality_id' => 197, 'odoo_mun_code' => '1504','name' => 'Cedeño' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1682,'odoo_municipality_id' => 198, 'odoo_mun_code' => '1505','name' => 'Ezequiel Zamora' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1682,'odoo_municipality_id' => 199, 'odoo_mun_code' => '1506','name' => 'Libertador' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1682,'odoo_municipality_id' => 200, 'odoo_mun_code' => '1507','name' => 'Maturín' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1682,'odoo_municipality_id' => 201, 'odoo_mun_code' => '1508','name' => 'Piar' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1682,'odoo_municipality_id' => 202, 'odoo_mun_code' => '1509','name' => 'Punceres' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1682,'odoo_municipality_id' => 205, 'odoo_mun_code' => '1512','name' => 'Santa Bárbara' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1682,'odoo_municipality_id' => 203, 'odoo_mun_code' => '1510','name' => 'Sotillo' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1682,'odoo_municipality_id' => 206, 'odoo_mun_code' => '1513','name' => 'Uracoa' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1683,'odoo_municipality_id' => 216, 'odoo_mun_code' => '1610','name' => 'Antolín Del Campo' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1683,'odoo_municipality_id' => 207, 'odoo_mun_code' => '1601','name' => 'Arismendi' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1683,'odoo_municipality_id' => 208, 'odoo_mun_code' => '1602','name' => 'Díaz' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1683,'odoo_municipality_id' => 217, 'odoo_mun_code' => '1611','name' => 'García' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1683,'odoo_municipality_id' => 209, 'odoo_mun_code' => '1603','name' => 'Gómez' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1683,'odoo_municipality_id' => 210, 'odoo_mun_code' => '1604','name' => 'Maneiro' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1683,'odoo_municipality_id' => 211, 'odoo_mun_code' => '1605','name' => 'Marcano' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1683,'odoo_municipality_id' => 212, 'odoo_mun_code' => '1606','name' => 'Mariño' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1683,'odoo_municipality_id' => 213, 'odoo_mun_code' => '1607','name' => 'Península De Macanao' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1683,'odoo_municipality_id' => 215, 'odoo_mun_code' => '1609','name' => 'Tubores' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1683,'odoo_municipality_id' => 214, 'odoo_mun_code' => '1608','name' => 'Villalba' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1684,'odoo_municipality_id' => 227, 'odoo_mun_code' => '1710','name' => 'Agua Blanca' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1684,'odoo_municipality_id' => 218, 'odoo_mun_code' => '1701','name' => 'Araure' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1684,'odoo_municipality_id' => 219, 'odoo_mun_code' => '1702','name' => 'Esteller' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1684,'odoo_municipality_id' => 220, 'odoo_mun_code' => '1703','name' => 'Guanare' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1684,'odoo_municipality_id' => 221, 'odoo_mun_code' => '1704','name' => 'Guanarito' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1684,'odoo_municipality_id' => 226, 'odoo_mun_code' => '1709','name' => 'Monseñor José Vicente De Unda' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1684,'odoo_municipality_id' => 222, 'odoo_mun_code' => '1705','name' => 'Ospino' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1684,'odoo_municipality_id' => 228, 'odoo_mun_code' => '1711','name' => 'Papelón' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1684,'odoo_municipality_id' => 223, 'odoo_mun_code' => '1706','name' => 'Páez' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1684,'odoo_municipality_id' => 229, 'odoo_mun_code' => '1712','name' => 'San Genaro De Boconoito' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1684,'odoo_municipality_id' => 230, 'odoo_mun_code' => '1713','name' => 'San Rafael De Onoto' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1684,'odoo_municipality_id' => 231, 'odoo_mun_code' => '1714','name' => 'Santa Rosalía' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1684,'odoo_municipality_id' => 224, 'odoo_mun_code' => '1707','name' => 'Sucre' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1684,'odoo_municipality_id' => 225, 'odoo_mun_code' => '1708','name' => 'Turén' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1685,'odoo_municipality_id' => 242, 'odoo_mun_code' => '1811','name' => 'Andrés Eloy Blanco' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1685,'odoo_municipality_id' => 244, 'odoo_mun_code' => '1813','name' => 'Andrés Mata' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1685,'odoo_municipality_id' => 232, 'odoo_mun_code' => '1801','name' => 'Arismendi' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1685,'odoo_municipality_id' => 233, 'odoo_mun_code' => '1802','name' => 'Benítez' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1685,'odoo_municipality_id' => 234, 'odoo_mun_code' => '1803','name' => 'Bermúdez' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1685,'odoo_municipality_id' => 245, 'odoo_mun_code' => '1814','name' => 'Bolívar' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1685,'odoo_municipality_id' => 235, 'odoo_mun_code' => '1804','name' => 'Cajigal' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1685,'odoo_municipality_id' => 246, 'odoo_mun_code' => '1815','name' => 'Cruz Salmerón Acosta' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1685,'odoo_municipality_id' => 243, 'odoo_mun_code' => '1812','name' => 'Libertador' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1685,'odoo_municipality_id' => 236, 'odoo_mun_code' => '1805','name' => 'Mariño' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1685,'odoo_municipality_id' => 237, 'odoo_mun_code' => '1806','name' => 'Mejía' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1685,'odoo_municipality_id' => 238, 'odoo_mun_code' => '1807','name' => 'Montes' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1685,'odoo_municipality_id' => 239, 'odoo_mun_code' => '1808','name' => 'Ribero' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1685,'odoo_municipality_id' => 240, 'odoo_mun_code' => '1809','name' => 'Sucre' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1685,'odoo_municipality_id' => 241, 'odoo_mun_code' => '1810','name' => 'Valdez' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 264, 'odoo_mun_code' => '1918','name' => 'Andrés Bello' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 269, 'odoo_mun_code' => '1923','name' => 'Antonio Rómulo Costa' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 247, 'odoo_mun_code' => '1901','name' => 'Ayacucho' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 248, 'odoo_mun_code' => '1902','name' => 'Bolívar' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 250, 'odoo_mun_code' => '1904','name' => 'Cárdenas' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 256, 'odoo_mun_code' => '1910','name' => 'Córdoba' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 265, 'odoo_mun_code' => '1919','name' => 'Fernández Feo' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 270, 'odoo_mun_code' => '1924','name' => 'Francisco De Miranda' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 257, 'odoo_mun_code' => '1911','name' => 'García De Hevia' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 258, 'odoo_mun_code' => '1912','name' => 'Guásimos' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 249, 'odoo_mun_code' => '1903','name' => 'Independencia' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 271, 'odoo_mun_code' => '1925','name' => 'José María Vargas' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 252, 'odoo_mun_code' => '1906','name' => 'Junín' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 251, 'odoo_mun_code' => '1905','name' => 'Jáuregui' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 266, 'odoo_mun_code' => '1920','name' => 'Libertad' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 260, 'odoo_mun_code' => '1914','name' => 'Libertador' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 253, 'odoo_mun_code' => '1907','name' => 'Lobatera' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 259, 'odoo_mun_code' => '1913','name' => 'Michelena' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 261, 'odoo_mun_code' => '1915','name' => 'Panamericano' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 262, 'odoo_mun_code' => '1916','name' => 'Pedro María Ureña' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 272, 'odoo_mun_code' => '1926','name' => 'Rafael Urdaneta' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 267, 'odoo_mun_code' => '1921','name' => 'Samuel Darío Maldonado' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 254, 'odoo_mun_code' => '1908','name' => 'San Cristóbal' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 275, 'odoo_mun_code' => '1929','name' => 'San Judas Tadeo' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 268, 'odoo_mun_code' => '1922','name' => 'Seboruco' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 273, 'odoo_mun_code' => '1927','name' => 'Simón Rodríguez' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 263, 'odoo_mun_code' => '1917','name' => 'Sucre' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 274, 'odoo_mun_code' => '1928','name' => 'Torbes' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1686,'odoo_municipality_id' => 255, 'odoo_mun_code' => '1909','name' => 'Uribante' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1687,'odoo_municipality_id' => 290, 'odoo_mun_code' => '2015','name' => 'Andrés Bello' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1687,'odoo_municipality_id' => 277, 'odoo_mun_code' => '2002','name' => 'Boconó' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1687,'odoo_municipality_id' => 291, 'odoo_mun_code' => '2016','name' => 'Bolívar' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1687,'odoo_municipality_id' => 283, 'odoo_mun_code' => '2008','name' => 'Candelaria' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1687,'odoo_municipality_id' => 278, 'odoo_mun_code' => '2003','name' => 'Carache' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1687,'odoo_municipality_id' => 279, 'odoo_mun_code' => '2004','name' => 'Escuque' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1687,'odoo_municipality_id' => 292, 'odoo_mun_code' => '2017','name' => 'José Felipe Márquez Cañizales' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1687,'odoo_municipality_id' => 293, 'odoo_mun_code' => '2018','name' => 'Juan Vicente Campo Elías' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1687,'odoo_municipality_id' => 294, 'odoo_mun_code' => '2019','name' => 'La Ceiba' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1687,'odoo_municipality_id' => 284, 'odoo_mun_code' => '2009','name' => 'Miranda' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1687,'odoo_municipality_id' => 285, 'odoo_mun_code' => '2010','name' => 'Monte Carmelo' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1687,'odoo_municipality_id' => 286, 'odoo_mun_code' => '2011','name' => 'Motatán' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1687,'odoo_municipality_id' => 295, 'odoo_mun_code' => '2020','name' => 'Pampanito' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1687,'odoo_municipality_id' => 287, 'odoo_mun_code' => '2012','name' => 'Pampán' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1687,'odoo_municipality_id' => 276, 'odoo_mun_code' => '2001','name' => 'Rafael Rangel' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1687,'odoo_municipality_id' => 288, 'odoo_mun_code' => '2013','name' => 'San Rafael De Carvajal' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1687,'odoo_municipality_id' => 289, 'odoo_mun_code' => '2014','name' => 'Sucre' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1687,'odoo_municipality_id' => 280, 'odoo_mun_code' => '2005','name' => 'Trujillo' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1687,'odoo_municipality_id' => 281, 'odoo_mun_code' => '2006','name' => 'Urdaneta' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1687,'odoo_municipality_id' => 282, 'odoo_mun_code' => '2007','name' => 'Valera' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1688,'odoo_municipality_id' => 307, 'odoo_mun_code' => '2112','name' => 'Arístides Bastidas' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1688,'odoo_municipality_id' => 296, 'odoo_mun_code' => '2101','name' => 'Bolívar' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1688,'odoo_municipality_id' => 297, 'odoo_mun_code' => '2102','name' => 'Bruzual' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1688,'odoo_municipality_id' => 305, 'odoo_mun_code' => '2110','name' => 'Cocorote' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1688,'odoo_municipality_id' => 306, 'odoo_mun_code' => '2111','name' => 'Independencia' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1688,'odoo_municipality_id' => 303, 'odoo_mun_code' => '2108','name' => 'José Antonio Páez' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1688,'odoo_municipality_id' => 304, 'odoo_mun_code' => '2109','name' => 'La Trinidad' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1688,'odoo_municipality_id' => 308, 'odoo_mun_code' => '2113','name' => 'Manuel Monge' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1688,'odoo_municipality_id' => 298, 'odoo_mun_code' => '2103','name' => 'Nirgua' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1688,'odoo_municipality_id' => 302, 'odoo_mun_code' => '2107','name' => 'Peña' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1688,'odoo_municipality_id' => 299, 'odoo_mun_code' => '2104','name' => 'San Felipe' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1688,'odoo_municipality_id' => 300, 'odoo_mun_code' => '2105','name' => 'Sucre' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1688,'odoo_municipality_id' => 301, 'odoo_mun_code' => '2106','name' => 'Urachiche' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1688,'odoo_municipality_id' => 309, 'odoo_mun_code' => '2114','name' => 'Veroes' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1689,'odoo_municipality_id' => 326, 'odoo_mun_code' => '2217','name' => 'Almirante Padilla' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1689,'odoo_municipality_id' => 310, 'odoo_mun_code' => '2201','name' => 'Baralt' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1689,'odoo_municipality_id' => 323, 'odoo_mun_code' => '2214','name' => 'Cabimas' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1689,'odoo_municipality_id' => 321, 'odoo_mun_code' => '2212','name' => 'Catatumbo' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1689,'odoo_municipality_id' => 312, 'odoo_mun_code' => '2203','name' => 'Colón' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1689,'odoo_municipality_id' => 329, 'odoo_mun_code' => '2220','name' => 'Francisco Javier Pulgar' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1689,'odoo_municipality_id' => 325, 'odoo_mun_code' => '2216','name' => 'Jesús Enrique Lossada' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1689,'odoo_municipality_id' => 328, 'odoo_mun_code' => '2219','name' => 'Jesús María Semprún' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1689,'odoo_municipality_id' => 319, 'odoo_mun_code' => '2210','name' => 'La Cañada De Urdaneta' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1689,'odoo_municipality_id' => 320, 'odoo_mun_code' => '2211','name' => 'Lagunillas' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1689,'odoo_municipality_id' => 317, 'odoo_mun_code' => '2208','name' => 'Machiques De Perijá' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1689,'odoo_municipality_id' => 313, 'odoo_mun_code' => '2204','name' => 'Mara' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1689,'odoo_municipality_id' => 314, 'odoo_mun_code' => '2205','name' => 'Maracaibo' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1689,'odoo_municipality_id' => 315, 'odoo_mun_code' => '2206','name' => 'Miranda' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1689,'odoo_municipality_id' => 316, 'odoo_mun_code' => '2207','name' => 'Páez' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1689,'odoo_municipality_id' => 322, 'odoo_mun_code' => '2213','name' => 'Rosario De Perijá' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1689,'odoo_municipality_id' => 327, 'odoo_mun_code' => '2218','name' => 'San Francisco' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1689,'odoo_municipality_id' => 311, 'odoo_mun_code' => '2202','name' => 'Santa Rita' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1689,'odoo_municipality_id' => 330, 'odoo_mun_code' => '2221','name' => 'Simón Bolívar' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1689,'odoo_municipality_id' => 318, 'odoo_mun_code' => '2209','name' => 'Sucre' ]);
        DB::table('cities')->insert(['odoo_state_id' => 1689,'odoo_municipality_id' => 324, 'odoo_mun_code' => '2215','name' => 'Valmore Rodríguez' ]);
	DB::table('cities')->update(['status' => 1]);
                
    }
}
