# just countries for another api, if i need to put them. 


Country.create([
  {
    "id":1,
    "name_en": "Afghanistan",
    "name_es": "Afganistán",
    "name": "Afganistán",
    "sortname": "AF",
    "sortname2": "AFG",
    "latitude": 33.93911,
    "longitude": 67.709953,
    "flag": "🇦🇫",
    "phonecode": 93
  },
  {
    "id":2,
    "name_en": "Albania",
    "name_es": "Albania",
    "name": "Albania",
    "sortname": "AL",
    "sortname2": "ALB",
    "latitude": 41.153332,
    "longitude": 20.168331,
    "flag": "🇦🇱",
    "phonecode": 355
  },
  {
    "id":3,
    "name_en": "Algeria",
    "name_es": "Argelia",
    "name": "Argelia",
    "sortname": "DZ",
    "sortname2": "DZA",
    "latitude": 28.033886,
    "longitude": 28.033886,
    "flag": "🇩🇿",
    "phonecode": 213
  },
  {
    "id":4,
    "name_en": "American Samoa",
    "name_es": "Samoa Americana",
    "name": "Samoa Americana",
    "sortname": "AS",
    "sortname2": "ASM",
    "latitude": -14.270972,
    "longitude": -170.132217,
    "flag": "🇦🇸",
    "phonecode": 1684
  },
  {
    "id":5,
    "name_en": "Andorra",
    "name_es": "Andorra",
    "name": "Andorra",
    "sortname": "AD",
    "sortname2": "AND",
    "latitude": 42.546245,
    "longitude": 1.601554,
    "flag": "🇦🇩",
    "phonecode": 376
  },
  {
    "id":6,
    "name_en": "Angola",
    "name_es": "Angola",
    "name": "Angola",
    "sortname": "AO",
    "sortname2": "AGO",
    "latitude": -11.202692,
    "longitude": 17.873887,
    "flag": "🇦🇴",
    "phonecode": 244
  },
  {
    "id":7,
    "name_en": "Anguilla",
    "name_es": "Anguilla",
    "name": "Anguilla",
    "sortname": "AI",
    "sortname2": "AIA",
    "latitude": 18.220554,
    "longitude": -63.068615,
    "flag": "🇦🇮",
    "phonecode": 1264
  },
  {
    "id":8,
    "name_en": "Antarctica",
    "name_es": "Antártida",
    "name": "Antártida",
    "sortname": "AQ",
    "sortname2": "ATA",
    "latitude": -75.250973,
    "longitude": -0.071389,
    "flag": "🇦🇶",
    "phonecode": 0
  },
  {
    "id":9,
    "name_en": "Antigua and Barbuda",
    "name_es": "Antigua y Barbuda",
    "name": "Antigua y Barbuda",
    "sortname": "AG",
    "sortname2": "ATG",
    "latitude": 17.060816,
    "longitude": -61.796428,
    "flag": "🇦🇬",
    "phonecode": 1268
  },
  {
    "id":10,
    "name_en": "Argentina",
    "name_es": "Argentina",
    "name": "Argentina",
    "sortname": "AR",
    "sortname2": "ARG",
    "latitude": -38.416097,
    "longitude": -63.616672,
    "flag": "🇦🇷",
    "phonecode": 54
  },
  {
    "id":11,
    "name_en": "Armenia",
    "name_es": "Armenia",
    "name": "Armenia",
    "sortname": "AM",
    "sortname2": "ARM",
    "latitude": 40.069099,
    "longitude": 45.038189,
    "flag": "🇦🇲",
    "phonecode": 374
  },
  {
    "id":12,
    "name_en": "Aruba",
    "name_es": "Aruba",
    "name": "Aruba",
    "sortname": "AW",
    "sortname2": "ABW",
    "latitude": 12.52111,
    "longitude": -69.968338,
    "flag": "🇦🇼",
    "phonecode": 297
  },
  {
    "id":13,
    "name_en": "Australia",
    "name_es": "Australia",
    "name": "Australia",
    "sortname": "AU",
    "sortname2": "AUS",
    "latitude": -25.274398,
    "longitude": 133.775136,
    "flag": "🇦🇺",
    "phonecode": 61
  },
  {
    "id":14,
    "name_en": "Austria",
    "name_es": "Austria",
    "name": "Austria",
    "sortname": "AT",
    "sortname2": "AUT",
    "latitude": 47.516231,
    "longitude": 14.550072,
    "flag": "🇦🇹",
    "phonecode": 43
  },
  {
    "id":15,
    "name_en": "Azerbaijan",
    "name_es": "Azerbaiyán",
    "name": "Azerbaiyán",
    "sortname": "AZ",
    "sortname2": "AZE",
    "latitude": 40.143105,
    "longitude": 47.576927,
    "flag": "🇦🇿",
    "phonecode": 994
  },
  {
    "id":16,
    "name_en": "Bahamas",
    "name_es": "Bahamas",
    "name": "Bahamas",
    "sortname": "BS",
    "sortname2": "BHS",
    "latitude": 25.03428,
    "longitude": -77.39628,
    "flag": "🇧🇸",
    "phonecode": 1242
  },
  {
    "id":17,
    "name_en": "Bahrain",
    "name_es": "Baréin",
    "name": "Baréin",
    "sortname": "BH",
    "sortname2": "BHR",
    "latitude": 25.930414,
    "longitude": 50.637772,
    "flag": "🇧🇭",
    "phonecode": 973
  },
  {
    "id":18,
    "name_en": "Bangladesh",
    "name_es": "Banglades",
    "name": "Banglades",
    "sortname": "BD",
    "sortname2": "BGD",
    "latitude": 23.684994,
    "longitude": 90.356331,
    "flag": "🇧🇩",
    "phonecode": 880
  },
  {
    "id":19,
    "name_en": "Barbados",
    "name_es": "Barbados",
    "name": "Barbados",
    "sortname": "BB",
    "sortname2": "BRB",
    "latitude": 13.193887,
    "longitude": -59.543198,
    "flag": "🇧🇧",
    "phonecode": 1246
  },{
    "id":20,
    "name_en": "Belarus",
    "name_es": "Bielorrusia",
    "name": "Bielorrusia",
    "sortname": "BY",
    "sortname2": "BLR",
    "latitude": 53.709807,
    "longitude": 27.953389,
    "flag": "🇧🇾",
    "phonecode": 375
  },
  {
    "id":21,
    "name_en": "Belgium",
    "name_es": "Bélgica",
    "name": "Bélgica",
    "sortname": "BE",
    "sortname2": "BEL",
    "latitude": 50.503887,
    "longitude": 4.469936,
    "flag": "🇧🇪",
    "phonecode": 32
  },
  {
    "id":22,
    "name_en": "Belize",
    "name_es": "Belice",
    "name": "Belice",
    "sortname": "BZ",
    "sortname2": "BLZ",
    "latitude": 17.189877,
    "longitude": -88.49765,
    "flag": "🇧🇿",
    "phonecode": 501
  },
  {
    "id":23,
    "name_en": "Benin",
    "name_es": "Benin",
    "name": "Benin",
    "sortname": "BJ",
    "sortname2": "BEN",
    "latitude": 9.30769,
    "longitude": 2.315834,
    "flag": "🇧🇯",
    "phonecode": 229
  },
  {
    "id":24,
    "name_en": "Bermuda",
    "name_es": "Bermudas",
    "name": "Bermudas",
    "sortname": "BM",
    "sortname2": "BMU",
    "latitude": 32.321384,
    "longitude": -64.75737,
    "flag": "🇧🇲",
    "phonecode": 1441
  },
  {
    "id":25,
    "name_en": "Bhutan",
    "name_es": "Butan",
    "name": "Butan",
    "sortname": "BT",
    "sortname2": "BTN",
    "latitude": 27.514162,
    "longitude": 90.433601,
    "flag": "🇧🇹",
    "phonecode": 975
  },
  {
    "id":26,
    "name_en": "Bolivia",
    "name_es": "Bolivia",
    "name": "Bolivia",
    "sortname": "BO",
    "sortname2": "BOL",
    "latitude": -16.290154,
    "longitude": -63.588653,
    "flag": "🇧🇴",
    "phonecode": 591
  },
  {
    "id":27,
    "name_en": "Bosnia and Herzegovina",
    "name_es": "Bosnia-Herzegovina",
    "name": "Bosnia-Herzegovina",
    "sortname": "BA",
    "sortname2": "BIH",
    "latitude": 43.915886,
    "longitude": 17.679076,
    "flag": "🇧🇦",
    "phonecode": 387
  },
  {
    "id":28,
    "name_en": "Botswana",
    "name_es": "Botsuana",
    "name": "Botsuana",
    "sortname": "BW",
    "sortname2": "BWA",
    "latitude": -22.328474,
    "longitude": 24.684866,
    "flag": "🇧🇼",
    "phonecode": 267
  },
  {
    "id":29,
    "name_en": "Bouvet Island",
    "name_es": "Isla Bouvet",
    "name": "Isla Bouvet",
    "sortname": "BV",
    "sortname2": "BVT",
    "latitude": -54.423199,
    "longitude": 3.413194,
    "flag": "🇧🇻",
    "phonecode": 0
  },
  {
    "id":30,
    "name_en": "Brazil",
    "name_es": "Brasil",
    "name": "Brasil",
    "sortname": "BR",
    "sortname2": "BRA",
    "latitude": -14.235004,
    "longitude": -51.92528,
    "flag": "🇧🇷",
    "phonecode": 55
  },
  {
    "id":31,
    "name_en": "British Indian Ocean Territory",
    "name_es": "Territorio Británico del Océano Índico",
    "name": "Territorio Británico del Océano Índico",
    "sortname": "IO",
    "sortname2": "IOT",
    "latitude": -6.343194,
    "longitude": 71.876519,
    "flag": "🇮🇴",
    "phonecode": 246
  },
  {
    "id":32,
    "name_en": "Brunei Darussalam",
    "name_es": "Brunei",
    "name": "Brunei",
    "sortname": "BN",
    "sortname2": "BRN",
    "latitude": 4.535277,
    "longitude": 114.727669,
    "flag": "🇧🇳",
    "phonecode": 673
  },
  {
    "id":33,
    "name_en": "Bulgaria",
    "name_es": "Bulgaria",
    "name": "Bulgaria",
    "sortname": "BG",
    "sortname2": "BGR",
    "latitude": 42.733883,
    "longitude": 25.48583,
    "flag": "🇧🇬",
    "phonecode": 359
  },
  {
    "id":34,
    "name_en": "Burkina Faso",
    "name_es": "Burkina Faso",
    "name": "Burkina Faso",
    "sortname": "BF",
    "sortname2": "BFA",
    "latitude": 12.238333,
    "longitude": -1.561593,
    "flag": "🇧🇫",
    "phonecode": 226
  },
  {
    "id":35,
    "name_en": "Burundi",
    "name_es": "Burundi",
    "name": "Burundi",
    "sortname": "BI",
    "sortname2": "BDI",
    "latitude": -3.373056,
    "longitude": 29.918886,
    "flag": "🇧🇮",
    "phonecode": 257
  },
  {
    "id":36,
    "name_en": "Cambodia",
    "name_es": "Camboya",
    "name": "Camboya",
    "sortname": "KH",
    "sortname2": "KHM",
    "latitude": 12.565679,
    "longitude": 104.990963,
    "flag": "🇰🇭",
    "phonecode": 855
  },
  {
    "id":37,
    "name_en": "Cameroon",
    "name_es": "Camerún",
    "name": "Camerún",
    "sortname": "CM",
    "sortname2": "CMR",
    "latitude": 7.369722,
    "longitude": 12.354722,
    "flag": "🇨🇲",
    "phonecode": 237
  },
  {
    "id":38,
    "name_en": "Canada",
    "name_es": "Canadá",
    "name": "Canadá",
    "sortname": "CA",
    "sortname2": "CAN",
    "latitude": 56.130366,
    "longitude": -106.346771,
    "flag": "🇨🇦",
    "phonecode": 1
  },
  {
    "id":39,
    "name_en": "Cape Verde",
    "name_es": "Cabo Verde",
    "name": "Cabo Verde",
    "sortname": "CV",
    "sortname2": "CPV",
    "latitude": 16.002082,
    "longitude": -24.013197,
    "flag": "🇨🇻",
    "phonecode": 238
  },
  {
    "id":40,
    "name_en": "Cayman Islands",
    "name_es": "Islas Caimán",
    "name": "Islas Caimán",
    "sortname": "KY",
    "sortname2": "CYM",
    "latitude": 19.513469,
    "longitude": -80.566956,
    "flag": "🇰🇾",
    "phonecode": 1345
  },
  {
    "id":41,
    "name_en": "Central African Republic",
    "name_es": "República Centroafricana",
    "name": "República Centroafricana",
    "sortname": "CF",
    "sortname2": "CAF",
    "latitude": 6.611111,
    "longitude": 20.939444,
    "flag": "🇨🇫",
    "phonecode": 236
  },
  {
    "id":42,
    "name_en": "Chad",
    "name_es": "Chad",
    "name": "Chad",
    "sortname": "TD",
    "sortname2": "TCD",
    "latitude": 15.454166,
    "longitude": 18.732207,
    "flag": "🇹🇩",
    "phonecode": 235
  },
  {
    "id":43,
    "name_en": "Chile",
    "name_es": "Chile",
    "name": "Chile",
    "sortname": "CL",
    "sortname2": "CHL",
    "latitude": -35.675147,
    "longitude": -71.542969,
    "flag": "🇨🇱",
    "phonecode": 56
  },
  {
    "id":44,
    "name_en": "China",
    "name_es": "China",
    "name": "China",
    "sortname": "CN",
    "sortname2": "CHN",
    "latitude": 35.86166,
    "longitude": 104.195397,
    "flag": "🇨🇳",
    "phonecode": 86
  },
  {
    "id":45,
    "name_en": "Christmas Island",
    "name_es": "Isla de Navidad",
    "name": "Isla de Navidad",
    "sortname": "CX",
    "sortname2": "CXR",
    "latitude": -10.447525,
    "longitude": 105.690449,
    "flag": "🇨🇽",
    "phonecode": 61
  },
  {
    "id":46,
    "name_en": "Cocos (Keeling) Islands",
    "name_es": "Islas Cocos",
    "name": "Islas Cocos",
    "sortname": "CC",
    "sortname2": "CCK",
    "latitude": -12.164165,
    "longitude": 96.870956,
    "flag": "🇨🇨",
    "phonecode": 672
  },
  {
    "id":47,
    "name_en": "Colombia",
    "name_es": "Colombia",
    "name": "Colombia",
    "sortname": "CO",
    "sortname2": "COL",
    "latitude": 4.570868,
    "longitude": -74.297333,
    "flag": "🇨🇴",
    "phonecode": 57
  },
  {
    "id":48,
    "name_en": "Comoros",
    "name_es": "Comoras",
    "name": "Comoras",
    "sortname": "KM",
    "sortname2": "COM",
    "latitude": -11.875001,
    "longitude": 43.872219,
    "flag": "🇰🇲",
    "phonecode": 269
  },
  {
    "id":49,
    "name_en": "Republic of the Congo",
    "name_es": "Congo",
    "name": "Congo",
    "sortname": "CG",
    "sortname2": "COG",
    "latitude": -3.9834936,
    "longitude": 12.6823952,
    "flag": "🇨🇬",
    "phonecode": 242
  },
  {
    "id":50,
    "name_en": "Congo, The Democratic Republic of the",
    "name_es": "República Democrática del Congo",
    "name": "República Democrática del Congo",
    "sortname": "CD",
    "sortname2": "COD",
    "latitude": -0.228021,
    "longitude": 15.827659,
    "flag": "🇨🇩",
    "phonecode": 242
  },
  {
    "id":51,
    "name_en": "Cook Islands",
    "name_es": "Islas Cook",
    "name": "Islas Cook",
    "sortname": "CK",
    "sortname2": "COK",
    "latitude": -21.236736,
    "longitude": -159.777671,
    "flag": "🇨🇰",
    "phonecode": 682
  },
  {
    "id":52,
    "name_en": "Costa Rica",
    "name_es": "Costa Rica",
    "name": "Costa Rica",
    "sortname": "CR",
    "sortname2": "CRI",
    "latitude": 9.748917,
    "longitude": -83.753428	,
    "flag": "🇨🇷",
    "phonecode": 506
  },
  {
    "id":53,
    "name_en": "Ivory Coast",
    "name_es": "Costa de Marfil",
    "name": "Costa de Marfil",
    "sortname": "CI",
    "sortname2": "CIV",
    "latitude": 7.539989,
    "longitude": -5.54708	,
    "flag": "🇨🇮",
    "phonecode": 225
  },
  {
    "id":54,
    "name_en": "Croatia",
    "name_es": "Croacia",
    "name": "Croacia",
    "sortname": "HR",
    "sortname2": "HRV",
    "latitude": 45.1,
    "longitude": 15.2,
    "flag": "🇭🇷",
    "phonecode": 385
  },
  {
    "id":55,
    "name_en": "Cuba",
    "name_es": "Cuba",
    "name": "Cuba",
    "sortname": "CU",
    "sortname2": "CUB",
    "latitude": 21.521757,
    "longitude": -77.781167,
    "flag": "🇨🇺",
    "phonecode": 53
  },
  {
    "id":56,
    "name_en": "Cyprus",
    "name_es": "Chipre",
    "name": "Chipre",
    "sortname": "CY",
    "sortname2": "CYP",
    "latitude": 35.126413,
    "longitude": 33.429859,
    "flag": "🇨🇾",
    "phonecode": 357
  },
  {
    "id":57,
    "name_en": "Czech Republic",
    "name_es": "República Checa",
    "name": "República Checa",
    "sortname": "CZ",
    "sortname2": "CZE",
    "latitude": 49.817492,
    "longitude": 15.472962,
    "flag": "🇨🇿",
    "phonecode": 420
  },
  {
    "id":58,
    "name_en": "Denmark",
    "name_es": "Dinamarca",
    "name": "Dinamarca",
    "sortname": "DK",
    "sortname2": "DNK",
    "latitude": 56.26392,
    "longitude": 9.501785,
    "flag": "🇩🇰",
    "phonecode": 45
  },
  {
    "id":59,
    "name_en": "Djibouti",
    "name_es": "Yibuti",
    "name": "Yibuti",
    "sortname": "DJ",
    "sortname2": "DJI",
    "latitude": 11.825138,
    "longitude": 42.590275,
    "flag": "🇩🇯",
    "phonecode": 253
  },
  {
    "id":60,
    "name_en": "Dominica",
    "name_es": "Dominica",
    "name": "Dominica",
    "sortname": "DM",
    "sortname2": "DMA",
    "latitude": 15.414999,
    "longitude": -61.370976,
    "flag": "🇩🇲",
    "phonecode": 1767
  },
  {
    "id":61,
    "name_en": "Dominican Republic",
    "name_es": "República Dominicana",
    "name": "República Dominicana",
    "sortname": "DO",
    "sortname2": "DOM",
    "latitude": 18.735693,
    "longitude": -70.162651,
    "flag": "🇩🇴",
    "phonecode": 1809
  },
  {
    "id":62,
    "name_en": "East Timor",
    "name_es": "Timor Oriental",
    "name": "Timor Oriental",
    "sortname": "TP",
    "sortname2": "EAT",
    "latitude": -8.7827118,
    "longitude": 123.4845096,
    "flag": "🇹🇱",
    "phonecode": 670
  },
  {
    "id":63,
    "name_en": "Ecuador",
    "name_es": "Ecuador",
    "name": "Ecuador",
    "sortname": "EC",
    "sortname2": "ECU",
    "latitude": -1.831239,
    "longitude": -78.183406,
    "flag": "🇪🇨",
    "phonecode": 593
  },
  {
    "id":64,
    "name_en": "Egypt",
    "name_es": "Egipto",
    "name": "Egipto",
    "sortname": "EG",
    "sortname2": "EGY",
    "latitude": 26.820553,
    "longitude": 30.802498,
    "flag": "🇪🇬",
    "phonecode": 20
  },
  {
    "id":65,
    "name_en": "Salvador",
    "name_es": "El Salvador",
    "name": "El Salvador",
    "sortname": "SV",
    "sortname2": "SLV",
    "latitude": 13.794185,
    "longitude": -88.89653,
    "flag": "🇸🇻",
    "phonecode": 503
  },
  {
    "id":66,
    "name_en": "Equatorial Guinea",
    "name_es": "Guinea Ecuatorial",
    "name": "Guinea Ecuatorial",
    "sortname": "GQ",
    "sortname2": "GNQ",
    "latitude": 1.650801,
    "longitude": 10.267895,
    "flag": "🇬🇶",
    "phonecode": 240
  },
  {
    "id":67,
    "name_en": "Eritrea",
    "name_es": "Eritrea",
    "name": "Eritrea",
    "sortname": "ER",
    "sortname2": "ERI",
    "latitude": 15.179384,
    "longitude": 39.782334,
    "flag": "🇪🇷",
    "phonecode": 291
  },
  {
    "id":68,
    "name_en": "Estonia",
    "name_es": "Estonia",
    "name": "Estonia",
    "sortname": "EE",
    "sortname2": "EST",
    "latitude": 58.595272,
    "longitude": 25.013607,
    "flag": "🇪🇪",
    "phonecode": 372
  },
  {
    "id":69,
    "name_en": "Ethiopia",
    "name_es": "Etiopía",
    "name": "Etiopía",
    "sortname": "ET",
    "sortname2": "ETH",
    "latitude": 9.145,
    "longitude": 40.489673,
    "flag": "🇪🇹",
    "phonecode": 251
  },
  {
    "id":70,
    "name_en": "External Territories of Australia",
    "name_es": "Territorios Externos de Australia",
    "name": "Territorios Externos de Australia",
    "sortname": "XA",
    "sortname2": "XTA",
    "latitude": 0,
    "longitude": 0,
    "flag": "🇦🇺",
    "phonecode": 61
  },
  {
    "id":71,
    "name_en": "Falkland Islands",
    "name_es": "Islas Malvinas",
    "name": "Islas Malvinas",
    "sortname": "FK",
    "sortname2": "KLK",
    "latitude": -51.796253,
    "longitude": -59.523613,
    "flag": "🇫🇰",
    "phonecode": 500
  },
  {
    "id":72,
    "name_en": "Faroe Islands",
    "name_es": "Islas Feroe",
    "name": "Islas Feroe",
    "sortname": "FO",
    "sortname2": "FRO",
    "latitude": 61.892635,
    "longitude": -6.911806,
    "flag": "🇫🇴",
    "phonecode": 298
  },
  {
    "id":73,
    "name_en": "Fiji",
    "name_es": "Fiyi",
    "name": "Fiyi",
    "sortname": "FJ",
    "sortname2": "FJI",
    "latitude": -16.578193	,
    "longitude": 179.414413,
    "flag": "🇫🇯",
    "phonecode": 679
  },
  {
    "id":74,
    "name_en": "Finland",
    "name_es": "Finlandia",
    "name": "Finlandia",
    "sortname": "FI",
    "sortname2": "FIN",
    "latitude": 61.92411,
    "longitude": 25.748151,
    "flag": "🇫🇮",
    "phonecode": 358
  },
  {
    "id":75,
    "name_en": "France",
    "name_es": "Francia",
    "name": "Francia",
    "sortname": "FR",
    "sortname2": "FRA",
    "latitude": 46.227638,
    "longitude": 2.213749,
    "flag": "🇫🇷",
    "phonecode": 33
  },
  {
    "id":76,
    "name_en": "French Guiana",
    "name_es": "Guayana Francesa",
    "name": "Guayana Francesa",
    "sortname": "GF",
    "sortname2": "GUF",
    "latitude": 3.933889,
    "longitude": -53.125782,
    "flag": "🇬🇫",
    "phonecode": 594
  },
  {
    "id":77,
    "name_en": "French Polynesia",
    "name_es": "Polinesia Francesa",
    "name": "Polinesia Francesa",
    "sortname": "PF",
    "sortname2": "PYF",
    "latitude": -17.679742	,
    "longitude": -149.406843,
    "flag": "🇵🇫",
    "phonecode": 689
  },
  {
    "id":78,
    "name_en": "French Southern Territories",
    "name_es": "Territorios Australes Franceses",
    "name": "Territorios Australes Franceses",
    "sortname": "TF",
    "sortname2": "ATF",
    "latitude": -49.280366,
    "longitude": 69.348557,
    "flag": "🇹🇫",
    "phonecode": 0
  },
  {
    "id":79,
    "name_en": "Gabon",
    "name_es": "Gabón",
    "name": "Gabón",
    "sortname": "GA",
    "sortname2": "GAB",
    "latitude": -0.803689,
    "longitude": 11.609444,
    "flag": "🇬🇦",
    "phonecode": 241
  },
  {
    "id":80,
    "name_en": "Gambia",
    "name_es": "Gambia",
    "name": "Gambia",
    "sortname": "GM",
    "sortname2": "GMB",
    "latitude": 13.443182,
    "longitude": -15.310139,
    "flag": "🇬🇲",
    "phonecode": 220
  },
  {
    "id":81,
    "name_en": "Georgia",
    "name_es": "Georgia",
    "name": "Georgia",
    "sortname": "GE",
    "sortname2": "GEO",
    "latitude": 42.315407,
    "longitude": 43.356892,
    "flag": "🇬🇪",
    "phonecode": 995
  },
  {
    "id":82,
    "name_en": "Germany",
    "name_es": "Alemania",
    "name": "Alemania",
    "sortname": "DE",
    "sortname2": "DEU",
    "latitude": 51.165691,
    "longitude": 10.451526,
    "flag": "🇩🇪",
    "phonecode": 49
  },
  {
    "id":83,
    "name_en": "Ghana",
    "name_es": "Ghana",
    "name": "Ghana",
    "sortname": "GH",
    "sortname2": "GHA",
    "latitude": 7.946527,
    "longitude": -1.023194,
    "flag": "🇬🇭",
    "phonecode": 233
  },
  {
    "id":84,
    "name_en": "Gibraltar",
    "name_es": "Gibraltar",
    "name": "Gibraltar",
    "sortname": "GI",
    "sortname2": "GIB",
    "latitude": 36.137741,
    "longitude": -5.345374,
    "flag": "🇬🇮",
    "phonecode": 350
  },
  {
    "id":85,
    "name_en": "Greece",
    "name_es": "Grecia",
    "name": "Grecia",
    "sortname": "GR",
    "sortname2": "GRC",
    "latitude": 39.074208,
    "longitude": 21.824312,
    "flag": "🇬🇷",
    "phonecode": 30
  },
  {
    "id":86,
    "name_en": "Greenland",
    "name_es": "Groenlandia",
    "name": "Groenlandia",
    "sortname": "GL",
    "sortname2": "GRL",
    "latitude": 71.706936,
    "longitude": -42.604303,
    "flag": "🇬🇱",
    "phonecode": 299
  },
  {
    "id":87,
    "name_en": "Grenada",
    "name_es": "Granada",
    "name": "Granada",
    "sortname": "GD",
    "sortname2": "GRD",
    "latitude": 12.262776,
    "longitude": -61.604171,
    "flag": "🇬🇩",
    "phonecode": 1473
  },
  {
    "id":88,
    "name_en": "Guadeloupe",
    "name_es": "Guadalupe",
    "name": "Guadalupe",
    "sortname": "GP",
    "sortname2": "GLP",
    "latitude": 16.995971,
    "longitude": -62.067641,
    "flag": "🇬🇵",
    "phonecode": 590
  },
  {
    "id":89,
    "name_en": "Guam",
    "name_es": "Guam",
    "name": "Guam",
    "sortname": "GU",
    "sortname2": "GUM",
    "latitude": 13.444304,
    "longitude": 144.793731,
    "flag": "🇬🇺",
    "phonecode": 1671
  },
  {
    "id":90,
    "name_en": "Guatemala",
    "name_es": "Guatemala",
    "name": "Guatemala",
    "sortname": "GT",
    "sortname2": "GTM",
    "latitude": 15.783471,
    "longitude": -90.230759	,
    "flag": "🇬🇹",
    "phonecode": 502
  },
  {
    "id":91,
    "name_en": "Guernsey",
    "name_es": "Guernsey",
    "name": "Guernsey",
    "sortname": "GG",
    "sortname2": "GGY",
    "latitude": 49.465691,
    "longitude": -2.585278	,
    "flag": "🇬🇬",
    "phonecode": 44
  },
  {
    "id":92,
    "name_en": "Guinea",
    "name_es": "Guinea",
    "name": "Guinea",
    "sortname": "GN",
    "sortname2": "GIN",
    "latitude": 9.945587,
    "longitude": -9.696645,
    "flag": "🇬🇳",
    "phonecode": 224
  },
  {
    "id":93,
    "name_en": "Guinea-Bissau",
    "name_es": "Guinea-Bisau",
    "name": "Guinea-Bisau",
    "sortname": "GW",
    "sortname2": "GNB",
    "latitude": 11.803749,
    "longitude": -15.180413,
    "flag": "🇬🇼",
    "phonecode": 245
  },
  {
    "id":94,
    "name_en": "Guyana",
    "name_es": "Guyana",
    "name": "Guyana",
    "sortname": "GY",
    "sortname2": "GUY",
    "latitude": 4.860416,
    "longitude": -58.93018,
    "flag": "🇬🇾",
    "phonecode": 592
  },
  {
    "id":95,
    "name_en": "Haiti",
    "name_es": "Haití",
    "name": "Haití",
    "sortname": "HT",
    "sortname2": "HTI",
    "latitude": 18.971187,
    "longitude": -72.285215,
    "flag": "🇭🇹",
    "phonecode": 509
  },
  {
    "id":96,
    "name_en": "Heard & McDonald Islands",
    "name_es": "Islas Heard y McDonald",
    "name": "Islas Heard y McDonald",
    "sortname": "HM",
    "sortname2": "HMD",
    "latitude": -53.08181,
    "longitude": 73.504158,
    "flag": "🇭🇲",
    "phonecode": 0
  },
  {
    "id":97,
    "name_en": "Honduras",
    "name_es": "Honduras",
    "name": "Honduras",
    "sortname": "HN",
    "sortname2": "HND",
    "latitude": 15.199999,
    "longitude": -86.241905,
    "flag": "🇭🇳",
    "phonecode": 504
  },
  {
    "id":98,
    "name_en": "Hong Kong",
    "name_es": "Hong Kong",
    "name": "Hong Kong",
    "sortname": "HK",
    "sortname2": "HKG",
    "latitude": 22.396428,
    "longitude": 114.109497,
    "flag": "🇭🇰",
    "phonecode": 852
  },
  {
    "id":99,
    "name_en": "Hungary",
    "name_es": "Hungría",
    "name": "Hungría",
    "sortname": "HU",
    "sortname2": "HUN",
    "latitude": 47.162494,
    "longitude": 19.503304,
    "flag": "🇭🇺",
    "phonecode": 36
  },
  {
    "id":100,
    "name_en": "Iceland",
    "name_es": "Islandia",
    "name": "Islandia",
    "sortname": "IS",
    "sortname2": "ISL",
    "latitude": 64.963051,
    "longitude": -19.020835,
    "flag": "🇮🇸",
    "phonecode": 354
  },
  {
    "id":101,
    "name_en": "India",
    "name_es": "India",
    "name": "India",
    "sortname": "IN",
    "sortname2": "IND",
    "latitude": 20.593684,
    "longitude": 78.96288,
    "flag": "🇮🇳",
    "phonecode": 91
  },
  {
    "id":102,
    "name_en": "Indonesia",
    "name_es": "Indonesia",
    "name": "Indonesia",
    "sortname": "ID",
    "sortname2": "IDN",
    "latitude": -6.343194,
    "longitude": 71.876519,
    "flag": "🇮🇩",
    "phonecode": 62
  },
  {
    "id":103,
    "name_en": "Iran, Islamic Republic of",
    "name_es": "Irán",
    "name": "Irán",
    "sortname": "IR",
    "sortname2": "IRN",
    "latitude": 32.427908,
    "longitude": 53.688046,
    "flag": "🇮🇷",
    "phonecode": 98
  },
  {
    "id":104,
    "name_en": "Iraq",
    "name_es": "Iraq",
    "name": "Iraq",
    "sortname": "IQ",
    "sortname2": "IRQ",
    "latitude": 33.223191,
    "longitude": 43.679291,
    "flag": "🇮🇶",
    "phonecode": 964
  },
  {
    "id":105,
    "name_en": "Ireland",
    "name_es": "Irlanda",
    "name": "Irlanda",
    "sortname": "IE",
    "sortname2": "IRL",
    "latitude": 53.41291,
    "longitude": -8.24389,
    "flag": "🇮🇪",
    "phonecode": 353
  },
  {
    "id":106,
    "name_en": "Israel",
    "name_es": "Israel",
    "name": "Israel",
    "sortname": "IL",
    "sortname2": "ISR",
    "latitude": 31.046051,
    "longitude": 34.851612,
    "flag": "🇮🇱",
    "phonecode": 972
  },
  {
    "id":107,
    "name_en": "Italy",
    "name_es": "Italia",
    "name": "Italia",
    "sortname": "IT",
    "sortname2": "ITA",
    "latitude": 41.87194,
    "longitude": 12.56738,
    "flag": "🇮🇹",
    "phonecode": 39
  },
  {
    "id":108,
    "name_en": "Jamaica",
    "name_es": "Jamaica",
    "name": "Jamaica",
    "sortname": "JM",
    "sortname2": "JAM",
    "latitude": 18.109581,
    "longitude": -77.297508,
    "flag": "🇯🇲",
    "phonecode": 1876
  },
  {
    "id":109,
    "name_en": "Japan",
    "name_es": "Japón",
    "name": "Japón",
    "sortname": "JP",
    "sortname2": "JPN",
    "latitude": 36.204824,
    "longitude": 138.252924,
    "flag": "🇯🇵",
    "phonecode": 81
  },
  {
    "id":110,
    "name_en": "Jersey",
    "name_es": "Jersey",
    "name": "Jersey",
    "sortname": "JE",
    "sortname2": "JEY",
    "latitude": 49.214439,
    "longitude": -2.13125,
    "flag": "🇯🇪",
    "phonecode": 44
  },
  {
    "id":111,
    "name_en": "Jordan",
    "name_es": "Jordania",
    "name": "Jordania",
    "sortname": "JO",
    "sortname2": "JOR",
    "latitude": 30.585164,
    "longitude": 36.238414,
    "flag": "🇯🇴",
    "phonecode": 962
  },
  {
    "id":112,
    "name_en": "Kazakhstan",
    "name_es": "Kazajistán",
    "name": "Kazajistán",
    "sortname": "KZ",
    "sortname2": "KAZ",
    "latitude": 48.019573,
    "longitude": 66.923684,
    "flag": "🇰🇿",
    "phonecode": 7
  },
  {
    "id":113,
    "name_en": "Kenya",
    "name_es": "Kenia",
    "name": "Kenia",
    "sortname": "KE",
    "sortname2": "KEN",
    "latitude": -0.023559,
    "longitude": 37.906193,
    "flag": "🇰🇪",
    "phonecode": 254
  },
  {
    "id":114,
    "name_en": "Kiribati",
    "name_es": "Kiribati",
    "name": "Kiribati",
    "sortname": "KI",
    "sortname2": "KIR",
    "latitude": -3.370417,
    "longitude": -168.734039,
    "flag": "🇰🇮",
    "phonecode": 686
  },
  {
    "id":115,
    "name_en": "Korea, Democratic People's Republic of",
    "name_es": "Corea del Norte",
    "name": "Corea del Norte",
    "sortname": "KP",
    "sortname2": "PRK",
    "latitude": 40.339852,
    "longitude": 127.510093,
    "flag": "🇰🇵",
    "phonecode": 850
  },
  {
    "id":116,
    "name_en": "Korea, Republic of",
    "name_es": "Corea del Sur",
    "name": "Corea del Sur",
    "sortname": "KR",
    "sortname2": "KOR",
    "latitude": 35.907757,
    "longitude": 127.766922,
    "flag": "🇰🇷",
    "phonecode": 82
  },
  {
    "id":117,
    "name_en": "Kuwait",
    "name_es": "Kuwait",
    "name": "Kuwait",
    "sortname": "KW",
    "sortname2": "KWT",
    "latitude": 29.31166,
    "longitude": 47.481766,
    "flag": "🇰🇼",
    "phonecode": 965
  },
  {
    "id":118,
    "name_en": "Kyrgyzstan",
    "name_es": "Kirguistán",
    "name": "Kirguistán",
    "sortname": "KG",
    "sortname2": "KGZ",
    "latitude": 41.1355493,
    "longitude": 70.2500128,
    "flag": "🇰🇬",
    "phonecode": 996
  },
  {
    "id":119,
    "name_en": "Lao People's Democratic Republic",
    "name_es": "Laos",
    "name": "Laos",
    "sortname": "LA",
    "sortname2": "LAO",
    "latitude": 41.20438,
    "longitude": 74.766098,
    "flag": "🇱🇦",
    "phonecode": 856
  },
  {
    "id":120,
    "name_en": "Latvia",
    "name_es": "Letonia",
    "name": "Letonia",
    "sortname": "LV",
    "sortname2": "LVA",
    "latitude": 56.879635,
    "longitude": 24.603189,
    "flag": "🇱🇻",
    "phonecode": 371
  },
  {
    "id":121,
    "name_en": "Lebanon",
    "name_es": "Líbano",
    "name": "Líbano",
    "sortname": "LB",
    "sortname2": "LBN",
    "latitude": 33.854721,
    "longitude": 35.862285,
    "flag": "🇱🇧",
    "phonecode": 961
  },
  {
    "id":122,
    "name_en": "Lesotho",
    "name_es": "Lesoto",
    "name": "Lesoto",
    "sortname": "LS",
    "sortname2": "LSO",
    "latitude": -29.609988,
    "longitude": 28.233608,
    "flag": "🇱🇸",
    "phonecode": 266
  },
  {
    "id":123,
    "name_en": "Liberia",
    "name_es": "Liberia",
    "name": "Liberia",
    "sortname": "LR",
    "sortname2": "LBR",
    "latitude": 6.428055,
    "longitude": -9.429499,
    "flag": "🇱🇷",
    "phonecode": 231
  },
  {
    "id":124,
    "name_en": "Libyan Arab Jamahiriya",
    "name_es": "Libia",
    "name": "Libia",
    "sortname": "LY",
    "sortname2": "LBY",
    "latitude": 26.3351,
    "longitude": 17.228331,
    "flag": "🇱🇾",
    "phonecode": 218
  },
  {
    "id":125,
    "name_en": "Liechtenstein",
    "name_es": "Liechtenstein",
    "name": "Liechtenstein",
    "sortname": "LI",
    "sortname2": "LIE",
    "latitude": 47.166,
    "longitude": 9.555373,
    "flag": "🇱🇮",
    "phonecode": 423
  },
  {
    "id":126,
    "name_en": "Lithuania",
    "name_es": "Lituania",
    "name": "Lituania",
    "sortname": "LT",
    "sortname2": "LTU",
    "latitude": 55.169438,
    "longitude": 23.881275,
    "flag": "🇱🇹",
    "phonecode": 370
  },
  {
    "id":127,
    "name_en": "Luxembourg",
    "name_es": "Luxemburgo",
    "name": "Luxemburgo",
    "sortname": "LU",
    "sortname2": "LUX",
    "latitude": 49.815273,
    "longitude": 6.129583,
    "flag": "🇱🇺",
    "phonecode": 352
  },
  {
    "id":128,
    "name_en": "Macao",
    "name_es": "Macao",
    "name": "Macao",
    "sortname": "MO",
    "sortname2": "MAC",
    "latitude": 22.198745,
    "longitude": 113.543873,
    "flag": "🇲🇴",
    "phonecode": 853
  },
  {
    "id":129,
    "name_en": "The Former Yugoslav Republic of Macedonia",
    "name_es": "República de Macedonia",
    "name": "República de Macedonia",
    "sortname": "MK",
    "sortname2": "MKD",
    "latitude": 41.608635,
    "longitude": 21.745275,
    "flag": "🇲🇰",
    "phonecode": 389
  },
  {
    "id":130,
    "name_en": "Madagascar",
    "name_es": "Madagascar",
    "name": "Madagascar",
    "sortname": "MG",
    "sortname2": "MDG",
    "latitude": -18.766947,
    "longitude": 46.869107,
    "flag": "🇲🇬",
    "phonecode": 261
  },
  {
    "id":131,
    "name_en": "Malawi",
    "name_es": "Malaui",
    "name": "Malaui",
    "sortname": "MW",
    "sortname2": "MWI",
    "latitude": -13.254308,
    "longitude": 34.301525,
    "flag": "🇲🇼",
    "phonecode": 265
  },
  {
    "id":132,
    "name_en": "Malaysia",
    "name_es": "Malasia",
    "name": "Malasia",
    "sortname": "MY",
    "sortname2": "MYS",
    "latitude": 4.210484,
    "longitude": 101.975766,
    "flag": "🇲🇾",
    "phonecode": 60
  },
  {
    "id":133,
    "name_en": "Maldives",
    "name_es": "Maldivas",
    "name": "Maldivas",
    "sortname": "MV",
    "sortname2": "MDV",
    "latitude": 3.202778,
    "longitude": 73.22068,
    "flag": "🇲🇻",
    "phonecode": 960
  },
  {
    "id":134,
    "name_en": "Mali",
    "name_es": "Malí",
    "name": "Malí",
    "sortname": "ML",
    "sortname2": "MLI",
    "latitude": 17.570692,
    "longitude": -3.996166,
    "flag": "🇲🇱",
    "phonecode": 223
  },
  {
    "id":135,
    "name_en": "Malta",
    "name_es": "Malta",
    "name": "Malta",
    "sortname": "MT",
    "sortname2": "MLT",
    "latitude": 35.937496,
    "longitude": 14.375416,
    "flag": "🇲🇹",
    "phonecode": 356
  },
  {
    "id":136,
    "name_en": "Isle of Man",
    "name_es": "Isla de Man",
    "name": "Isla de Man",
    "sortname": "IM",
    "sortname2": "IMN",
    "latitude": 54.236107,
    "longitude": -4.548056,
    "flag": "🇮🇲",
    "phonecode": 44
  },
  {
    "id":137,
    "name_en": "Marshall Islands",
    "name_es": "Islas Marshall",
    "name": "Islas Marshall",
    "sortname": "MH",
    "sortname2": "MHL",
    "latitude": 7.131474,
    "longitude": 171.184478,
    "flag": "🇲🇭",
    "phonecode": 692
  },
  {
    "id":138,
    "name_en": "Martinique",
    "name_es": "Martinica",
    "name": "Martinica",
    "sortname": "MQ",
    "sortname2": "MTQ",
    "latitude": 14.641528,
    "longitude": -61.024174,
    "flag": "🇲🇶",
    "phonecode": 596
  },
  {
    "id":139,
    "name_en": "Mauritania",
    "name_es": "Mauritania",
    "name": "Mauritania",
    "sortname": "MR",
    "sortname2": "MRT",
    "latitude": 21.00789,
    "longitude": -10.940835,
    "flag": "🇲🇷",
    "phonecode": 222
  },
  {
    "id":140,
    "name_en": "Mauritius",
    "name_es": "Mauricio",
    "name": "Mauricio",
    "sortname": "MU",
    "sortname2": "MUS",
    "latitude": -20.348404,
    "longitude": 57.552152,
    "flag": "🇲🇺",
    "phonecode": 230
  },
  {
    "id":141,
    "name_en": "Mayotte",
    "name_es": "Mayotte",
    "name": "Mayotte",
    "sortname": "YT",
    "sortname2": "MYT",
    "latitude": -12.8275,
    "longitude": 45.166244,
    "flag": "🇾🇹",
    "phonecode": 269
  },
  {
    "id":142,
    "name_en": "Mexico",
    "name_es": "México",
    "name": "México",
    "sortname": "MX",
    "sortname2": "MEX",
    "latitude": 23.634501,
    "longitude": -102.552784,
    "flag": "🇲🇽",
    "phonecode": 52
  },
  {
    "id":143,
    "name_en": "Micronesia",
    "name_es": "Micronesia",
    "name": "Micronesia",
    "sortname": "FM",
    "sortname2": "FSM",
    "latitude": 7.425554,
    "longitude": 150.550812,
    "flag": "🇫🇲",
    "phonecode": 691
  },
  {
    "id":144,
    "name_en": "Republic of Moldova",
    "name_es": "Moldavia",
    "name": "Moldavia",
    "sortname": "MD",
    "sortname2": "MDA",
    "latitude": 47.411631,
    "longitude": 28.369885,
    "flag": "🇲🇩",
    "phonecode": 373
  },
  {
    "id":145,
    "name_en": "Monaco",
    "name_es": "Monaco",
    "name": "Monaco",
    "sortname": "MC",
    "sortname2": "MCO",
    "latitude": 43.750298,
    "longitude": 7.412841,
    "flag": "🇲🇨",
    "phonecode": 377
  },
  {
    "id":146,
    "name_en": "Mongolia",
    "name_es": "Mongolia",
    "name": "Mongolia",
    "sortname": "MN",
    "sortname2": "MNG",
    "latitude": 46.862496,
    "longitude": 103.846656,
    "flag": "🇲🇳",
    "phonecode": 976
  },
  {
    "id":147,
    "name_en": "Montserrat",
    "name_es": "Montserrat",
    "name": "Montserrat",
    "sortname": "MS",
    "sortname2": "MSR",
    "latitude": 16.742498,
    "longitude": -62.187366,
    "flag": "🇲🇸",
    "phonecode": 1664
  },
  {
    "id":148,
    "name_en": "Morocco",
    "name_es": "Marruecos",
    "name": "Marruecos",
    "sortname": "MA",
    "sortname2": "MAR",
    "latitude": 31.791702,
    "longitude": -7.09262,
    "flag": "🇲🇦",
    "phonecode": 212
  },
  {
    "id":149,
    "name_en": "Mozambique",
    "name_es": "Mozambique",
    "name": "Mozambique",
    "sortname": "MZ",
    "sortname2": "MOZ",
    "latitude": -18.665695	,
    "longitude": 35.529562,
    "flag": "🇲🇿",
    "phonecode": 258
  },
  {
    "id":150,
    "name_en": "Myanmar",
    "name_es": "Birmania",
    "name": "Birmania",
    "sortname": "MM",
    "sortname2": "MMR",
    "latitude": 21.913965,
    "longitude": 95.956223,
    "flag": "🇲🇲",
    "phonecode": 95
  },
  {
    "id":151,
    "name_en": "Namibia",
    "name_es": "Namibia",
    "name": "Namibia",
    "sortname": "NA",
    "sortname2": "NAM",
    "latitude": -22.95764,
    "longitude": 18.49041,
    "flag": "🇳🇦",
    "phonecode": 264
  },
  {
    "id":152,
    "name_en": "Nauru",
    "name_es": "Nauru",
    "name": "Nauru",
    "sortname": "NR",
    "sortname2": "NRU",
    "latitude": -0.522778	,
    "longitude": 166.931503,
    "flag": "🇳🇷",
    "phonecode": 674
  },
  {
    "id":153,
    "name_en": "Nepal",
    "name_es": "Nepal",
    "name": "Nepal",
    "sortname": "NP",
    "sortname2": "NPL",
    "latitude": 28.394857,
    "longitude": 84.124008,
    "flag": "🇳🇵",
    "phonecode": 977
  },
  {
    "id":154,
    "name_en": "Netherlands Antilles",
    "name_es": "Antillas Holandesas",
    "name": "Antillas Holandesas",
    "sortname": "AN",
    "sortname2": "ANT",
    "latitude": 12.226079,
    "longitude": -69.060087	,
    "flag": "🇧🇶",
    "phonecode": 599
  },
  {
    "id":155,
    "name_en": "Netherlands",
    "name_es": "Holanda",
    "name": "Holanda",
    "sortname": "NL",
    "sortname2": "NLD",
    "latitude": 52.132633,
    "longitude": 5.291266,
    "flag": "🇳🇱",
    "phonecode": 31
  },
  {
    "id":156,
    "name_en": "New Caledonia",
    "name_es": "Nueva Caledonia",
    "name": "Nueva Caledonia",
    "sortname": "NC",
    "sortname2": "NCL",
    "latitude": -20.904305,
    "longitude": 165.618042,
    "flag": "🇳🇨",
    "phonecode": 687
  },
  {
    "id":157,
    "name_en": "New Zealand",
    "name_es": "Nueva Zelanda",
    "name": "Nueva Zelanda",
    "sortname": "NZ",
    "sortname2": "NZL",
    "latitude": -40.900557,
    "longitude": 174.885971,
    "flag": "🇳🇿",
    "phonecode": 64
  },
  {
    "id":158,
    "name_en": "Nicaragua",
    "name_es": "Nicaragua",
    "name": "Nicaragua",
    "sortname": "NI",
    "sortname2": "NIC",
    "latitude": 12.865416,
    "longitude": -85.207229,
    "flag": "🇳🇮",
    "phonecode": 505
  },
  {
    "id":159,
    "name_en": "Niger",
    "name_es": "Niger",
    "name": "Niger",
    "sortname": "NE",
    "sortname2": "NER",
    "latitude": 17.607789,
    "longitude": 8.081666,
    "flag": "🇳🇪",
    "phonecode": 227
  },
  {
    "id":160,
    "name_en": "Nigeria",
    "name_es": "Nigeria",
    "name": "Nigeria",
    "sortname": "NG",
    "sortname2": "NGA",
    "latitude": 9.081999,
    "longitude": 8.675277,
    "flag": "🇳🇬",
    "phonecode": 234
  },
  {
    "id":161,
    "name_en": "Niue",
    "name_es": "Niue",
    "name": "Niue",
    "sortname": "NU",
    "sortname2": "NIU",
    "latitude": -19.054445,
    "longitude": -169.867233,
    "flag": "🇳🇺",
    "phonecode": 683
  },
  {
    "id":162,
    "name_en": "NorfolkIsland",
    "name_es": "Isla Norfolk",
    "name": "Isla Norfolk",
    "sortname": "NF",
    "sortname2": "NFK",
    "latitude": -29.040835,
    "longitude": 167.954712,
    "flag": "🇳🇫",
    "phonecode": 672
  },
  {
    "id":163,
    "name_en": "Northern Mariana Islands",
    "name_es": "Islas Marianas del Norte",
    "name": "Islas Marianas del Norte",
    "sortname": "MP",
    "sortname2": "MIP",
    "latitude": 17.33083,
    "longitude": 145.38469,
    "flag": "🇲🇵",
    "phonecode": 1670
  },
  {
    "id":164,
    "name_en": "Norway",
    "name_es": "Noruega",
    "name": "Noruega",
    "sortname": "NO",
    "sortname2": "NOR",
    "latitude": 60.472024,
    "longitude": 8.468946,
    "flag": "🇳🇴",
    "phonecode": 47
  },
  {
    "id":165,
    "name_en": "Oman",
    "name_es": "Omán",
    "name": "Omán",
    "sortname": "OM",
    "sortname2": "OMN",
    "latitude": 21.512583,
    "longitude": 55.923255,
    "flag": "🇴🇲",
    "phonecode": 968
  },
  {
    "id":166,
    "name_en": "Pakistan",
    "name_es": "Pakistán",
    "name": "Pakistán",
    "sortname": "PK",
    "sortname2": "PAK",
    "latitude": 30.375321,
    "longitude": 69.345116,
    "flag": "🇵🇰",
    "phonecode": 92
  },
  {
    "id":167,
    "name_en": "Palau",
    "name_es": "Palaos",
    "name": "Palaos",
    "sortname": "PW",
    "sortname2": "PLW",
    "latitude": 7.51498,
    "longitude": 134.58252,
    "flag": "🇵🇼",
    "phonecode": 680
  },
  {
    "id":168,
    "name_en": "State of Palestine",
    "name_es": "Estado de Palestina",
    "name": "Estado de Palestina",
    "sortname": "PS",
    "sortname2": "PSE",
    "latitude": 31.952162,
    "longitude": 35.233154,
    "flag": "🇵🇸",
    "phonecode": 970
  },
  {
    "id":169,
    "name_en": "Panama",
    "name_es": "Panamá",
    "name": "Panamá",
    "sortname": "PA",
    "sortname2": "PAN",
    "latitude": 8.537981,
    "longitude": -80.782127,
    "flag": "🇵🇦",
    "phonecode": 507
  },
  {
    "id":170,
    "name_en": "Papua New Guinea",
    "name_es": "Papúa Nueva Guinea",
    "name": "Papúa Nueva Guinea",
    "sortname": "PG",
    "sortname2": "PNG",
    "latitude": -6.314993,
    "longitude": 143.95555,
    "flag": "🇵🇬",
    "phonecode": 675
  },
  {
    "id":171,
    "name_en": "Paraguay",
    "name_es": "Paraguay",
    "name": "Paraguay",
    "sortname": "PY",
    "sortname2": "PRY",
    "latitude": -23.442503,
    "longitude": -58.443832,
    "flag": "🇵🇾",
    "phonecode": 595
  },
  {
    "id":172,
    "name_en": "Peru",
    "name_es": "Perú",
    "name": "Perú",
    "sortname": "PE",
    "sortname2": "PER",
    "latitude": -9.189967,
    "longitude": -75.015152,
    "flag": "🇵🇪",
    "phonecode": 51
  },
  {
    "id":173,
    "name_en": "Philippines",
    "name_es": "Filipinas",
    "name": "Filipinas",
    "sortname": "PH",
    "sortname2": "PHL",
    "latitude": 12.879721,
    "longitude": 121.774017,
    "flag": "🇵🇭",
    "phonecode": 63
  },
  {
    "id":174,
    "name_en": "Pitcairn Islands",
    "name_es": "Islas Pitcairn",
    "name": "Islas Pitcairn",
    "sortname": "PN",
    "sortname2": "PCN",
    "latitude": -24.703615,
    "longitude": -127.439308,
    "flag": "🇵🇳",
    "phonecode": 0
  },
  {
    "id":175,
    "name_en": "Poland",
    "name_es": "Polonia",
    "name": "Polonia",
    "sortname": "PL",
    "sortname2": "POL",
    "latitude": 51.919438,
    "longitude": 19.145136,
    "flag": "🇵🇱",
    "phonecode": 48
  },
  {
    "id":176,
    "name_en": "Portugal",
    "name_es": "Portugal",
    "name": "Portugal",
    "sortname": "PT",
    "sortname2": "PRT",
    "latitude": 39.399872,
    "longitude": -8.224454,
    "flag": "🇵🇹",
    "phonecode": 351
  },
  {
    "id":177,
    "name_en": "Puerto Rico",
    "name_es": "Puerto Rico",
    "name": "Puerto Rico",
    "sortname": "PR",
    "sortname2": "PRI",
    "latitude": 18.220833,
    "longitude": -66.590149,
    "flag": "🇵🇷",
    "phonecode": 1787
  },
  {
    "id":178,
    "name_en": "Qatar",
    "name_es": "Catar",
    "name": "Catar",
    "sortname": "QA",
    "sortname2": "QAT",
    "latitude": 25.354826,
    "longitude": 51.183884,
    "flag": "🇶🇦",
    "phonecode": 974
  },
  {
    "id":179,
    "name_en": "Reunion",
    "name_es": "Réunion",
    "name": "Réunion",
    "sortname": "RE",
    "sortname2": "REU",
    "latitude": -21.115141,
    "longitude": 55.536384,
    "flag": "🇷🇪",
    "phonecode": 262
  },
  {
    "id":180,
    "name_en": "Romania",
    "name_es": "Rumania",
    "name": "Rumania",
    "sortname": "RO",
    "sortname2": "ROU",
    "latitude": 45.943161,
    "longitude": 24.96676,
    "flag": "🇷🇴",
    "phonecode": 40
  },
  {
    "id":181,
    "name_en": "Russia",
    "name_es": "Rusia",
    "name": "Rusia",
    "sortname": "RU",
    "sortname2": "RUS",
    "latitude": 61.52401,
    "longitude": 105.318756,
    "flag": "🇷🇺",
    "phonecode": 70
  },
  {
    "id":182,
    "name_en": "Rwanda",
    "name_es": "Ruanda",
    "name": "Ruanda",
    "sortname": "RW",
    "sortname2": "RWA",
    "latitude": -1.940278	,
    "longitude": 29.873888,
    "flag": "🇷🇼",
    "phonecode": 250
  },
  {
    "id":183,
    "name_en": "Saint Helena, Ascension and Tristan Da Cunha",
    "name_es": "Santa Elena, Ascensión y Tristán de Acuña",
    "name": "Santa Elena, Ascensión y Tristán de Acuña",
    "sortname": "SH",
    "sortname2": "SHN",
    "latitude": -24.143474,
    "longitude": -10.030696,
    "flag": "🇸🇭",
    "phonecode": 290
  },
  {
    "id":184,
    "name_en": "Saint Kitts and Nevis",
    "name_es": "San Cristóbal y Nieves",
    "name": "San Cristóbal y Nieves",
    "sortname": "KN",
    "sortname2": "KNA",
    "latitude": 17.357822,
    "longitude": -62.782998,
    "flag": "🇰🇳",
    "phonecode": 1869
  },
  {
    "id":185,
    "name_en": "Saint Lucia",
    "name_es": "Santa Lucía",
    "name": "Santa Lucía",
    "sortname": "LC",
    "sortname2": "LCA",
    "latitude": 13.909444,
    "longitude": -60.978893	,
    "flag": "🇱🇨",
    "phonecode": 1758
  },
  {
    "id":186,
    "name_en": "Saint Pierre and Miquelon",
    "name_es": "San Pedro y Miquelon",
    "name": "San Pedro y Miquelon",
    "sortname": "PM",
    "sortname2": "SPM",
    "latitude": 17.33083,
    "longitude": 145.38469,
    "flag": "🇵🇲",
    "phonecode": 508
  },
  {
    "id":187,
    "name_en": "Saint Vincent and the Grenadines",
    "name_es": "San Vicente y las Granadinas",
    "name": "San Vicente y las Granadinas",
    "sortname": "VC",
    "sortname2": "VCT",
    "latitude": 12.984305,
    "longitude": -61.287228,
    "flag": "🇻🇨",
    "phonecode": 1784
  },
  {
    "id":188,
    "name_en": "Samoa",
    "name_es": "Samoa",
    "name": "Samoa",
    "sortname": "WS",
    "sortname2": "WSM",
    "latitude": -13.759029,
    "longitude": -172.104629,
    "flag": "🇼🇸",
    "phonecode": 684
  },
  {
    "id":189,
    "name_en": "San Marino",
    "name_es": "San Marino",
    "name": "San Marino",
    "sortname": "SM",
    "sortname2": "SMR",
    "latitude": 43.94236,
    "longitude": 12.457777,
    "flag": "🇸🇲",
    "phonecode": 378
  },
  {
    "id":190,
    "name_en": "Sao Tome and Principe",
    "name_es": " Santo Tomé y Príncipe",
    "name": " Santo Tomé y Príncipe",
    "sortname": "ST",
    "sortname2": "STP",
    "latitude": 0.18636,
    "longitude": 6.613081,
    "flag": "🇸🇹",
    "phonecode": 239
  },
  {
    "id":191,
    "name_en": "Saudi Arabia",
    "name_es": "Arabia Saudita",
    "name": "Arabia Saudita",
    "sortname": "SA",
    "sortname2": "SAU",
    "latitude": 23.885942,
    "longitude": 45.079162,
    "flag": "🇸🇦",
    "phonecode": 966
  },
  {
    "id":192,
    "name_en": "Senegal",
    "name_es": "Senegal",
    "name": "Senegal",
    "sortname": "SN",
    "sortname2": "SEN",
    "latitude": 14.497401,
    "longitude": -14.452362,
    "flag": "🇸🇳",
    "phonecode": 221
  },
  {
    "id":193,
    "name_en": "Serbia",
    "name_es": "Serbia",
    "name": "Serbia",
    "sortname": "RS",
    "sortname2": "SRB",
    "latitude": 44.016521,
    "longitude": 21.005859,
    "flag": "🇷🇸",
    "phonecode": 381
  },
  {
    "id":194,
    "name_en": "Seychelles",
    "name_es": "Seychelles",
    "name": "Seychelles",
    "sortname": "SC",
    "sortname2": "SYC",
    "latitude": -4.679574,
    "longitude": 55.491977,
    "flag": "🇸🇨",
    "phonecode": 248
  },
  {
    "id":195,
    "name_en": "Sierra Leone",
    "name_es": "Sierra Leona",
    "name": "Sierra Leona",
    "sortname": "SL",
    "sortname2": "SLE",
    "latitude": 8.460555,
    "longitude": -11.779889	,
    "flag": "🇸🇱",
    "phonecode": 232
  },
  {
    "id":196,
    "name_en": "Singapore",
    "name_es": "Singapur",
    "name": "Singapur",
    "sortname": "SG",
    "sortname2": "SGP",
    "latitude": 1.352083,
    "longitude": 103.819836,
    "flag": "🇸🇬",
    "phonecode": 65
  },
  {
    "id":197,
    "name_en": "Slovakia",
    "name_es": "Eslovaquia",
    "name": "Eslovaquia",
    "sortname": "SK",
    "sortname2": "SVK",
    "latitude": 48.669026,
    "longitude": 19.699024,
    "flag": "🇸🇮",
    "phonecode": 421
  },
  {
    "id":198,
    "name_en": "Slovenia",
    "name_es": "Eslovenia",
    "name": "Eslovenia",
    "sortname": "SI",
    "sortname2": "SVN",
    "latitude": 46.151241,
    "longitude": 14.995463,
    "flag": "🇸🇰",
    "phonecode": 386
  },
  {
    "id":199,
    "name_en": "Smaller Territories of the UK",
    "name_es": "Pequeñas Islas del Reino Unido",
    "name": "Pequeñas Islas del Reino Unido",
    "sortname": "XG",
    "sortname2": "SUK",
    "latitude": 0,
    "longitude": 0,
    "flag": "🇬🇧",
    "phonecode": 44
  },
  {
    "id":200,
    "name_en": "Solomon Islands",
    "name_es": "Islas Salomón",
    "name": "Islas Salomón",
    "sortname": "SB",
    "sortname2": "SLB",
    "latitude": -9.64571,
    "longitude": 160.156194,
    "flag": "🇸🇧",
    "phonecode": 677
  },
  {
    "id":201,
    "name_en": "Somalia",
    "name_es": "Somalia",
    "name": "Somalia",
    "sortname": "SO",
    "sortname2": "SOM",
    "latitude": 5.152149,
    "longitude": 46.199616,
    "flag": "🇸🇴",
    "phonecode": 252
  },
  {
    "id":202,
    "name_en": "South Africa",
    "name_es": "Sudáfrica",
    "name": "Sudáfrica",
    "sortname": "ZA",
    "sortname2": "ZAF",
    "latitude": -30.559482,
    "longitude": 22.937506,
    "flag": "🇿🇦",
    "phonecode": 27
  },
  {
    "id":203,
    "name_en": "South Georgia & South Sandwich Islands",
    "name_es": "Georgia del Sur e Islas Sandwich del Sur",
    "name": "Georgia del Sur e Islas Sandwich del Sur",
    "sortname": "GS",
    "sortname2": "SGS",
    "latitude": -54.429579,
    "longitude": -36.587909,
    "flag": "🇬🇸",
    "phonecode": 0
  },
  {
    "id":204,
    "name_en": "South Sudan",
    "name_es": "Sudán del Sur",
    "name": "Sudán del Sur",
    "sortname": "SS",
    "sortname2": "SSD",
    "latitude": 7.7660983,
    "longitude": 20.6491937,
    "flag": "🇸🇸",
    "phonecode": 211
  },
  {
    "id":205,
    "name_en": "Spain",
    "name_es": "España",
    "name": "España",
    "sortname": "ES",
    "sortname2": "ESP",
    "latitude": 40.463667,
    "longitude": -3.74922,
    "flag": "🇪🇸",
    "phonecode": 34
  },
  {
    "id":206,
    "name_en": "Sri Lanka",
    "name_es": "Sri Lanka",
    "name": "Sri Lanka",
    "sortname": "LK",
    "sortname2": "LKA",
    "latitude": 7.873054,
    "longitude": 80.771797,
    "flag": "🇱🇰",
    "phonecode": 94
  },
  {
    "id":207,
    "name_en": "Sudan",
    "name_es": "Sudán",
    "name": "Sudán",
    "sortname": "SD",
    "sortname2": "SDN",
    "latitude": 12.862807,
    "longitude": 30.217636,
    "flag": "🇸🇩",
    "phonecode": 249
  },
  {
    "id":208,
    "name_en": "Suriname",
    "name_es": "Surinam",
    "name": "Surinam",
    "sortname": "SR",
    "sortname2": "SUR",
    "latitude": 3.919305,
    "longitude": -56.027783,
    "flag": "🇸🇷",
    "phonecode": 597
  },
  {
    "id":209,
    "name_en": "Svalbard and Jan Mayen",
    "name_es": "Islas Svalbard y Jan Mayen",
    "name": "Islas Svalbard y Jan Mayen",
    "sortname": "SJ",
    "sortname2": "SJM",
    "latitude": 77.553604,
    "longitude": 23.670272,
    "flag": "🇸🇯",
    "phonecode": 47
  },
  {
    "id":210,
    "name_en": "Swaziland",
    "name_es": "Suazilandia",
    "name": "Suazilandia",
    "sortname": "SZ",
    "sortname2": "SWZ",
    "latitude": -26.522503,
    "longitude": 31.465866,
    "flag": "🇸🇿",
    "phonecode": 268
  },
  {
    "id":211,
    "name_en": "Sweden",
    "name_es": "Suecia",
    "name": "Suecia",
    "sortname": "SE",
    "sortname2": "SWE",
    "latitude": 60.128161,
    "longitude": 18.643501,
    "flag": "🇸🇪",
    "phonecode": 46
  },
  {
    "id":212,
    "name_en": "Switzerland",
    "name_es": "Suiza",
    "name": "Suiza",
    "sortname": "CH",
    "sortname2": "CHE",
    "latitude": 46.818188,
    "longitude": 8.227512,
    "flag": "🇨🇭",
    "phonecode": 41
  },
  {
    "id":213,
    "name_en": "Syrian",
    "name_es": "Siria",
    "name": "Siria",
    "sortname": "SY",
    "sortname2": "SYR",
    "latitude": 34.802075,
    "longitude": 38.996815,
    "flag": "🇸🇾",
    "phonecode": 963
  },
  {
    "id":214,
    "name_en": "Taiwan, Province of China",
    "name_es": "Taiwán",
    "name": "Taiwán",
    "sortname": "TW",
    "sortname2": "TWN",
    "latitude": 23.69781,
    "longitude": 120.960515,
    "flag": "🇹🇼",
    "phonecode": 886
  },
  {
    "id":215,
    "name_en": "Tayikistan",
    "name_es": "Tayikistán",
    "name": "Tayikistán",
    "sortname": "TJ",
    "sortname2": "TJK",
    "latitude": 38.861034,
    "longitude": 71.276093,
    "flag": "🇹🇯",
    "phonecode": 992
  },
  {
    "id":216,
    "name_en": "Tanzania",
    "name_es": "Tanzania",
    "name": "Tanzania",
    "sortname": "TZ",
    "sortname2": "TZA",
    "latitude": -6.369028,
    "longitude": 34.888822,
    "flag": "🇹🇿",
    "phonecode": 255
  },
  {
    "id":217,
    "name_en": "Thailand",
    "name_es": "Tailandia",
    "name": "Tailandia",
    "sortname": "TH",
    "sortname2": "THA",
    "latitude": 15.870032,
    "longitude": 100.992541,
    "flag": "🇹🇭",
    "phonecode": 66
  },
  {
    "id":218,
    "name_en": "Togo",
    "name_es": "Togo",
    "name": "Togo",
    "sortname": "TG",
    "sortname2": "TGO",
    "latitude": 8.619543,
    "longitude": 0.824782,
    "flag": "🇹🇬",
    "phonecode": 228
  },
  {
    "id":219,
    "name_en": "Tokelau",
    "name_es": "Tokelau",
    "name": "Tokelau",
    "sortname": "TK",
    "sortname2": "TKL",
    "latitude": -8.967363,
    "longitude": -171.855881,
    "flag": "🇹🇰",
    "phonecode": 690
  },
  {
    "id":220,
    "name_en": "Tonga",
    "name_es": "Tonga",
    "name": "Tonga",
    "sortname": "TO",
    "sortname2": "TON",
    "latitude": -21.178986,
    "longitude": -175.198242,
    "flag": "🇹🇴",
    "phonecode": 676
  },
  {
    "id":221,
    "name_en": "Trinidad and Tobago",
    "name_es": "Trinidad y Tobago",
    "name": "Trinidad y Tobago",
    "sortname": "TT",
    "sortname2": "TTO",
    "latitude": 10.691803,
    "longitude": -61.222503,
    "flag": "🇹🇹",
    "phonecode": 1868
  },
  {
    "id":222,
    "name_en": "Tunisia",
    "name_es": "Túnez",
    "name": "Túnez",
    "sortname": "TN",
    "sortname2": "TUN",
    "latitude": 33.886917,
    "longitude": 9.537499,
    "flag": "🇹🇳",
    "phonecode": 216
  },
  {
    "id":223,
    "name_en": "Turkey",
    "name_es": "Turquía",
    "name": "Turquía",
    "sortname": "TR",
    "sortname2": "TUR",
    "latitude": 38.963745,
    "longitude": 35.243322,
    "flag": "🇹🇷",
    "phonecode": 90
  },
  {
    "id":224,
    "name_en": "Turkmenistan",
    "name_es": "Turkmenistán",
    "name": "Turkmenistán",
    "sortname": "TM",
    "sortname2": "TKM",
    "latitude": 38.969719,
    "longitude": 59.556278,
    "flag": "🇹🇲",
    "phonecode": 7370
  },
  {
    "id":225,
    "name_en": "Turks and Caicos Islands",
    "name_es": "Islas Turcas y Caicos",
    "name": "Islas Turcas y Caicos",
    "sortname": "TC",
    "sortname2": "TCA",
    "latitude": 21.694025,
    "longitude": -71.797928,
    "flag": "🇹🇨",
    "phonecode": 1649
  },
  {
    "id":226,
    "name_en": "Tuvalu",
    "name_es": "Tuvalu",
    "name": "Tuvalu",
    "sortname": "TV",
    "sortname2": "TUV",
    "latitude": -7.109535,
    "longitude": 177.64933,
    "flag": "🇹🇻",
    "phonecode": 688
  },
  {
    "id":227,
    "name_en": "Uganda",
    "name_es": "Uganda",
    "name": "Uganda",
    "sortname": "UG",
    "sortname2": "UGA",
    "latitude": 1.373333,
    "longitude": 32.290275,
    "flag": "🇺🇬",
    "phonecode": 256
  },
  {
    "id":228,
    "name_en": "Ukraine",
    "name_es": "Ucrania",
    "name": "Ucrania",
    "sortname": "UA",
    "sortname2": "UKR",
    "latitude": 48.379433,
    "longitude": 31.16558,
    "flag": "🇺🇦",
    "phonecode": 380
  },
  {
    "id":229,
    "name_en": "United Arab Emirates",
    "name_es": "Emiratos Árabes Unidos",
    "name": "Emiratos Árabes Unidos",
    "sortname": "AE",
    "sortname2": "ARE",
    "latitude": 23.424076,
    "longitude": 53.847818,
    "flag": "🇦🇪",
    "phonecode": 971
  },
  {
    "id":230,
    "name_en": "United Kingdom",
    "name_es": "Reino Unido",
    "name": "Reino Unido",
    "sortname": "GB",
    "sortname2": "GBR",
    "latitude": 55.378051,
    "longitude": -3.435973,
    "flag": "🇬🇧",
    "phonecode": 44
  },
  {
    "id":231,
    "name_en": "United States",
    "name_es": "Estados Unidos",
    "name": "Estados Unidos",
    "sortname": "US",
    "sortname2": "USA",
    "latitude": 37.09024,
    "longitude": -95.712891,
    "flag": "🇺🇸",
    "phonecode": 1
  },
  {
    "id":232,
    "name_en": "United States Minor Outlying Islands",
    "name_es": "",
    "name": "",
    "sortname": "UM",
    "sortname2": "USM",
    "latitude": 19.2794632,
    "longitude": 166.5967,
    "flag": "🇺🇸",
    "phonecode": 1
  },
  {
    "id":233,
    "name_en": "Uruguay",
    "name_es": "Uruguay",
    "name": "Uruguay",
    "sortname": "UY",
    "sortname2": "URY",
    "latitude": -32.522779,
    "longitude": -55.765835,
    "flag": "🇺🇾",
    "phonecode": 598
  },
  {
    "id":234,
    "name_en": "Uzbekistan",
    "name_es": "Uzbekistán",
    "name": "Uzbekistán",
    "sortname": "UZ",
    "sortname2": "UZB",
    "latitude": 41.377491,
    "longitude": 64.585262,
    "flag": "🇺🇿",
    "phonecode": 998
  },
  {
    "id":235,
    "name_en": "Vanuatu",
    "name_es": "Vanuatu",
    "name": "Vanuatu",
    "sortname": "VU",
    "sortname2": "VUT",
    "latitude": -15.376706,
    "longitude": 166.959158,
    "flag": "🇻🇺",
    "phonecode": 678
  },

  {
    "id":236,
    "name_en": "Vatican City State (Holy See)",
    "name_es": "Ciudad del Vaticano",
    "name": "Ciudad del Vaticano",
    "sortname": "VA",
    "sortname2": "VAT",
    "latitude": 41.902916,
    "longitude": 12.453389,
    "flag": "🇻🇦",
    "phonecode": 39
  },
  {
    "id":237,
    "name_en": "Venezuela, Bolivarian Republic of",
    "name_es": "Venezuela",
    "name": "Venezuela",
    "sortname": "VE",
    "sortname2": "VEN",
    "latitude": 6.42375,
    "longitude": -66.58973,
    "flag": "🇻🇪",
    "phonecode": 58
  },
  {
    "id":238,
    "name_en": "Vietnam",
    "name_es": "Vietnam",
    "name": "Vietnam",
    "sortname": "VN",
    "sortname2": "VNM",
    "latitude": 14.058324,
    "longitude": 108.277199,
    "flag": "🇻🇳",
    "phonecode": 84
  },
  {
    "id":239,
    "name_en": "Virgin Islands, British",
    "name_es": "Islas Vírgenes Británicas",
    "name": "Islas Vírgenes Británicas",
    "sortname": "VG",
    "sortname2": "VGB",
    "latitude": 18.420695,
    "longitude": -64.639968,
    "flag": "🇻🇬",
    "phonecode": 1284
  },
  {
    "id":240,
    "name_en": "Virgin Islands, U.S.",
    "name_es": "Islas Vírgenes de los Estados Unidos",
    "name": "Islas Vírgenes de los Estados Unidos",
    "sortname": "VI",
    "sortname2": "VIR",
    "latitude": 18.335765,
    "longitude": -64.896335,
    "flag": "🇻🇮",
    "phonecode": 1340
  },
  {
    "id":241,
    "name_en": "Wallis and Futuna",
    "name_es": "Wallis y Futuna",
    "name": "Wallis y Futuna",
    "sortname": "WF",
    "sortname2": "WLF",
    "latitude": -13.768752,
    "longitude": -177.156097,
    "flag": "🇼🇫",
    "phonecode": 681
  },
  {
    "id":242,
    "name_en": "Western Sahara",
    "name_es": "Sahara Occidental",
    "name": "Sahara Occidental",
    "sortname": "EH",
    "sortname2": "ESH",
    "latitude": 24.215527,
    "longitude": -12.885834,
    "flag": "🇪🇭",
    "phonecode": 212
  },
  {
    "id":243,
    "name_en": "Yemen",
    "name_es": "Yemen",
    "name": "Yemen",
    "sortname": "YE",
    "sortname2": "YEM",
    "latitude": 15.552727,
    "longitude": 48.516388,
    "flag": "🇾🇪",
    "phonecode": 967
  },
  {
    "id":244,
    "name_en": "Montenegro",
    "name_es": "Montenegro",
    "name": "Montenegro",
    "sortname": "ME",
    "sortname2": "MNE",
    "latitude": 42.708678,
    "longitude": 19.37439,
    "flag": "🇲🇪",
    "phonecode": 382
  },
  {
    "id":245,
    "name_en": "Zambia",
    "name_es": "Zambia",
    "name": "Zambia",
    "sortname": "ZM",
    "sortname2": "ZMB",
    "latitude": -13.133897,
    "longitude": 27.849332,
    "flag": "🇿🇲",
    "phonecode": 260
  },
  {
    "id":246,
    "name_en": "Zimbabwe",
    "name_es": "Zimbabue",
    "name": "Zimbabue",
    "sortname": "ZW",
    "sortname2": "ZWE",
    "latitude": -19.015438,
    "longitude": 29.154857,
    "flag": "🇿🇼",
    "phonecode": 263
  }
  ])