<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class OdooMunicipalitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('odoo_municipalities')->insert(['id'=>29,'state_id' => 1670,'odoo_municipality_id' => 29, 'odoo_mun_code' => '307','odoo_mun_name' => 'Autónomo Alto Orinoco' ]);
        DB::table('odoo_municipalities')->insert(['id'=>24,'state_id' => 1670,'odoo_municipality_id' => 24, 'odoo_mun_code' => '302','odoo_mun_name' => 'Autónomo Atabapo' ]);
        DB::table('odoo_municipalities')->insert(['id'=>23,'state_id' => 1670,'odoo_municipality_id' => 23, 'odoo_mun_code' => '301','odoo_mun_name' => 'Autónomo Atures' ]);
        DB::table('odoo_municipalities')->insert(['id'=>27,'state_id' => 1670,'odoo_municipality_id' => 27, 'odoo_mun_code' => '305','odoo_mun_name' => 'Autónomo Autana' ]);
        DB::table('odoo_municipalities')->insert(['id'=>25,'state_id' => 1670,'odoo_municipality_id' => 25, 'odoo_mun_code' => '303','odoo_mun_name' => 'Autónomo Guainía' ]);
        DB::table('odoo_municipalities')->insert(['id'=>28,'state_id' => 1670,'odoo_municipality_id' => 28, 'odoo_mun_code' => '306','odoo_mun_name' => 'Autónomo Manapiare' ]);
        DB::table('odoo_municipalities')->insert(['id'=>26,'state_id' => 1670,'odoo_municipality_id' => 26, 'odoo_mun_code' => '304','odoo_mun_name' => 'Autónomo Río Negro' ]);
        DB::table('odoo_municipalities')->insert(['id'=>30,'state_id' => 1671,'odoo_municipality_id' => 30, 'odoo_mun_code' => '401','odoo_mun_name' => 'Achaguas' ]);
        DB::table('odoo_municipalities')->insert(['id'=>36,'state_id' => 1671,'odoo_municipality_id' => 36, 'odoo_mun_code' => '407','odoo_mun_name' => 'Biruaca' ]);
        DB::table('odoo_municipalities')->insert(['id'=>31,'state_id' => 1671,'odoo_municipality_id' => 31, 'odoo_mun_code' => '402','odoo_mun_name' => 'Muñoz' ]);
        DB::table('odoo_municipalities')->insert(['id'=>33,'state_id' => 1671,'odoo_municipality_id' => 33, 'odoo_mun_code' => '404','odoo_mun_name' => 'Pedro Camejo' ]);
        DB::table('odoo_municipalities')->insert(['id'=>32,'state_id' => 1671,'odoo_municipality_id' => 32, 'odoo_mun_code' => '403','odoo_mun_name' => 'Páez' ]);
        DB::table('odoo_municipalities')->insert(['id'=>34,'state_id' => 1671,'odoo_municipality_id' => 34, 'odoo_mun_code' => '405','odoo_mun_name' => 'Rómulo Gallegos' ]);
        DB::table('odoo_municipalities')->insert(['id'=>35,'state_id' => 1671,'odoo_municipality_id' => 35, 'odoo_mun_code' => '406','odoo_mun_name' => 'San Fernando' ]);
        DB::table('odoo_municipalities')->insert(['id'=>37,'state_id' => 1672,'odoo_municipality_id' => 37, 'odoo_mun_code' => '501','odoo_mun_name' => 'Atanasio Girardot' ]);
        DB::table('odoo_municipalities')->insert(['id'=>47,'state_id' => 1672,'odoo_municipality_id' => 47, 'odoo_mun_code' => '511','odoo_mun_name' => 'Bolívar' ]);
        DB::table('odoo_municipalities')->insert(['id'=>51,'state_id' => 1672,'odoo_municipality_id' => 51, 'odoo_mun_code' => '515','odoo_mun_name' => 'Camatagua' ]);
        DB::table('odoo_municipalities')->insert(['id'=>53,'state_id' => 1672,'odoo_municipality_id' => 53, 'odoo_mun_code' => '517','odoo_mun_name' => 'Francisco Linares Alcántara' ]);
        DB::table('odoo_municipalities')->insert(['id'=>46,'state_id' => 1672,'odoo_municipality_id' => 46, 'odoo_mun_code' => '510','odoo_mun_name' => 'José Angel Lamas' ]);
        DB::table('odoo_municipalities')->insert(['id'=>39,'state_id' => 1672,'odoo_municipality_id' => 39, 'odoo_mun_code' => '503','odoo_mun_name' => 'José Félix Ribas' ]);
        DB::table('odoo_municipalities')->insert(['id'=>52,'state_id' => 1672,'odoo_municipality_id' => 52, 'odoo_mun_code' => '516','odoo_mun_name' => 'José Rafael Revenga' ]);
        DB::table('odoo_municipalities')->insert(['id'=>45,'state_id' => 1672,'odoo_municipality_id' => 45, 'odoo_mun_code' => '509','odoo_mun_name' => 'Libertador' ]);
        DB::table('odoo_municipalities')->insert(['id'=>49,'state_id' => 1672,'odoo_municipality_id' => 49, 'odoo_mun_code' => '513','odoo_mun_name' => 'Mario Briceño Iragorry' ]);
        DB::table('odoo_municipalities')->insert(['id'=>54,'state_id' => 1672,'odoo_municipality_id' => 54, 'odoo_mun_code' => '518','odoo_mun_name' => 'Ocumare De La Costa De Oro' ]);
        DB::table('odoo_municipalities')->insert(['id'=>40,'state_id' => 1672,'odoo_municipality_id' => 40, 'odoo_mun_code' => '504','odoo_mun_name' => 'San Casimiro' ]);
        DB::table('odoo_municipalities')->insert(['id'=>41,'state_id' => 1672,'odoo_municipality_id' => 41, 'odoo_mun_code' => '505','odoo_mun_name' => 'San Sebastián' ]);
        DB::table('odoo_municipalities')->insert(['id'=>38,'state_id' => 1672,'odoo_municipality_id' => 38, 'odoo_mun_code' => '502','odoo_mun_name' => 'Santiago Mariño' ]);
        DB::table('odoo_municipalities')->insert(['id'=>48,'state_id' => 1672,'odoo_municipality_id' => 48, 'odoo_mun_code' => '512','odoo_mun_name' => 'Santos Michelena' ]);
        DB::table('odoo_municipalities')->insert(['id'=>42,'state_id' => 1672,'odoo_municipality_id' => 42, 'odoo_mun_code' => '506','odoo_mun_name' => 'Sucre' ]);
        DB::table('odoo_municipalities')->insert(['id'=>50,'state_id' => 1672,'odoo_municipality_id' => 50, 'odoo_mun_code' => '514','odoo_mun_name' => 'Tovar' ]);
        DB::table('odoo_municipalities')->insert(['id'=>43,'state_id' => 1672,'odoo_municipality_id' => 43, 'odoo_mun_code' => '507','odoo_mun_name' => 'Urdaneta' ]);
        DB::table('odoo_municipalities')->insert(['id'=>44,'state_id' => 1672,'odoo_municipality_id' => 44, 'odoo_mun_code' => '508','odoo_mun_name' => 'Zamora' ]);
        DB::table('odoo_municipalities')->insert(['id'=>2,'state_id' => 1669,'odoo_municipality_id' => 2, 'odoo_mun_code' => '201','odoo_mun_name' => 'Anaco' ]);
        DB::table('odoo_municipalities')->insert(['id'=>3,'state_id' => 1669,'odoo_municipality_id' => 3, 'odoo_mun_code' => '202','odoo_mun_name' => 'Aragua' ]);
        DB::table('odoo_municipalities')->insert(['id'=>18,'state_id' => 1669,'odoo_municipality_id' => 18, 'odoo_mun_code' => '217','odoo_mun_name' => 'Diego Bautista Urbaneja' ]);
        DB::table('odoo_municipalities')->insert(['id'=>12,'state_id' => 1669,'odoo_municipality_id' => 12, 'odoo_mun_code' => '211','odoo_mun_name' => 'Fernando De Peñalver' ]);
        DB::table('odoo_municipalities')->insert(['id'=>10,'state_id' => 1669,'odoo_municipality_id' => 10, 'odoo_mun_code' => '209','odoo_mun_name' => 'Francisco De Miranda' ]);
        DB::table('odoo_municipalities')->insert(['id'=>19,'state_id' => 1669,'odoo_municipality_id' => 19, 'odoo_mun_code' => '218','odoo_mun_name' => 'Francisco Del Carmen Carvajal' ]);
        DB::table('odoo_municipalities')->insert(['id'=>16,'state_id' => 1669,'odoo_municipality_id' => 16, 'odoo_mun_code' => '215','odoo_mun_name' => 'Guanta' ]);
        DB::table('odoo_municipalities')->insert(['id'=>8,'state_id' => 1669,'odoo_municipality_id' => 8, 'odoo_mun_code' => '207','odoo_mun_name' => 'Independencia' ]);
        DB::table('odoo_municipalities')->insert(['id'=>11,'state_id' => 1669,'odoo_municipality_id' => 11, 'odoo_mun_code' => '210','odoo_mun_name' => 'José Gregorio Monagas' ]);
        DB::table('odoo_municipalities')->insert(['id'=>14,'state_id' => 1669,'odoo_municipality_id' => 14, 'odoo_mun_code' => '213','odoo_mun_name' => 'Juan Antonio Sotillo' ]);
        DB::table('odoo_municipalities')->insert(['id'=>6,'state_id' => 1669,'odoo_municipality_id' => 6, 'odoo_mun_code' => '205','odoo_mun_name' => 'Juan Manuel Cajigal' ]);
        DB::table('odoo_municipalities')->insert(['id'=>9,'state_id' => 1669,'odoo_municipality_id' => 9, 'odoo_mun_code' => '208','odoo_mun_name' => 'Libertad' ]);
        DB::table('odoo_municipalities')->insert(['id'=>5,'state_id' => 1669,'odoo_municipality_id' => 5, 'odoo_mun_code' => '204','odoo_mun_name' => 'Manuel Ezequiel Bruzual' ]);
        DB::table('odoo_municipalities')->insert(['id'=>7,'state_id' => 1669,'odoo_municipality_id' => 7, 'odoo_mun_code' => '206','odoo_mun_name' => 'Pedro María Freites' ]);
        DB::table('odoo_municipalities')->insert(['id'=>17,'state_id' => 1669,'odoo_municipality_id' => 17, 'odoo_mun_code' => '216','odoo_mun_name' => 'Píritu' ]);
        DB::table('odoo_municipalities')->insert(['id'=>15,'state_id' => 1669,'odoo_municipality_id' => 15, 'odoo_mun_code' => '214','odoo_mun_name' => 'San José De Guanipa' ]);
        DB::table('odoo_municipalities')->insert(['id'=>22,'state_id' => 1669,'odoo_municipality_id' => 22, 'odoo_mun_code' => '221','odoo_mun_name' => 'San Juan De Capistrano' ]);
        DB::table('odoo_municipalities')->insert(['id'=>20,'state_id' => 1669,'odoo_municipality_id' => 20, 'odoo_mun_code' => '219','odoo_mun_name' => 'Santa  Ana' ]);
        DB::table('odoo_municipalities')->insert(['id'=>4,'state_id' => 1669,'odoo_municipality_id' => 4, 'odoo_mun_code' => '203','odoo_mun_name' => 'Simón Bolívar' ]);
        DB::table('odoo_municipalities')->insert(['id'=>13,'state_id' => 1669,'odoo_municipality_id' => 13, 'odoo_mun_code' => '212','odoo_mun_name' => 'Simón Rodríguez' ]);
        DB::table('odoo_municipalities')->insert(['id'=>21,'state_id' => 1669,'odoo_municipality_id' => 21, 'odoo_mun_code' => '220','odoo_mun_name' => 'Sir Arthur Mc Gregor' ]);
        DB::table('odoo_municipalities')->insert(['id'=>63,'state_id' => 1673,'odoo_municipality_id' => 63, 'odoo_mun_code' => '609','odoo_mun_name' => 'Alberto Arvelo Torrealba' ]);
        DB::table('odoo_municipalities')->insert(['id'=>66,'state_id' => 1673,'odoo_municipality_id' => 66, 'odoo_mun_code' => '612','odoo_mun_name' => 'Andrés Eloy Blanco' ]);
        DB::table('odoo_municipalities')->insert(['id'=>64,'state_id' => 1673,'odoo_municipality_id' => 64, 'odoo_mun_code' => '610','odoo_mun_name' => 'Antonio José De Sucre' ]);
        DB::table('odoo_municipalities')->insert(['id'=>55,'state_id' => 1673,'odoo_municipality_id' => 55, 'odoo_mun_code' => '601','odoo_mun_name' => 'Arismendi' ]);
        DB::table('odoo_municipalities')->insert(['id'=>56,'state_id' => 1673,'odoo_municipality_id' => 56, 'odoo_mun_code' => '602','odoo_mun_name' => 'Barinas' ]);
        DB::table('odoo_municipalities')->insert(['id'=>57,'state_id' => 1673,'odoo_municipality_id' => 57, 'odoo_mun_code' => '603','odoo_mun_name' => 'Bolívar' ]);
        DB::table('odoo_municipalities')->insert(['id'=>65,'state_id' => 1673,'odoo_municipality_id' => 65, 'odoo_mun_code' => '611','odoo_mun_name' => 'Cruz Paredes' ]);
        DB::table('odoo_municipalities')->insert(['id'=>58,'state_id' => 1673,'odoo_municipality_id' => 58, 'odoo_mun_code' => '604','odoo_mun_name' => 'Ezequiel Zamora' ]);
        DB::table('odoo_municipalities')->insert(['id'=>59,'state_id' => 1673,'odoo_municipality_id' => 59, 'odoo_mun_code' => '605','odoo_mun_name' => 'Obispos' ]);
        DB::table('odoo_municipalities')->insert(['id'=>60,'state_id' => 1673,'odoo_municipality_id' => 60, 'odoo_mun_code' => '606','odoo_mun_name' => 'Pedraza' ]);
        DB::table('odoo_municipalities')->insert(['id'=>61,'state_id' => 1673,'odoo_municipality_id' => 61, 'odoo_mun_code' => '607','odoo_mun_name' => 'Rojas' ]);
        DB::table('odoo_municipalities')->insert(['id'=>62,'state_id' => 1673,'odoo_municipality_id' => 62, 'odoo_mun_code' => '608','odoo_mun_name' => 'Sosa' ]);
        DB::table('odoo_municipalities')->insert(['id'=>74,'state_id' => 1674,'odoo_municipality_id' => 74, 'odoo_mun_code' => '708','odoo_mun_name' => 'Angostura' ]);
        DB::table('odoo_municipalities')->insert(['id'=>67,'state_id' => 1674,'odoo_municipality_id' => 67, 'odoo_mun_code' => '701','odoo_mun_name' => 'Caroní' ]);
        DB::table('odoo_municipalities')->insert(['id'=>68,'state_id' => 1674,'odoo_municipality_id' => 68, 'odoo_mun_code' => '702','odoo_mun_name' => 'Cedeño' ]);
        DB::table('odoo_municipalities')->insert(['id'=>76,'state_id' => 1674,'odoo_municipality_id' => 76, 'odoo_mun_code' => '710','odoo_mun_name' => 'El Callao' ]);
        DB::table('odoo_municipalities')->insert(['id'=>75,'state_id' => 1674,'odoo_municipality_id' => 75, 'odoo_mun_code' => '709','odoo_mun_name' => 'Gran Sabana' ]);
        DB::table('odoo_municipalities')->insert(['id'=>69,'state_id' => 1674,'odoo_municipality_id' => 69, 'odoo_mun_code' => '703','odoo_mun_name' => 'Heres' ]);
        DB::table('odoo_municipalities')->insert(['id'=>77,'state_id' => 1674,'odoo_municipality_id' => 77, 'odoo_mun_code' => '711','odoo_mun_name' => 'Padre Pedro Chien' ]);
        DB::table('odoo_municipalities')->insert(['id'=>70,'state_id' => 1674,'odoo_municipality_id' => 70, 'odoo_mun_code' => '704','odoo_mun_name' => 'Piar' ]);
        DB::table('odoo_municipalities')->insert(['id'=>71,'state_id' => 1674,'odoo_municipality_id' => 71, 'odoo_mun_code' => '705','odoo_mun_name' => 'Roscio' ]);
        DB::table('odoo_municipalities')->insert(['id'=>73,'state_id' => 1674,'odoo_municipality_id' => 73, 'odoo_mun_code' => '707','odoo_mun_name' => 'Sifontes' ]);
        DB::table('odoo_municipalities')->insert(['id'=>72,'state_id' => 1674,'odoo_municipality_id' => 72, 'odoo_mun_code' => '706','odoo_mun_name' => 'Sucre' ]);
        DB::table('odoo_municipalities')->insert(['id'=>78,'state_id' => 1675,'odoo_municipality_id' => 78, 'odoo_mun_code' => '801','odoo_mun_name' => 'Bejuma' ]);
        DB::table('odoo_municipalities')->insert(['id'=>79,'state_id' => 1675,'odoo_municipality_id' => 79, 'odoo_mun_code' => '802','odoo_mun_name' => 'Carlos Arvelo' ]);
        DB::table('odoo_municipalities')->insert(['id'=>80,'state_id' => 1675,'odoo_municipality_id' => 80, 'odoo_mun_code' => '803','odoo_mun_name' => 'Diego Ibarra' ]);
        DB::table('odoo_municipalities')->insert(['id'=>81,'state_id' => 1675,'odoo_municipality_id' => 81, 'odoo_mun_code' => '804','odoo_mun_name' => 'Guacara' ]);
        DB::table('odoo_municipalities')->insert(['id'=>83,'state_id' => 1675,'odoo_municipality_id' => 83, 'odoo_mun_code' => '806','odoo_mun_name' => 'Juan José Mora' ]);
        DB::table('odoo_municipalities')->insert(['id'=>91,'state_id' => 1675,'odoo_municipality_id' => 91, 'odoo_mun_code' => '814','odoo_mun_name' => 'Libertador' ]);
        DB::table('odoo_municipalities')->insert(['id'=>88,'state_id' => 1675,'odoo_municipality_id' => 88, 'odoo_mun_code' => '811','odoo_mun_name' => 'Los Guayos' ]);
        DB::table('odoo_municipalities')->insert(['id'=>87,'state_id' => 1675,'odoo_municipality_id' => 87, 'odoo_mun_code' => '810','odoo_mun_name' => 'Miranda' ]);
        DB::table('odoo_municipalities')->insert(['id'=>82,'state_id' => 1675,'odoo_municipality_id' => 82, 'odoo_mun_code' => '805','odoo_mun_name' => 'Montalbán' ]);
        DB::table('odoo_municipalities')->insert(['id'=>89,'state_id' => 1675,'odoo_municipality_id' => 89, 'odoo_mun_code' => '812','odoo_mun_name' => 'Naguanagua' ]);
        DB::table('odoo_municipalities')->insert(['id'=>84,'state_id' => 1675,'odoo_municipality_id' => 84, 'odoo_mun_code' => '807','odoo_mun_name' => 'Puerto Cabello' ]);
        DB::table('odoo_municipalities')->insert(['id'=>90,'state_id' => 1675,'odoo_municipality_id' => 90, 'odoo_mun_code' => '813','odoo_mun_name' => 'San Diego' ]);
        DB::table('odoo_municipalities')->insert(['id'=>85,'state_id' => 1675,'odoo_municipality_id' => 85, 'odoo_mun_code' => '808','odoo_mun_name' => 'San Joaquín' ]);
        DB::table('odoo_municipalities')->insert(['id'=>86,'state_id' => 1675,'odoo_municipality_id' => 86, 'odoo_mun_code' => '809','odoo_mun_name' => 'Valencia' ]);
        DB::table('odoo_municipalities')->insert(['id'=>92,'state_id' => 1676,'odoo_municipality_id' => 92, 'odoo_mun_code' => '901','odoo_mun_name' => 'Anzoátegui' ]);
        DB::table('odoo_municipalities')->insert(['id'=>93,'state_id' => 1676,'odoo_municipality_id' => 93, 'odoo_mun_code' => '902','odoo_mun_name' => 'Falcón' ]);
        DB::table('odoo_municipalities')->insert(['id'=>94,'state_id' => 1676,'odoo_municipality_id' => 94, 'odoo_mun_code' => '903','odoo_mun_name' => 'Girardot' ]);
        DB::table('odoo_municipalities')->insert(['id'=>99,'state_id' => 1676,'odoo_municipality_id' => 99, 'odoo_mun_code' => '908','odoo_mun_name' => 'Lima Blanco' ]);
        DB::table('odoo_municipalities')->insert(['id'=>95,'state_id' => 1676,'odoo_municipality_id' => 95, 'odoo_mun_code' => '904','odoo_mun_name' => 'Pao De San Juan Bautista' ]);
        DB::table('odoo_municipalities')->insert(['id'=>96,'state_id' => 1676,'odoo_municipality_id' => 96, 'odoo_mun_code' => '905','odoo_mun_name' => 'Ricaurte' ]);
        DB::table('odoo_municipalities')->insert(['id'=>100,'state_id' => 1676,'odoo_municipality_id' => 100, 'odoo_mun_code' => '909','odoo_mun_name' => 'Rómulo Gallegos' ]);
        DB::table('odoo_municipalities')->insert(['id'=>97,'state_id' => 1676,'odoo_municipality_id' => 97, 'odoo_mun_code' => '906','odoo_mun_name' => 'San Carlos' ]);
        DB::table('odoo_municipalities')->insert(['id'=>98,'state_id' => 1676,'odoo_municipality_id' => 98, 'odoo_mun_code' => '907','odoo_mun_name' => 'Tinaco' ]);
        DB::table('odoo_municipalities')->insert(['id'=>333,'state_id' => 1690,'odoo_municipality_id' => 333, 'odoo_mun_code' => '2303','odoo_mun_name' => 'Antonio Díaz' ]);
        DB::table('odoo_municipalities')->insert(['id'=>334,'state_id' => 1690,'odoo_municipality_id' => 334, 'odoo_mun_code' => '2304','odoo_mun_name' => 'Casacoima' ]);
        DB::table('odoo_municipalities')->insert(['id'=>332,'state_id' => 1690,'odoo_municipality_id' => 332, 'odoo_mun_code' => '2302','odoo_mun_name' => 'Pedernales' ]);
        DB::table('odoo_municipalities')->insert(['id'=>331,'state_id' => 1690,'odoo_municipality_id' => 331, 'odoo_mun_code' => '2301','odoo_mun_name' => 'Tucupita' ]);
        DB::table('odoo_municipalities')->insert(['id'=>1,'state_id' => 1668,'odoo_municipality_id' => 1, 'odoo_mun_code' => '101','odoo_mun_name' => 'Libertador' ]);
        DB::table('odoo_municipalities')->insert(['id'=>101,'state_id' => 1677,'odoo_municipality_id' => 101, 'odoo_mun_code' => '1001','odoo_mun_name' => 'Acosta' ]);
        DB::table('odoo_municipalities')->insert(['id'=>102,'state_id' => 1677,'odoo_municipality_id' => 102, 'odoo_mun_code' => '1002','odoo_mun_name' => 'Bolívar' ]);
        DB::table('odoo_municipalities')->insert(['id'=>103,'state_id' => 1677,'odoo_municipality_id' => 103, 'odoo_mun_code' => '1003','odoo_mun_name' => 'Buchivacoa' ]);
        DB::table('odoo_municipalities')->insert(['id'=>121,'state_id' => 1677,'odoo_municipality_id' => 121, 'odoo_mun_code' => '1021','odoo_mun_name' => 'Cacique Manaure' ]);
        DB::table('odoo_municipalities')->insert(['id'=>104,'state_id' => 1677,'odoo_municipality_id' => 104, 'odoo_mun_code' => '1004','odoo_mun_name' => 'Carirubana' ]);
        DB::table('odoo_municipalities')->insert(['id'=>105,'state_id' => 1677,'odoo_municipality_id' => 105, 'odoo_mun_code' => '1005','odoo_mun_name' => 'Colina' ]);
        DB::table('odoo_municipalities')->insert(['id'=>114,'state_id' => 1677,'odoo_municipality_id' => 114, 'odoo_mun_code' => '1014','odoo_mun_name' => 'Dabajuro' ]);
        DB::table('odoo_municipalities')->insert(['id'=>106,'state_id' => 1677,'odoo_municipality_id' => 106, 'odoo_mun_code' => '1006','odoo_mun_name' => 'Democracia' ]);
        DB::table('odoo_municipalities')->insert(['id'=>107,'state_id' => 1677,'odoo_municipality_id' => 107, 'odoo_mun_code' => '1007','odoo_mun_name' => 'Falcón' ]);
        DB::table('odoo_municipalities')->insert(['id'=>108,'state_id' => 1677,'odoo_municipality_id' => 108, 'odoo_mun_code' => '1008','odoo_mun_name' => 'Federación' ]);
        DB::table('odoo_municipalities')->insert(['id'=>120,'state_id' => 1677,'odoo_municipality_id' => 120, 'odoo_mun_code' => '1020','odoo_mun_name' => 'Jacura' ]);
        DB::table('odoo_municipalities')->insert(['id'=>116,'state_id' => 1677,'odoo_municipality_id' => 116, 'odoo_mun_code' => '1016','odoo_mun_name' => 'Los Taques' ]);
        DB::table('odoo_municipalities')->insert(['id'=>109,'state_id' => 1677,'odoo_municipality_id' => 109, 'odoo_mun_code' => '1009','odoo_mun_name' => 'Mauroa' ]);
        DB::table('odoo_municipalities')->insert(['id'=>110,'state_id' => 1677,'odoo_municipality_id' => 110, 'odoo_mun_code' => '1010','odoo_mun_name' => 'Miranda' ]);
        DB::table('odoo_municipalities')->insert(['id'=>115,'state_id' => 1677,'odoo_municipality_id' => 115, 'odoo_mun_code' => '1015','odoo_mun_name' => 'Monseñor Iturriza' ]);
        DB::table('odoo_municipalities')->insert(['id'=>122,'state_id' => 1677,'odoo_municipality_id' => 122, 'odoo_mun_code' => '1022','odoo_mun_name' => 'Palmasola' ]);
        DB::table('odoo_municipalities')->insert(['id'=>111,'state_id' => 1677,'odoo_municipality_id' => 111, 'odoo_mun_code' => '1011','odoo_mun_name' => 'Petit' ]);
        DB::table('odoo_municipalities')->insert(['id'=>117,'state_id' => 1677,'odoo_municipality_id' => 117, 'odoo_mun_code' => '1017','odoo_mun_name' => 'Píritu' ]);
        DB::table('odoo_municipalities')->insert(['id'=>119,'state_id' => 1677,'odoo_municipality_id' => 119, 'odoo_mun_code' => '1019','odoo_mun_name' => 'San Francisco' ]);
        DB::table('odoo_municipalities')->insert(['id'=>112,'state_id' => 1677,'odoo_municipality_id' => 112, 'odoo_mun_code' => '1012','odoo_mun_name' => 'Silva' ]);
        DB::table('odoo_municipalities')->insert(['id'=>123,'state_id' => 1677,'odoo_municipality_id' => 123, 'odoo_mun_code' => '1023','odoo_mun_name' => 'Sucre' ]);
        DB::table('odoo_municipalities')->insert(['id'=>125,'state_id' => 1677,'odoo_municipality_id' => 125, 'odoo_mun_code' => '1025','odoo_mun_name' => 'Tocópero' ]);
        DB::table('odoo_municipalities')->insert(['id'=>118,'state_id' => 1677,'odoo_municipality_id' => 118, 'odoo_mun_code' => '1018','odoo_mun_name' => 'Unión' ]);
        DB::table('odoo_municipalities')->insert(['id'=>124,'state_id' => 1677,'odoo_municipality_id' => 124, 'odoo_mun_code' => '1024','odoo_mun_name' => 'Urumaco' ]);
        DB::table('odoo_municipalities')->insert(['id'=>113,'state_id' => 1677,'odoo_municipality_id' => 113, 'odoo_mun_code' => '1013','odoo_mun_name' => 'Zamora' ]);
        DB::table('odoo_municipalities')->insert(['id'=>133,'state_id' => 1678,'odoo_municipality_id' => 133, 'odoo_mun_code' => '1108','odoo_mun_name' => 'Camaguán' ]);
        DB::table('odoo_municipalities')->insert(['id'=>139,'state_id' => 1678,'odoo_municipality_id' => 139, 'odoo_mun_code' => '1114','odoo_mun_name' => 'Chaguaramas' ]);
        DB::table('odoo_municipalities')->insert(['id'=>136,'state_id' => 1678,'odoo_municipality_id' => 136, 'odoo_mun_code' => '1111','odoo_mun_name' => 'El Socorro' ]);
        DB::table('odoo_municipalities')->insert(['id'=>128,'state_id' => 1678,'odoo_municipality_id' => 128, 'odoo_mun_code' => '1103','odoo_mun_name' => 'Francisco De Miranda' ]);
        DB::table('odoo_municipalities')->insert(['id'=>130,'state_id' => 1678,'odoo_municipality_id' => 130, 'odoo_mun_code' => '1105','odoo_mun_name' => 'José Félix Ribas' ]);
        DB::table('odoo_municipalities')->insert(['id'=>129,'state_id' => 1678,'odoo_municipality_id' => 129, 'odoo_mun_code' => '1104','odoo_mun_name' => 'José Tadeo Monagas' ]);
        DB::table('odoo_municipalities')->insert(['id'=>131,'state_id' => 1678,'odoo_municipality_id' => 131, 'odoo_mun_code' => '1106','odoo_mun_name' => 'Juan Germán Roscio' ]);
        DB::table('odoo_municipalities')->insert(['id'=>127,'state_id' => 1678,'odoo_municipality_id' => 127, 'odoo_mun_code' => '1102','odoo_mun_name' => 'Julián Mellado' ]);
        DB::table('odoo_municipalities')->insert(['id'=>135,'state_id' => 1678,'odoo_municipality_id' => 135, 'odoo_mun_code' => '1110','odoo_mun_name' => 'Las Mercedes' ]);
        DB::table('odoo_municipalities')->insert(['id'=>126,'state_id' => 1678,'odoo_municipality_id' => 126, 'odoo_mun_code' => '1101','odoo_mun_name' => 'Leonardo Infante' ]);
        DB::table('odoo_municipalities')->insert(['id'=>137,'state_id' => 1678,'odoo_municipality_id' => 137, 'odoo_mun_code' => '1112','odoo_mun_name' => 'Ortíz' ]);
        DB::table('odoo_municipalities')->insert(['id'=>132,'state_id' => 1678,'odoo_municipality_id' => 132, 'odoo_mun_code' => '1107','odoo_mun_name' => 'Pedro Zaraza' ]);
        DB::table('odoo_municipalities')->insert(['id'=>140,'state_id' => 1678,'odoo_municipality_id' => 140, 'odoo_mun_code' => '1115','odoo_mun_name' => 'San Gerónimo De Guayabal' ]);
        DB::table('odoo_municipalities')->insert(['id'=>134,'state_id' => 1678,'odoo_municipality_id' => 134, 'odoo_mun_code' => '1109','odoo_mun_name' => 'San José De Guaribe' ]);
        DB::table('odoo_municipalities')->insert(['id'=>138,'state_id' => 1678,'odoo_municipality_id' => 138, 'odoo_mun_code' => '1113','odoo_mun_name' => 'Santa María De Ipire' ]);
        DB::table('odoo_municipalities')->insert(['id'=>148,'state_id' => 1679,'odoo_municipality_id' => 148, 'odoo_mun_code' => '1208','odoo_mun_name' => 'Andrés Eloy Blanco' ]);
        DB::table('odoo_municipalities')->insert(['id'=>141,'state_id' => 1679,'odoo_municipality_id' => 141, 'odoo_mun_code' => '1201','odoo_mun_name' => 'Crespo' ]);
        DB::table('odoo_municipalities')->insert(['id'=>142,'state_id' => 1679,'odoo_municipality_id' => 142, 'odoo_mun_code' => '1202','odoo_mun_name' => 'Iribarren' ]);
        DB::table('odoo_municipalities')->insert(['id'=>143,'state_id' => 1679,'odoo_municipality_id' => 143, 'odoo_mun_code' => '1203','odoo_mun_name' => 'Jiménez' ]);
        DB::table('odoo_municipalities')->insert(['id'=>144,'state_id' => 1679,'odoo_municipality_id' => 144, 'odoo_mun_code' => '1204','odoo_mun_name' => 'Morán' ]);
        DB::table('odoo_municipalities')->insert(['id'=>145,'state_id' => 1679,'odoo_municipality_id' => 145, 'odoo_mun_code' => '1205','odoo_mun_name' => 'Palavecino' ]);
        DB::table('odoo_municipalities')->insert(['id'=>149,'state_id' => 1679,'odoo_municipality_id' => 149, 'odoo_mun_code' => '1209','odoo_mun_name' => 'Simón Planas' ]);
        DB::table('odoo_municipalities')->insert(['id'=>146,'state_id' => 1679,'odoo_municipality_id' => 146, 'odoo_mun_code' => '1206','odoo_mun_name' => 'Torres' ]);
        DB::table('odoo_municipalities')->insert(['id'=>147,'state_id' => 1679,'odoo_municipality_id' => 147, 'odoo_mun_code' => '1207','odoo_mun_name' => 'Urdaneta' ]);
        DB::table('odoo_municipalities')->insert(['id'=>335,'state_id' => 1691,'odoo_municipality_id' => 335, 'odoo_mun_code' => '2401','odoo_mun_name' => 'Vargas' ]);
        DB::table('odoo_municipalities')->insert(['id'=>150,'state_id' => 1680,'odoo_municipality_id' => 150, 'odoo_mun_code' => '1301','odoo_mun_name' => 'Alberto Adriani' ]);
        DB::table('odoo_municipalities')->insert(['id'=>151,'state_id' => 1680,'odoo_municipality_id' => 151, 'odoo_mun_code' => '1302','odoo_mun_name' => 'Andrés Bello' ]);
        DB::table('odoo_municipalities')->insert(['id'=>160,'state_id' => 1680,'odoo_municipality_id' => 160, 'odoo_mun_code' => '1311','odoo_mun_name' => 'Antonio Pinto Salinas' ]);
        DB::table('odoo_municipalities')->insert(['id'=>171,'state_id' => 1680,'odoo_municipality_id' => 171, 'odoo_mun_code' => '1322','odoo_mun_name' => 'Aricagua' ]);
        DB::table('odoo_municipalities')->insert(['id'=>152,'state_id' => 1680,'odoo_municipality_id' => 152, 'odoo_mun_code' => '1303','odoo_mun_name' => 'Arzobispo Chacón' ]);
        DB::table('odoo_municipalities')->insert(['id'=>153,'state_id' => 1680,'odoo_municipality_id' => 153, 'odoo_mun_code' => '1304','odoo_mun_name' => 'Campo Elías' ]);
        DB::table('odoo_municipalities')->insert(['id'=>162,'state_id' => 1680,'odoo_municipality_id' => 162, 'odoo_mun_code' => '1313','odoo_mun_name' => 'Caracciolo Parra Olmedo' ]);
        DB::table('odoo_municipalities')->insert(['id'=>163,'state_id' => 1680,'odoo_municipality_id' => 163, 'odoo_mun_code' => '1314','odoo_mun_name' => 'Cardenal Quintero' ]);
        DB::table('odoo_municipalities')->insert(['id'=>154,'state_id' => 1680,'odoo_municipality_id' => 154, 'odoo_mun_code' => '1305','odoo_mun_name' => 'Guaraque' ]);
        DB::table('odoo_municipalities')->insert(['id'=>155,'state_id' => 1680,'odoo_municipality_id' => 155, 'odoo_mun_code' => '1306','odoo_mun_name' => 'Julio César Salas' ]);
        DB::table('odoo_municipalities')->insert(['id'=>156,'state_id' => 1680,'odoo_municipality_id' => 156, 'odoo_mun_code' => '1307','odoo_mun_name' => 'Justo Briceño' ]);
        DB::table('odoo_municipalities')->insert(['id'=>157,'state_id' => 1680,'odoo_municipality_id' => 157, 'odoo_mun_code' => '1308','odoo_mun_name' => 'Libertador' ]);
        DB::table('odoo_municipalities')->insert(['id'=>159,'state_id' => 1680,'odoo_municipality_id' => 159, 'odoo_mun_code' => '1310','odoo_mun_name' => 'Miranda' ]);
        DB::table('odoo_municipalities')->insert(['id'=>161,'state_id' => 1680,'odoo_municipality_id' => 161, 'odoo_mun_code' => '1312','odoo_mun_name' => 'Obispo Ramos De Lora' ]);
        DB::table('odoo_municipalities')->insert(['id'=>170,'state_id' => 1680,'odoo_municipality_id' => 170, 'odoo_mun_code' => '1321','odoo_mun_name' => 'Padre Noguera' ]);
        DB::table('odoo_municipalities')->insert(['id'=>164,'state_id' => 1680,'odoo_municipality_id' => 164, 'odoo_mun_code' => '1315','odoo_mun_name' => 'Pueblo Llano' ]);
        DB::table('odoo_municipalities')->insert(['id'=>165,'state_id' => 1680,'odoo_municipality_id' => 165, 'odoo_mun_code' => '1316','odoo_mun_name' => 'Rangel' ]);
        DB::table('odoo_municipalities')->insert(['id'=>166,'state_id' => 1680,'odoo_municipality_id' => 166, 'odoo_mun_code' => '1317','odoo_mun_name' => 'Rivas Dávila' ]);
        DB::table('odoo_municipalities')->insert(['id'=>158,'state_id' => 1680,'odoo_municipality_id' => 158, 'odoo_mun_code' => '1309','odoo_mun_name' => 'Santos Marquina' ]);
        DB::table('odoo_municipalities')->insert(['id'=>167,'state_id' => 1680,'odoo_municipality_id' => 167, 'odoo_mun_code' => '1318','odoo_mun_name' => 'Sucre' ]);
        DB::table('odoo_municipalities')->insert(['id'=>168,'state_id' => 1680,'odoo_municipality_id' => 168, 'odoo_mun_code' => '1319','odoo_mun_name' => 'Tovar' ]);
        DB::table('odoo_municipalities')->insert(['id'=>169,'state_id' => 1680,'odoo_municipality_id' => 169, 'odoo_mun_code' => '1320','odoo_mun_name' => 'Tulio Febres Cordero' ]);
        DB::table('odoo_municipalities')->insert(['id'=>172,'state_id' => 1680,'odoo_municipality_id' => 172, 'odoo_mun_code' => '1323','odoo_mun_name' => 'Zea' ]);
        DB::table('odoo_municipalities')->insert(['id'=>173,'state_id' => 1681,'odoo_municipality_id' => 173, 'odoo_mun_code' => '1401','odoo_mun_name' => 'Acevedo' ]);
        DB::table('odoo_municipalities')->insert(['id'=>186,'state_id' => 1681,'odoo_municipality_id' => 186, 'odoo_mun_code' => '1414','odoo_mun_name' => 'Andrés Bello' ]);
        DB::table('odoo_municipalities')->insert(['id'=>188,'state_id' => 1681,'odoo_municipality_id' => 188, 'odoo_mun_code' => '1416','odoo_mun_name' => 'Baruta' ]);
        DB::table('odoo_municipalities')->insert(['id'=>174,'state_id' => 1681,'odoo_municipality_id' => 174, 'odoo_mun_code' => '1402','odoo_mun_name' => 'Brión' ]);
        DB::table('odoo_municipalities')->insert(['id'=>192,'state_id' => 1681,'odoo_municipality_id' => 192, 'odoo_mun_code' => '1420','odoo_mun_name' => 'Buroz' ]);
        DB::table('odoo_municipalities')->insert(['id'=>189,'state_id' => 1681,'odoo_municipality_id' => 189, 'odoo_mun_code' => '1417','odoo_mun_name' => 'Carrizal' ]);
        DB::table('odoo_municipalities')->insert(['id'=>190,'state_id' => 1681,'odoo_municipality_id' => 190, 'odoo_mun_code' => '1418','odoo_mun_name' => 'Chacao' ]);
        DB::table('odoo_municipalities')->insert(['id'=>184,'state_id' => 1681,'odoo_municipality_id' => 184, 'odoo_mun_code' => '1412','odoo_mun_name' => 'Cristóbal Rojas' ]);
        DB::table('odoo_municipalities')->insert(['id'=>191,'state_id' => 1681,'odoo_municipality_id' => 191, 'odoo_mun_code' => '1419','odoo_mun_name' => 'El Hatillo' ]);
        DB::table('odoo_municipalities')->insert(['id'=>175,'state_id' => 1681,'odoo_municipality_id' => 175, 'odoo_mun_code' => '1403','odoo_mun_name' => 'Guaicaipuro' ]);
        DB::table('odoo_municipalities')->insert(['id'=>176,'state_id' => 1681,'odoo_municipality_id' => 176, 'odoo_mun_code' => '1404','odoo_mun_name' => 'Independencia' ]);
        DB::table('odoo_municipalities')->insert(['id'=>177,'state_id' => 1681,'odoo_municipality_id' => 177, 'odoo_mun_code' => '1405','odoo_mun_name' => 'Lander' ]);
        DB::table('odoo_municipalities')->insert(['id'=>185,'state_id' => 1681,'odoo_municipality_id' => 185, 'odoo_mun_code' => '1413','odoo_mun_name' => 'Los Salias' ]);
        DB::table('odoo_municipalities')->insert(['id'=>179,'state_id' => 1681,'odoo_municipality_id' => 179, 'odoo_mun_code' => '1407','odoo_mun_name' => 'Paz Castillo' ]);
        DB::table('odoo_municipalities')->insert(['id'=>193,'state_id' => 1681,'odoo_municipality_id' => 193, 'odoo_mun_code' => '1421','odoo_mun_name' => 'Pedro Gual' ]);
        DB::table('odoo_municipalities')->insert(['id'=>180,'state_id' => 1681,'odoo_municipality_id' => 180, 'odoo_mun_code' => '1408','odoo_mun_name' => 'Plaza' ]);
        DB::table('odoo_municipalities')->insert(['id'=>178,'state_id' => 1681,'odoo_municipality_id' => 178, 'odoo_mun_code' => '1406','odoo_mun_name' => 'Páez' ]);
        DB::table('odoo_municipalities')->insert(['id'=>187,'state_id' => 1681,'odoo_municipality_id' => 187, 'odoo_mun_code' => '1415','odoo_mun_name' => 'Simón Bolívar' ]);
        DB::table('odoo_municipalities')->insert(['id'=>181,'state_id' => 1681,'odoo_municipality_id' => 181, 'odoo_mun_code' => '1409','odoo_mun_name' => 'Sucre' ]);
        DB::table('odoo_municipalities')->insert(['id'=>182,'state_id' => 1681,'odoo_municipality_id' => 182, 'odoo_mun_code' => '1410','odoo_mun_name' => 'Urdaneta' ]);
        DB::table('odoo_municipalities')->insert(['id'=>183,'state_id' => 1681,'odoo_municipality_id' => 183, 'odoo_mun_code' => '1411','odoo_mun_name' => 'Zamora' ]);
        DB::table('odoo_municipalities')->insert(['id'=>194,'state_id' => 1682,'odoo_municipality_id' => 194, 'odoo_mun_code' => '1501','odoo_mun_name' => 'Acosta' ]);
        DB::table('odoo_municipalities')->insert(['id'=>204,'state_id' => 1682,'odoo_municipality_id' => 204, 'odoo_mun_code' => '1511','odoo_mun_name' => 'Aguasay' ]);
        DB::table('odoo_municipalities')->insert(['id'=>195,'state_id' => 1682,'odoo_municipality_id' => 195, 'odoo_mun_code' => '1502','odoo_mun_name' => 'Bolívar' ]);
        DB::table('odoo_municipalities')->insert(['id'=>196,'state_id' => 1682,'odoo_municipality_id' => 196, 'odoo_mun_code' => '1503','odoo_mun_name' => 'Caripe' ]);
        DB::table('odoo_municipalities')->insert(['id'=>197,'state_id' => 1682,'odoo_municipality_id' => 197, 'odoo_mun_code' => '1504','odoo_mun_name' => 'Cedeño' ]);
        DB::table('odoo_municipalities')->insert(['id'=>198,'state_id' => 1682,'odoo_municipality_id' => 198, 'odoo_mun_code' => '1505','odoo_mun_name' => 'Ezequiel Zamora' ]);
        DB::table('odoo_municipalities')->insert(['id'=>199,'state_id' => 1682,'odoo_municipality_id' => 199, 'odoo_mun_code' => '1506','odoo_mun_name' => 'Libertador' ]);
        DB::table('odoo_municipalities')->insert(['id'=>200,'state_id' => 1682,'odoo_municipality_id' => 200, 'odoo_mun_code' => '1507','odoo_mun_name' => 'Maturín' ]);
        DB::table('odoo_municipalities')->insert(['id'=>201,'state_id' => 1682,'odoo_municipality_id' => 201, 'odoo_mun_code' => '1508','odoo_mun_name' => 'Piar' ]);
        DB::table('odoo_municipalities')->insert(['id'=>202,'state_id' => 1682,'odoo_municipality_id' => 202, 'odoo_mun_code' => '1509','odoo_mun_name' => 'Punceres' ]);
        DB::table('odoo_municipalities')->insert(['id'=>205,'state_id' => 1682,'odoo_municipality_id' => 205, 'odoo_mun_code' => '1512','odoo_mun_name' => 'Santa Bárbara' ]);
        DB::table('odoo_municipalities')->insert(['id'=>203,'state_id' => 1682,'odoo_municipality_id' => 203, 'odoo_mun_code' => '1510','odoo_mun_name' => 'Sotillo' ]);
        DB::table('odoo_municipalities')->insert(['id'=>206,'state_id' => 1682,'odoo_municipality_id' => 206, 'odoo_mun_code' => '1513','odoo_mun_name' => 'Uracoa' ]);
        DB::table('odoo_municipalities')->insert(['id'=>216,'state_id' => 1683,'odoo_municipality_id' => 216, 'odoo_mun_code' => '1610','odoo_mun_name' => 'Antolín Del Campo' ]);
        DB::table('odoo_municipalities')->insert(['id'=>207,'state_id' => 1683,'odoo_municipality_id' => 207, 'odoo_mun_code' => '1601','odoo_mun_name' => 'Arismendi' ]);
        DB::table('odoo_municipalities')->insert(['id'=>208,'state_id' => 1683,'odoo_municipality_id' => 208, 'odoo_mun_code' => '1602','odoo_mun_name' => 'Díaz' ]);
        DB::table('odoo_municipalities')->insert(['id'=>217,'state_id' => 1683,'odoo_municipality_id' => 217, 'odoo_mun_code' => '1611','odoo_mun_name' => 'García' ]);
        DB::table('odoo_municipalities')->insert(['id'=>209,'state_id' => 1683,'odoo_municipality_id' => 209, 'odoo_mun_code' => '1603','odoo_mun_name' => 'Gómez' ]);
        DB::table('odoo_municipalities')->insert(['id'=>210,'state_id' => 1683,'odoo_municipality_id' => 210, 'odoo_mun_code' => '1604','odoo_mun_name' => 'Maneiro' ]);
        DB::table('odoo_municipalities')->insert(['id'=>211,'state_id' => 1683,'odoo_municipality_id' => 211, 'odoo_mun_code' => '1605','odoo_mun_name' => 'Marcano' ]);
        DB::table('odoo_municipalities')->insert(['id'=>212,'state_id' => 1683,'odoo_municipality_id' => 212, 'odoo_mun_code' => '1606','odoo_mun_name' => 'Mariño' ]);
        DB::table('odoo_municipalities')->insert(['id'=>213,'state_id' => 1683,'odoo_municipality_id' => 213, 'odoo_mun_code' => '1607','odoo_mun_name' => 'Península De Macanao' ]);
        DB::table('odoo_municipalities')->insert(['id'=>215,'state_id' => 1683,'odoo_municipality_id' => 215, 'odoo_mun_code' => '1609','odoo_mun_name' => 'Tubores' ]);
        DB::table('odoo_municipalities')->insert(['id'=>214,'state_id' => 1683,'odoo_municipality_id' => 214, 'odoo_mun_code' => '1608','odoo_mun_name' => 'Villalba' ]);
        DB::table('odoo_municipalities')->insert(['id'=>227,'state_id' => 1684,'odoo_municipality_id' => 227, 'odoo_mun_code' => '1710','odoo_mun_name' => 'Agua Blanca' ]);
        DB::table('odoo_municipalities')->insert(['id'=>218,'state_id' => 1684,'odoo_municipality_id' => 218, 'odoo_mun_code' => '1701','odoo_mun_name' => 'Araure' ]);
        DB::table('odoo_municipalities')->insert(['id'=>219,'state_id' => 1684,'odoo_municipality_id' => 219, 'odoo_mun_code' => '1702','odoo_mun_name' => 'Esteller' ]);
        DB::table('odoo_municipalities')->insert(['id'=>220,'state_id' => 1684,'odoo_municipality_id' => 220, 'odoo_mun_code' => '1703','odoo_mun_name' => 'Guanare' ]);
        DB::table('odoo_municipalities')->insert(['id'=>221,'state_id' => 1684,'odoo_municipality_id' => 221, 'odoo_mun_code' => '1704','odoo_mun_name' => 'Guanarito' ]);
        DB::table('odoo_municipalities')->insert(['id'=>226,'state_id' => 1684,'odoo_municipality_id' => 226, 'odoo_mun_code' => '1709','odoo_mun_name' => 'Monseñor José Vicente De Unda' ]);
        DB::table('odoo_municipalities')->insert(['id'=>222,'state_id' => 1684,'odoo_municipality_id' => 222, 'odoo_mun_code' => '1705','odoo_mun_name' => 'Ospino' ]);
        DB::table('odoo_municipalities')->insert(['id'=>228,'state_id' => 1684,'odoo_municipality_id' => 228, 'odoo_mun_code' => '1711','odoo_mun_name' => 'Papelón' ]);
        DB::table('odoo_municipalities')->insert(['id'=>223,'state_id' => 1684,'odoo_municipality_id' => 223, 'odoo_mun_code' => '1706','odoo_mun_name' => 'Páez' ]);
        DB::table('odoo_municipalities')->insert(['id'=>229,'state_id' => 1684,'odoo_municipality_id' => 229, 'odoo_mun_code' => '1712','odoo_mun_name' => 'San Genaro De Boconoito' ]);
        DB::table('odoo_municipalities')->insert(['id'=>230,'state_id' => 1684,'odoo_municipality_id' => 230, 'odoo_mun_code' => '1713','odoo_mun_name' => 'San Rafael De Onoto' ]);
        DB::table('odoo_municipalities')->insert(['id'=>231,'state_id' => 1684,'odoo_municipality_id' => 231, 'odoo_mun_code' => '1714','odoo_mun_name' => 'Santa Rosalía' ]);
        DB::table('odoo_municipalities')->insert(['id'=>224,'state_id' => 1684,'odoo_municipality_id' => 224, 'odoo_mun_code' => '1707','odoo_mun_name' => 'Sucre' ]);
        DB::table('odoo_municipalities')->insert(['id'=>225,'state_id' => 1684,'odoo_municipality_id' => 225, 'odoo_mun_code' => '1708','odoo_mun_name' => 'Turén' ]);
        DB::table('odoo_municipalities')->insert(['id'=>242,'state_id' => 1685,'odoo_municipality_id' => 242, 'odoo_mun_code' => '1811','odoo_mun_name' => 'Andrés Eloy Blanco' ]);
        DB::table('odoo_municipalities')->insert(['id'=>244,'state_id' => 1685,'odoo_municipality_id' => 244, 'odoo_mun_code' => '1813','odoo_mun_name' => 'Andrés Mata' ]);
        DB::table('odoo_municipalities')->insert(['id'=>232,'state_id' => 1685,'odoo_municipality_id' => 232, 'odoo_mun_code' => '1801','odoo_mun_name' => 'Arismendi' ]);
        DB::table('odoo_municipalities')->insert(['id'=>233,'state_id' => 1685,'odoo_municipality_id' => 233, 'odoo_mun_code' => '1802','odoo_mun_name' => 'Benítez' ]);
        DB::table('odoo_municipalities')->insert(['id'=>234,'state_id' => 1685,'odoo_municipality_id' => 234, 'odoo_mun_code' => '1803','odoo_mun_name' => 'Bermúdez' ]);
        DB::table('odoo_municipalities')->insert(['id'=>245,'state_id' => 1685,'odoo_municipality_id' => 245, 'odoo_mun_code' => '1814','odoo_mun_name' => 'Bolívar' ]);
        DB::table('odoo_municipalities')->insert(['id'=>235,'state_id' => 1685,'odoo_municipality_id' => 235, 'odoo_mun_code' => '1804','odoo_mun_name' => 'Cajigal' ]);
        DB::table('odoo_municipalities')->insert(['id'=>246,'state_id' => 1685,'odoo_municipality_id' => 246, 'odoo_mun_code' => '1815','odoo_mun_name' => 'Cruz Salmerón Acosta' ]);
        DB::table('odoo_municipalities')->insert(['id'=>243,'state_id' => 1685,'odoo_municipality_id' => 243, 'odoo_mun_code' => '1812','odoo_mun_name' => 'Libertador' ]);
        DB::table('odoo_municipalities')->insert(['id'=>236,'state_id' => 1685,'odoo_municipality_id' => 236, 'odoo_mun_code' => '1805','odoo_mun_name' => 'Mariño' ]);
        DB::table('odoo_municipalities')->insert(['id'=>237,'state_id' => 1685,'odoo_municipality_id' => 237, 'odoo_mun_code' => '1806','odoo_mun_name' => 'Mejía' ]);
        DB::table('odoo_municipalities')->insert(['id'=>238,'state_id' => 1685,'odoo_municipality_id' => 238, 'odoo_mun_code' => '1807','odoo_mun_name' => 'Montes' ]);
        DB::table('odoo_municipalities')->insert(['id'=>239,'state_id' => 1685,'odoo_municipality_id' => 239, 'odoo_mun_code' => '1808','odoo_mun_name' => 'Ribero' ]);
        DB::table('odoo_municipalities')->insert(['id'=>240,'state_id' => 1685,'odoo_municipality_id' => 240, 'odoo_mun_code' => '1809','odoo_mun_name' => 'Sucre' ]);
        DB::table('odoo_municipalities')->insert(['id'=>241,'state_id' => 1685,'odoo_municipality_id' => 241, 'odoo_mun_code' => '1810','odoo_mun_name' => 'Valdez' ]);
        DB::table('odoo_municipalities')->insert(['id'=>264,'state_id' => 1686,'odoo_municipality_id' => 264, 'odoo_mun_code' => '1918','odoo_mun_name' => 'Andrés Bello' ]);
        DB::table('odoo_municipalities')->insert(['id'=>269,'state_id' => 1686,'odoo_municipality_id' => 269, 'odoo_mun_code' => '1923','odoo_mun_name' => 'Antonio Rómulo Costa' ]);
        DB::table('odoo_municipalities')->insert(['id'=>247,'state_id' => 1686,'odoo_municipality_id' => 247, 'odoo_mun_code' => '1901','odoo_mun_name' => 'Ayacucho' ]);
        DB::table('odoo_municipalities')->insert(['id'=>248,'state_id' => 1686,'odoo_municipality_id' => 248, 'odoo_mun_code' => '1902','odoo_mun_name' => 'Bolívar' ]);
        DB::table('odoo_municipalities')->insert(['id'=>250,'state_id' => 1686,'odoo_municipality_id' => 250, 'odoo_mun_code' => '1904','odoo_mun_name' => 'Cárdenas' ]);
        DB::table('odoo_municipalities')->insert(['id'=>256,'state_id' => 1686,'odoo_municipality_id' => 256, 'odoo_mun_code' => '1910','odoo_mun_name' => 'Córdoba' ]);
        DB::table('odoo_municipalities')->insert(['id'=>265,'state_id' => 1686,'odoo_municipality_id' => 265, 'odoo_mun_code' => '1919','odoo_mun_name' => 'Fernández Feo' ]);
        DB::table('odoo_municipalities')->insert(['id'=>270,'state_id' => 1686,'odoo_municipality_id' => 270, 'odoo_mun_code' => '1924','odoo_mun_name' => 'Francisco De Miranda' ]);
        DB::table('odoo_municipalities')->insert(['id'=>257,'state_id' => 1686,'odoo_municipality_id' => 257, 'odoo_mun_code' => '1911','odoo_mun_name' => 'García De Hevia' ]);
        DB::table('odoo_municipalities')->insert(['id'=>258,'state_id' => 1686,'odoo_municipality_id' => 258, 'odoo_mun_code' => '1912','odoo_mun_name' => 'Guásimos' ]);
        DB::table('odoo_municipalities')->insert(['id'=>249,'state_id' => 1686,'odoo_municipality_id' => 249, 'odoo_mun_code' => '1903','odoo_mun_name' => 'Independencia' ]);
        DB::table('odoo_municipalities')->insert(['id'=>271,'state_id' => 1686,'odoo_municipality_id' => 271, 'odoo_mun_code' => '1925','odoo_mun_name' => 'José María Vargas' ]);
        DB::table('odoo_municipalities')->insert(['id'=>252,'state_id' => 1686,'odoo_municipality_id' => 252, 'odoo_mun_code' => '1906','odoo_mun_name' => 'Junín' ]);
        DB::table('odoo_municipalities')->insert(['id'=>251,'state_id' => 1686,'odoo_municipality_id' => 251, 'odoo_mun_code' => '1905','odoo_mun_name' => 'Jáuregui' ]);
        DB::table('odoo_municipalities')->insert(['id'=>266,'state_id' => 1686,'odoo_municipality_id' => 266, 'odoo_mun_code' => '1920','odoo_mun_name' => 'Libertad' ]);
        DB::table('odoo_municipalities')->insert(['id'=>260,'state_id' => 1686,'odoo_municipality_id' => 260, 'odoo_mun_code' => '1914','odoo_mun_name' => 'Libertador' ]);
        DB::table('odoo_municipalities')->insert(['id'=>253,'state_id' => 1686,'odoo_municipality_id' => 253, 'odoo_mun_code' => '1907','odoo_mun_name' => 'Lobatera' ]);
        DB::table('odoo_municipalities')->insert(['id'=>259,'state_id' => 1686,'odoo_municipality_id' => 259, 'odoo_mun_code' => '1913','odoo_mun_name' => 'Michelena' ]);
        DB::table('odoo_municipalities')->insert(['id'=>261,'state_id' => 1686,'odoo_municipality_id' => 261, 'odoo_mun_code' => '1915','odoo_mun_name' => 'Panamericano' ]);
        DB::table('odoo_municipalities')->insert(['id'=>262,'state_id' => 1686,'odoo_municipality_id' => 262, 'odoo_mun_code' => '1916','odoo_mun_name' => 'Pedro María Ureña' ]);
        DB::table('odoo_municipalities')->insert(['id'=>272,'state_id' => 1686,'odoo_municipality_id' => 272, 'odoo_mun_code' => '1926','odoo_mun_name' => 'Rafael Urdaneta' ]);
        DB::table('odoo_municipalities')->insert(['id'=>267,'state_id' => 1686,'odoo_municipality_id' => 267, 'odoo_mun_code' => '1921','odoo_mun_name' => 'Samuel Darío Maldonado' ]);
        DB::table('odoo_municipalities')->insert(['id'=>254,'state_id' => 1686,'odoo_municipality_id' => 254, 'odoo_mun_code' => '1908','odoo_mun_name' => 'San Cristóbal' ]);
        DB::table('odoo_municipalities')->insert(['id'=>275,'state_id' => 1686,'odoo_municipality_id' => 275, 'odoo_mun_code' => '1929','odoo_mun_name' => 'San Judas Tadeo' ]);
        DB::table('odoo_municipalities')->insert(['id'=>268,'state_id' => 1686,'odoo_municipality_id' => 268, 'odoo_mun_code' => '1922','odoo_mun_name' => 'Seboruco' ]);
        DB::table('odoo_municipalities')->insert(['id'=>273,'state_id' => 1686,'odoo_municipality_id' => 273, 'odoo_mun_code' => '1927','odoo_mun_name' => 'Simón Rodríguez' ]);
        DB::table('odoo_municipalities')->insert(['id'=>263,'state_id' => 1686,'odoo_municipality_id' => 263, 'odoo_mun_code' => '1917','odoo_mun_name' => 'Sucre' ]);
        DB::table('odoo_municipalities')->insert(['id'=>274,'state_id' => 1686,'odoo_municipality_id' => 274, 'odoo_mun_code' => '1928','odoo_mun_name' => 'Torbes' ]);
        DB::table('odoo_municipalities')->insert(['id'=>255,'state_id' => 1686,'odoo_municipality_id' => 255, 'odoo_mun_code' => '1909','odoo_mun_name' => 'Uribante' ]);
        DB::table('odoo_municipalities')->insert(['id'=>290,'state_id' => 1687,'odoo_municipality_id' => 290, 'odoo_mun_code' => '2015','odoo_mun_name' => 'Andrés Bello' ]);
        DB::table('odoo_municipalities')->insert(['id'=>277,'state_id' => 1687,'odoo_municipality_id' => 277, 'odoo_mun_code' => '2002','odoo_mun_name' => 'Boconó' ]);
        DB::table('odoo_municipalities')->insert(['id'=>291,'state_id' => 1687,'odoo_municipality_id' => 291, 'odoo_mun_code' => '2016','odoo_mun_name' => 'Bolívar' ]);
        DB::table('odoo_municipalities')->insert(['id'=>283,'state_id' => 1687,'odoo_municipality_id' => 283, 'odoo_mun_code' => '2008','odoo_mun_name' => 'Candelaria' ]);
        DB::table('odoo_municipalities')->insert(['id'=>278,'state_id' => 1687,'odoo_municipality_id' => 278, 'odoo_mun_code' => '2003','odoo_mun_name' => 'Carache' ]);
        DB::table('odoo_municipalities')->insert(['id'=>279,'state_id' => 1687,'odoo_municipality_id' => 279, 'odoo_mun_code' => '2004','odoo_mun_name' => 'Escuque' ]);
        DB::table('odoo_municipalities')->insert(['id'=>292,'state_id' => 1687,'odoo_municipality_id' => 292, 'odoo_mun_code' => '2017','odoo_mun_name' => 'José Felipe Márquez Cañizales' ]);
        DB::table('odoo_municipalities')->insert(['id'=>293,'state_id' => 1687,'odoo_municipality_id' => 293, 'odoo_mun_code' => '2018','odoo_mun_name' => 'Juan Vicente Campo Elías' ]);
        DB::table('odoo_municipalities')->insert(['id'=>294,'state_id' => 1687,'odoo_municipality_id' => 294, 'odoo_mun_code' => '2019','odoo_mun_name' => 'La Ceiba' ]);
        DB::table('odoo_municipalities')->insert(['id'=>284,'state_id' => 1687,'odoo_municipality_id' => 284, 'odoo_mun_code' => '2009','odoo_mun_name' => 'Miranda' ]);
        DB::table('odoo_municipalities')->insert(['id'=>285,'state_id' => 1687,'odoo_municipality_id' => 285, 'odoo_mun_code' => '2010','odoo_mun_name' => 'Monte Carmelo' ]);
        DB::table('odoo_municipalities')->insert(['id'=>286,'state_id' => 1687,'odoo_municipality_id' => 286, 'odoo_mun_code' => '2011','odoo_mun_name' => 'Motatán' ]);
        DB::table('odoo_municipalities')->insert(['id'=>295,'state_id' => 1687,'odoo_municipality_id' => 295, 'odoo_mun_code' => '2020','odoo_mun_name' => 'Pampanito' ]);
        DB::table('odoo_municipalities')->insert(['id'=>287,'state_id' => 1687,'odoo_municipality_id' => 287, 'odoo_mun_code' => '2012','odoo_mun_name' => 'Pampán' ]);
        DB::table('odoo_municipalities')->insert(['id'=>276,'state_id' => 1687,'odoo_municipality_id' => 276, 'odoo_mun_code' => '2001','odoo_mun_name' => 'Rafael Rangel' ]);
        DB::table('odoo_municipalities')->insert(['id'=>288,'state_id' => 1687,'odoo_municipality_id' => 288, 'odoo_mun_code' => '2013','odoo_mun_name' => 'San Rafael De Carvajal' ]);
        DB::table('odoo_municipalities')->insert(['id'=>289,'state_id' => 1687,'odoo_municipality_id' => 289, 'odoo_mun_code' => '2014','odoo_mun_name' => 'Sucre' ]);
        DB::table('odoo_municipalities')->insert(['id'=>280,'state_id' => 1687,'odoo_municipality_id' => 280, 'odoo_mun_code' => '2005','odoo_mun_name' => 'Trujillo' ]);
        DB::table('odoo_municipalities')->insert(['id'=>281,'state_id' => 1687,'odoo_municipality_id' => 281, 'odoo_mun_code' => '2006','odoo_mun_name' => 'Urdaneta' ]);
        DB::table('odoo_municipalities')->insert(['id'=>282,'state_id' => 1687,'odoo_municipality_id' => 282, 'odoo_mun_code' => '2007','odoo_mun_name' => 'Valera' ]);
        DB::table('odoo_municipalities')->insert(['id'=>307,'state_id' => 1688,'odoo_municipality_id' => 307, 'odoo_mun_code' => '2112','odoo_mun_name' => 'Arístides Bastidas' ]);
        DB::table('odoo_municipalities')->insert(['id'=>296,'state_id' => 1688,'odoo_municipality_id' => 296, 'odoo_mun_code' => '2101','odoo_mun_name' => 'Bolívar' ]);
        DB::table('odoo_municipalities')->insert(['id'=>297,'state_id' => 1688,'odoo_municipality_id' => 297, 'odoo_mun_code' => '2102','odoo_mun_name' => 'Bruzual' ]);
        DB::table('odoo_municipalities')->insert(['id'=>305,'state_id' => 1688,'odoo_municipality_id' => 305, 'odoo_mun_code' => '2110','odoo_mun_name' => 'Cocorote' ]);
        DB::table('odoo_municipalities')->insert(['id'=>306,'state_id' => 1688,'odoo_municipality_id' => 306, 'odoo_mun_code' => '2111','odoo_mun_name' => 'Independencia' ]);
        DB::table('odoo_municipalities')->insert(['id'=>303,'state_id' => 1688,'odoo_municipality_id' => 303, 'odoo_mun_code' => '2108','odoo_mun_name' => 'José Antonio Páez' ]);
        DB::table('odoo_municipalities')->insert(['id'=>304,'state_id' => 1688,'odoo_municipality_id' => 304, 'odoo_mun_code' => '2109','odoo_mun_name' => 'La Trinidad' ]);
        DB::table('odoo_municipalities')->insert(['id'=>308,'state_id' => 1688,'odoo_municipality_id' => 308, 'odoo_mun_code' => '2113','odoo_mun_name' => 'Manuel Monge' ]);
        DB::table('odoo_municipalities')->insert(['id'=>298,'state_id' => 1688,'odoo_municipality_id' => 298, 'odoo_mun_code' => '2103','odoo_mun_name' => 'Nirgua' ]);
        DB::table('odoo_municipalities')->insert(['id'=>302,'state_id' => 1688,'odoo_municipality_id' => 302, 'odoo_mun_code' => '2107','odoo_mun_name' => 'Peña' ]);
        DB::table('odoo_municipalities')->insert(['id'=>299,'state_id' => 1688,'odoo_municipality_id' => 299, 'odoo_mun_code' => '2104','odoo_mun_name' => 'San Felipe' ]);
        DB::table('odoo_municipalities')->insert(['id'=>300,'state_id' => 1688,'odoo_municipality_id' => 300, 'odoo_mun_code' => '2105','odoo_mun_name' => 'Sucre' ]);
        DB::table('odoo_municipalities')->insert(['id'=>301,'state_id' => 1688,'odoo_municipality_id' => 301, 'odoo_mun_code' => '2106','odoo_mun_name' => 'Urachiche' ]);
        DB::table('odoo_municipalities')->insert(['id'=>309,'state_id' => 1688,'odoo_municipality_id' => 309, 'odoo_mun_code' => '2114','odoo_mun_name' => 'Veroes' ]);
        DB::table('odoo_municipalities')->insert(['id'=>326,'state_id' => 1689,'odoo_municipality_id' => 326, 'odoo_mun_code' => '2217','odoo_mun_name' => 'Almirante Padilla' ]);
        DB::table('odoo_municipalities')->insert(['id'=>310,'state_id' => 1689,'odoo_municipality_id' => 310, 'odoo_mun_code' => '2201','odoo_mun_name' => 'Baralt' ]);
        DB::table('odoo_municipalities')->insert(['id'=>323,'state_id' => 1689,'odoo_municipality_id' => 323, 'odoo_mun_code' => '2214','odoo_mun_name' => 'Cabimas' ]);
        DB::table('odoo_municipalities')->insert(['id'=>321,'state_id' => 1689,'odoo_municipality_id' => 321, 'odoo_mun_code' => '2212','odoo_mun_name' => 'Catatumbo' ]);
        DB::table('odoo_municipalities')->insert(['id'=>312,'state_id' => 1689,'odoo_municipality_id' => 312, 'odoo_mun_code' => '2203','odoo_mun_name' => 'Colón' ]);
        DB::table('odoo_municipalities')->insert(['id'=>329,'state_id' => 1689,'odoo_municipality_id' => 329, 'odoo_mun_code' => '2220','odoo_mun_name' => 'Francisco Javier Pulgar' ]);
        DB::table('odoo_municipalities')->insert(['id'=>325,'state_id' => 1689,'odoo_municipality_id' => 325, 'odoo_mun_code' => '2216','odoo_mun_name' => 'Jesús Enrique Lossada' ]);
        DB::table('odoo_municipalities')->insert(['id'=>328,'state_id' => 1689,'odoo_municipality_id' => 328, 'odoo_mun_code' => '2219','odoo_mun_name' => 'Jesús María Semprún' ]);
        DB::table('odoo_municipalities')->insert(['id'=>319,'state_id' => 1689,'odoo_municipality_id' => 319, 'odoo_mun_code' => '2210','odoo_mun_name' => 'La Cañada De Urdaneta' ]);
        DB::table('odoo_municipalities')->insert(['id'=>320,'state_id' => 1689,'odoo_municipality_id' => 320, 'odoo_mun_code' => '2211','odoo_mun_name' => 'Lagunillas' ]);
        DB::table('odoo_municipalities')->insert(['id'=>317,'state_id' => 1689,'odoo_municipality_id' => 317, 'odoo_mun_code' => '2208','odoo_mun_name' => 'Machiques De Perijá' ]);
        DB::table('odoo_municipalities')->insert(['id'=>313,'state_id' => 1689,'odoo_municipality_id' => 313, 'odoo_mun_code' => '2204','odoo_mun_name' => 'Mara' ]);
        DB::table('odoo_municipalities')->insert(['id'=>314,'state_id' => 1689,'odoo_municipality_id' => 314, 'odoo_mun_code' => '2205','odoo_mun_name' => 'Maracaibo' ]);
        DB::table('odoo_municipalities')->insert(['id'=>315,'state_id' => 1689,'odoo_municipality_id' => 315, 'odoo_mun_code' => '2206','odoo_mun_name' => 'Miranda' ]);
        DB::table('odoo_municipalities')->insert(['id'=>316,'state_id' => 1689,'odoo_municipality_id' => 316, 'odoo_mun_code' => '2207','odoo_mun_name' => 'Páez' ]);
        DB::table('odoo_municipalities')->insert(['id'=>322,'state_id' => 1689,'odoo_municipality_id' => 322, 'odoo_mun_code' => '2213','odoo_mun_name' => 'Rosario De Perijá' ]);
        DB::table('odoo_municipalities')->insert(['id'=>327,'state_id' => 1689,'odoo_municipality_id' => 327, 'odoo_mun_code' => '2218','odoo_mun_name' => 'San Francisco' ]);
        DB::table('odoo_municipalities')->insert(['id'=>311,'state_id' => 1689,'odoo_municipality_id' => 311, 'odoo_mun_code' => '2202','odoo_mun_name' => 'Santa Rita' ]);
        DB::table('odoo_municipalities')->insert(['id'=>330,'state_id' => 1689,'odoo_municipality_id' => 330, 'odoo_mun_code' => '2221','odoo_mun_name' => 'Simón Bolívar' ]);
        DB::table('odoo_municipalities')->insert(['id'=>318,'state_id' => 1689,'odoo_municipality_id' => 318, 'odoo_mun_code' => '2209','odoo_mun_name' => 'Sucre' ]);
        DB::table('odoo_municipalities')->insert(['id'=>324,'state_id' => 1689,'odoo_municipality_id' => 324, 'odoo_mun_code' => '2215','odoo_mun_name' => 'Valmore Rodríguez' ]);
        

    }
}
