{
    "main": "node_modules/expo/AppEntry.js",
    "scripts": {
      "start": "expo start",
      "android": "expo start --android",
      "ios": "expo start --ios",
      "eject": "expo eject",
      "test": "node ./node_modules/jest/bin/jest.js --watchAll"
    },
    "jest": {
      "preset": "jest-expo"
    },
    "rnpm": {
      "assets": [
        "assets/fonts"
      ]
    },
    "dependencies": {
      "@expo/samples": "2.1.1",
      "@expo/vector-icons": "^10.0.0",
      "@types/socket.io-client": "^1.4.32",
      "apisauce": "^1.1.1",
      "babel": "^6.23.0",
      "babel-cli": "^6.26.0",
      "core-js": "^3.6.4",
      "expo": "^36.0.0",
      "expo-asset": "~8.0.0",
      "expo-av": "~8.0.0",
      "expo-blur": "~8.0.0",
      "expo-constants": "~8.0.0",
      "expo-facebook": "~8.0.0",
      "expo-file-system": "~8.0.0",
      "expo-font": "~8.0.0",
      "expo-google-app-auth": "^7.0.0",
      "expo-image-manipulator": "~8.0.0",
      "expo-image-picker": "~8.0.1",
      "expo-linear-gradient": "~8.0.0",
      "expo-localization": "~8.0.0",
      "expo-media-library": "~8.0.0",
      "expo-permissions": "~8.0.0",
      "express": "^4.17.1",
      "firebase": "^6.6.2",
      "i18n-js": "^3.3.0",
      "lodash": "^4.17.15",
      "merge-options": "^2.0.0",
      "metro-react-native-babel-transformer": "^0.56.4",
      "node-pre-gyp": "^0.14.0",
      "react": "^16.12.0",
      "react-dom": "16.9.0",
      "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",
      "react-native-anchor-carousel": "^3.1.1",
      "react-native-app-intro-slider": "^3.0.0",
      "react-native-datepicker": "^1.7.2",
      "react-native-debugger": "^1.1.0",
      "react-native-elements": "^1.2.1",
      "react-native-expo-image-cache": "^4.1.0",
      "react-native-gesture-handler": "~1.5.0",
      "react-native-gifted-chat": "^0.13.0",
      "react-native-google-signin": "^2.1.1",
      "react-native-image-grid": "^1.0.0",
      "react-native-image-slider-show": "^1.0.3",
      "react-native-image-zoom-viewer": "^2.2.26",
      "react-native-keyboard-aware-scroll-view": "^0.9.1",
      "react-native-keyboard-spacer": "^0.4.1",
      "react-native-lightbox": "^0.8.1",
      "react-native-modal": "^11.3.1",
      "react-native-picker-select": "^6.3.3",
      "react-native-popup-dialog": "^0.18.3",
      "react-native-reanimated": "~1.4.0",
      "react-native-screens": "2.0.0-alpha.12",
      "react-native-select-input-ios": "^2.0.2",
      "react-native-select-plus": "^0.1.10",
      "react-native-sideswipe": "^1.5.0",
      "react-native-simple-twitter": "^2.3.0",
      "react-native-snap-carousel": "^3.8.4",
      "react-native-socketio": "^0.3.0",
      "react-native-svg": "9.13.3",
      "react-native-swipe-list-view": "^2.1.3",
      "react-native-switch-selector": "^2.0.2",
      "react-native-tab-view": "^2.10.0",
      "react-native-twitter": "^0.2.1",
      "react-native-vector-icons": "^6.6.0",
      "react-native-web": "^0.11.7",
      "react-navigation": "^4.0.6",
      "react-navigation-stack": "^1.9.0",
      "react-navigation-tabs": "^2.7.0",
      "react-redux": "^7.1.1",
      "reactotron-apisauce": "^3.0.0",
      "reactotron-react-native": "^4.0.0",
      "redux": "^4.0.4",
      "redux-logger": "^3.0.6",
      "redux-thunk": "^2.3.0",
      "redux-watch": "^1.1.1",
      "socket.io": "^2.3.0",
      "socket.io-client": "^2.3.0",
      "url-search-params": "^1.1.0"
    },
    "devDependencies": {
      "babel-preset-expo": "^8.0.0",
      "jest-expo": "^36.0.0"
    },
    "private": true
  }
  