version: '3.5'
services:
  web:
    build: .
    image: poraqui-page:stripe
    env_file: .env
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "${PORT}:3000"
